### ISSUE TITLE
scala/collection/Iterator.scala issues

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#913]
If compiled together with `TraversableOnce.BufferedCanBuildFrom` and `Builder` I see this issue:

```
./scala-scala/src/library/scala/collection/Iterator.scala:31: error: object creation impossible, since def apply: (from: [+hk$0] => scala.collection.Iterator[hk$0])scala.collection.mutable.Builder[A, scala.collection.Iterator[A]] is not defined
(Note that TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,generic)),CanBuildFrom)),scala$collection$generic$CanBuildFrom$$From) does not match RefinedType(TypeRef(ThisType(TypeRef(NoPrefix,collection)),TraversableOnce), scala$collection$TraversableOnce$$A, TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,scala)),Nothing), TypeRef(ThisType(TypeRef(NoPrefix,scala)),Any)) | -1064432624))
  implicit def IteratorCanBuildFrom[A]: TraversableOnce.BufferedCanBuildFrom[A, Iterator]  = new TraversableOnce.BufferedCanBuildFrom[A, Iterator] {
                                                                                                   ^
```

If compiled in isolation:

```
/scala-scala/src/library/scala/collection/Iterator.scala:31: error: Type argument A does not conform to upper bound [hk$0] =>  <: scala.collection.TraversableOnce[hk$0]
  implicit def IteratorCanBuildFrom[A]: TraversableOnce.BufferedCanBuildFrom[A, Iterator]  = new TraversableOnce.BufferedCanBuildFrom[A, Iterator] {
                                                                                                                                      ^
./scala-scala/src/library/scala/collection/Iterator.scala:32: error: type mismatch:
 found   : scala.collection.Iterator[B]
 required: A{hk$0 = B}#$apply
    def bufferToColl[B](coll: ArrayBuffer[B]) = coll.iterator
                                                     ^
dotty.tools.dotc.core.Types$MissingType: cannot resolve reference to type A{hk$0 = B}.$apply
the classfile defining the type might be missing from the classpath
	at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:447)
	at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:134)
	at dotty.tools.dotc.core.Signature$.apply(Signature.scala:76)
	at dotty.tools.dotc.core.Types$MethodicType$class.resultSignature(Types.scala:2042)
	at dotty.tools.dotc.core.Types$MethodType.resultSignature(Types.scala:2061)
	at dotty.tools.dotc.core.Types$MethodType.computeSignature(Types.scala:2133)
	at dotty.tools.dotc.core.Types$MethodicType$class.signature(Types.scala:2052)
	at dotty.tools.dotc.core.Types$MethodType.signature(Types.scala:2061)
	at dotty.tools.dotc.core.Types$MethodicType$class.resultSignature(Types.scala:2041)
	at dotty.tools.dotc.core.Types$PolyType.resultSignature(Types.scala:2252)
	at dotty.tools.dotc.core.Types$PolyType.computeSignature(Types.scala:2260)
	at dotty.tools.dotc.core.Types$MethodicType$class.signature(Types.scala:2052)
	at dotty.tools.dotc.core.Types$PolyType.signature(Types.scala:2252)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:452)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.termRefWithSig(SymDenotations.scala:1048)
	at dotty.tools.dotc.typer.TypeAssigner$class.assignType(TypeAssigner.scala:399)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:57)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1.apply(Typer.scala:913)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1.apply(Typer.scala:905)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:905)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1086)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1136)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1170)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1181)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:941)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:924)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:924)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1089)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1136)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1170)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1181)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedBlock$1.apply(Typer.scala:451)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedBlock$1.apply(Typer.scala:449)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:449)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1106)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1138)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedNew$1.apply(Typer.scala:346)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedNew$1.apply(Typer.scala:341)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedNew(Typer.scala:340)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1101)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1138)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1185)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1.apply(Typer.scala:912)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1.apply(Typer.scala:905)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:905)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1086)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1136)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1170)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1181)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:941)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:924)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:924)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1089)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1136)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1170)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1181)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1029)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1020)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1020)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1126)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1138)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1176)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1181)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1029)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1020)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1020)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1126)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1138)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1185)
	at dotty.tools.dotc.typer.FrontEnd$$anonfun$typeCheck$1.apply$mcV$sp(FrontEnd.scala:42)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:19)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:40)
	at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:53)
	at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:53)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:53)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:59)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:56)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:56)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:69)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:52)
	at dotty.tools.dotc.Run.compileSources(Run.scala:49)
	at dotty.tools.dotc.Run.compile(Run.scala:33)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:21)
	at dotty.tools.dotc.Driver.process(Driver.scala:44)
	at dotty.tools.dotc.Driver.main(Driver.scala:48)
	at dotty.tools.dotc.Main.main(Main.scala)
cannot take signature of [B](coll: scala.collection.mutable.ArrayBuffer[B])A{hk$0 = B}#$apply
./scala-scala/src/library/scala/collection/Iterator.scala:32: error: cannot resolve reference to type A{hk$0 = B}.$apply
the classfile defining the type might be missing from the classpath
    def bufferToColl[B](coll: ArrayBuffer[B]) = coll.iterator
        ^
./scala-scala/src/library/scala/collection/Iterator.scala:33: error: type mismatch:
 found   : scala.collection.Iterator[B]
 required: A{hk$0 = B}#$apply
    def traversableToColl[B](t: GenTraversable[B]) = t.toIterator
                                                       ^
dotty.tools.dotc.core.Types$MissingType: cannot resolve reference to type A{hk$0 = B}.$apply
the classfile defining the type might be missing from the classpath
	at dotty.tools.dotc.core.TypeErasure.dotty$tools$dotc$core$TypeErasure$$sigName(TypeErasure.scala:447)
	at dotty.tools.dotc.core.TypeErasure$.sigName(TypeErasure.scala:134)
	at dotty.tools.dotc.core.Signature$.apply(Signature.scala:76)
	at dotty.tools.dotc.core.Types$MethodicType$class.resultSignature(Types.scala:2042)
	at dotty.tools.dotc.core.Types$MethodType.resultSignature(Types.scala:2061)
	at dotty.tools.dotc.core.Types$MethodType.computeSignature(Types.scala:2133)
	at dotty.tools.dotc.core.Types$MethodicType$class.signature(Types.scala:2052)
	at dotty.tools.dotc.core.Types$MethodType.signature(Types.scala:2061)
	at dotty.tools.dotc.core.Types$MethodicType$class.resultSignature(Types.scala:2041)
	at dotty.tools.dotc.core.Types$PolyType.resultSignature(Types.scala:2252)
	at dotty.tools.dotc.core.Types$PolyType.computeSignature(Types.scala:2260)
	at dotty.tools.dotc.core.Types$MethodicType$class.signature(Types.scala:2052)
	at dotty.tools.dotc.core.Types$PolyType.signature(Types.scala:2252)
	at dotty.tools.dotc.core.Denotations$SingleDenotation.signature(Denotations.scala:452)
	at dotty.tools.dotc.core.SymDenotations$SymDenotation.termRefWithSig(SymDenotations.scala:1048)
	at dotty.tools.dotc.typer.TypeAssigner$class.assignType(TypeAssigner.scala:399)
	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:57)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1.apply(Typer.scala:913)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1.apply(Typer.scala:905)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:905)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1086)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1136)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1170)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1181)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:941)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:924)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:924)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1089)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1136)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1170)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1181)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedBlock$1.apply(Typer.scala:451)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedBlock$1.apply(Typer.scala:449)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:449)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1106)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1138)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedNew$1.apply(Typer.scala:346)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedNew$1.apply(Typer.scala:341)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedNew(Typer.scala:340)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1101)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1138)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1185)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1.apply(Typer.scala:912)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedDefDef$1.apply(Typer.scala:905)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:905)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1086)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1136)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1170)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1181)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:941)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedClassDef$1.apply(Typer.scala:924)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:924)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1089)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1136)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1170)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1181)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1029)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1020)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1020)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1126)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1138)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:1176)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:1181)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1029)
	at dotty.tools.dotc.typer.Typer$$anonfun$typedPackageDef$1.apply(Typer.scala:1020)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:36)
	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1020)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1126)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1138)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1148)
	at dotty.tools.dotc.typer.Typer$$anonfun$typed$2.apply(Typer.scala:1146)
	at dotty.tools.dotc.reporting.Reporting$class.traceIndented(Reporter.scala:148)
	at dotty.tools.dotc.core.Contexts$Context.traceIndented(Contexts.scala:53)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:1146)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:1185)
	at dotty.tools.dotc.typer.FrontEnd$$anonfun$typeCheck$1.apply$mcV$sp(FrontEnd.scala:42)
	at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:19)
	at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:40)
	at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:53)
	at dotty.tools.dotc.typer.FrontEnd$$anonfun$runOn$3.apply(FrontEnd.scala:53)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:53)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:59)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1$$anonfun$apply$mcV$sp$1.apply(Run.scala:56)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply$mcV$sp(Run.scala:56)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
	at dotty.tools.dotc.Run$$anonfun$compileUnits$1.apply(Run.scala:52)
	at dotty.tools.dotc.util.Stats$.monitorHeartBeat(Stats.scala:69)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:52)
	at dotty.tools.dotc.Run.compileSources(Run.scala:49)
	at dotty.tools.dotc.Run.compile(Run.scala:33)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:21)
	at dotty.tools.dotc.Driver.process(Driver.scala:44)
	at dotty.tools.dotc.Driver.main(Driver.scala:48)
	at dotty.tools.dotc.Main.main(Main.scala)
cannot take signature of [B](t: scala.collection.GenTraversable[B])A{hk$0 = B}#$apply
./scala-scala/src/library/scala/collection/Iterator.scala:33: error: cannot resolve reference to type A{hk$0 = B}.$apply
the classfile defining the type might be missing from the classpath
    def traversableToColl[B](t: GenTraversable[B]) = t.toIterator
        ^
5 errors found
```

**Comment by DarkDimius** [comment]
may be a duplicate of https://github.com/lampepfl/dotty/issues/914
