### ISSUE TITLE
Ignored upper bound of type parameter

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#2888]
In scala/collection-strawman, [this line](https://github.com/scala/collection-strawman/blob/map-ops/src/main/scala/strawman/collection/immutable/Map.scala#L37) gives the following compilation error:

~~~
def removeAll(keys: IterableOnce[K]): C = fromSpecificIterable(keys.iterator().foldLeft[CC[K, V]](coll)(_ - _))
                                                                                                        ^^^
                                 value `-` is not a member of CC[K, V]
~~~

Though `CC` is upper bounded by `MapOps` (see [here](https://github.com/scala/collection-strawman/blob/map-ops/src/main/scala/strawman/collection/immutable/Map.scala#L14)), which provides the `-` operation. Note that the `CC` upper bound is recursive.

This code compiles fine with Scala 2.12 and 2.13.

**Comment by julienrf** [comment]
Here is a self-contained reduced test case: https://scastie.scala-lang.org/g03Noc6YT1aZaHK0hbLG1Q

Not only `CC` is F-bounded, but we also have the `C` type parameter which is upper bounded by `CC`.

**Comment by julienrf** [comment]
Though type `C` is not involved in the expression that raises the type error, if I remove it from `Foo` definition, then the error disappears.

**Comment by odersky** [comment]
A beauty! Yet another nasty interaction between F-bounds and higher kinded types.
