### PR TITLE
Fix #17667 account for import order

### LINKED ISSUE #17667: `-Wunused:import` gets confused on import both locally and globally in file
Ran into this when migrating workplace code to 3.3.0. Tried to minimize the code as much as possible, might be more available. When importing something from an object in the local scope and in global, unused:import gets confused about which one is actually needed.

## Minimized code

```scala
//> using scala 3.3.0
//> using option -Wunused:imports

object MyImplicits:
  extension (a: Int) def print: Unit = println(s"Hello, I am $a")

import MyImplicits.print //Global import of extension
object Foo:
  def printInt(a: Int): Unit = a.print
  import MyImplicits._ //Local import of extension

Foo.printInt(1)
```

## Output

```
scala-cli .
[warn] ./main.sc:7:20
[warn] unused import
[warn] import MyImplicits.print
[warn]                    ^^^^^
Hello, I am 1
```

If I follow the "instructions" and remove the import on line 7..

```scala
//import MyImplicits.print
object Foo:
  def printInt(a: Int): Unit = a.print
  import MyImplicits._
```
gives
```
scala-cli .
Compiling project (Scala 3.3.0, JVM)
[error] ./main.sc:8:32
[error] value print is not a member of Int, but could be made available as an extension method.
[error] 
[error] The following import might fix the problem:
[error] 
[error]   import main$_.this.MyImplicits.print
[error] 
[error]   def printInt(a: Int): Unit = a.print
[error]                                ^^^^^^^
```

Though removing the other one
```scala
import MyImplicits.print
object Foo:
  def printInt(a: Int): Unit = a.print
  // import MyImplicits._
```

Removes the warning correctly 
```scala
scala-cli .
Compiling project (Scala 3.3.0, JVM)
Compiled project (Scala 3.3.0, JVM)
Hello, I am 1
```

## Expectation
The warning refers to the import that actually can be safely removed on line 10, not 7
```
scala-cli .
[warn] ./main.sc:10:22
[warn] unused import
[warn] import MyImplicits._
[warn]                    ^^^^^
Hello, I am 1
```

### PR DESCRIPTION
**Pull request by PaulCoral**
- Imports in the same scope, but after the usage are reported.
- Add test suit i17667
- Fix test i15503a

### CODE REVIEW

File: tests/neg-custom-args/fatal-warnings/i15503a.scala [hunk 1]
```diff
@@ -68,7 +68,7 @@ object InlineChecks:
     inline def getSet = Set(1)
 
   object InlinedBar:
-    import collection.mutable.Set // ok
+    import collection.mutable.Set // error
```
Comment (PaulCoral) [inline tests/neg-custom-args/fatal-warnings/i15503a.scala:71]: @szymon-rd 
I was just wondering about this one, it seems like this import is not required. It can be removed and still get the correct result : https://scastie.scala-lang.org/9pyvzVWyTAyBsOPduePhqg
Am I missing something ?

Comment (szymon-rd) [reply tests/neg-custom-args/fatal-warnings/i15503a.scala:71]: No, you are correct. Some of these tests lay out the expected false negatives. If this is not a false negative, then great.

**Review by szymon-rd — CHANGES_REQUESTED** [review]
Looks great! I just left one comment, and could you fix the failing test?

**Comment by szymon-rd** [comment]
@PaulCoral Can I finish this PR? Or are you planning to come back to it?

**Comment by PaulCoral** [comment]
@szymon-rd Yes, sure! Sorry for this, I was stuck with this last test, which seems to be related to "derives" (again...). I don't think I will have time soon for this, so you can go for it.

**Comment by som-snytt** [comment]
I think this stale PR can be retired. Tracking imports by source position does not seem like a natural approach.

**Comment by Gedochao** [comment]
Closing due to inactivity.
Feel free to open another attempt.
