### ISSUE TITLE
Inlining failure when accessing same-named private members in sub and superclass

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#15612]
Based on the community build failure https://scala3.westeurope.cloudapp.azure.com/blue/organizations/jenkins/buildCommunityProject/detail/buildCommunityProject/1136/pipeline/
Library maintainer @tabdulradi

Problem exists only if both open classes define extension methods using type matching

## Compiler version
Works in 3.1.3
Fails in 3.2.0-RC1 and RC2
Fails in 3.2.1-RC1-bin-20220706-9d07d52-NIGHTLY

## Minimized code

```Scala
import scala.reflect.TypeTest

open class ForSyntax[E](using E: TypeTest[E | Any, E]):
  extension [A](aOrE: E | A)
    inline def flatMap[B](f: A => E | B): E | B =
      aOrE match
        case e: E => ???
        case _ => ???


open class UnhappyCase[E](using E: TypeTest[E | Any, E]) extends ForSyntax[E]: 
  extension [A](aOrE: E | A) 
    inline def fold[B](inline fe: E => B, inline fa: A => B): B =
      aOrE match
        case e: E => ??? 
        case _ => ???

```

## Output

```scala
[error] ./test.scala:11:33: error overriding method inline$E in class ForSyntax of type => reflect.TypeTest[E | Any, E];
[error]   method inline$E of type => reflect.TypeTest[E | Any, E] cannot override final member method inline$E in class ForSyntax
[error] open class UnhappyCase[E](using E: TypeTest[E | Any, E]) extends ForSyntax[E]: 
[error]                                 ^
Error compiling project (Scala 3.2.1-RC1-bin-20220706-9d07d52-NIGHTLY, JVM)
```

## Expectation
Should compile

**Comment by KacperFKorban** [comment]
### Minimization

A bit smaller example:
```scala
class Parent[E](using u: Unit):
  inline def m: Any = u

class Klass[E](using u: Unit) extends Parent[E]:
  inline def n: Any = u
```

Error:
```scala
-- [E164] Declaration Error: tests/pos/i15612.scala:4:21 -----------------------
4 |class Klass[E](using u: Unit) extends Parent[E]:
  |                     ^
  |error overriding method inline$u in class Parent of type => Unit;
  |  method inline$u of type => Unit cannot override final member method inline$u in class Parent
```

### Explanation

The first commit that breaks this is: https://github.com/lampepfl/dotty/pull/15324/commits/13df1bc386211229bd033bf209dfb822ed6c8810

The problem here is that the `given val`s are `private` and so the inline accessors are generated to be `final` not to override them by mistake.

### Workaround

A possible workaround here is to make those `given`s `protected and override them explicitly. (since semantically those `TypeTests` are the same for us) Like so:

```scala
class Parent[E](using protected val u: Unit):
  extension [A](aOrE: E | A)
    inline def m: Any = u

class Klass[E](using override protected val u: Unit) extends Parent[E]: 
  extension [A](aOrE: E | A) 
    inline def n: Any = u
```

**Comment by odersky** [comment]
Minimization:
```scala
class A:
  private val a = 1
  inline def foo() = a
class B extends A:
  private val a = 2
  inline def bar() = a
```
