### ISSUE TITLE
Safer Exceptions throws clauses have stopped working

### ISSUE THREAD

**Issue by reftrans** [lampepfl/dotty#17040]
## Compiler version

The problem is introduced in https://github.com/lampepfl/dotty/commit/e422066c3da9fb02db9f9495e27cfddef719703e.
## Minimized code
```Scala
import language.experimental.saferExceptions
def fail(): Unit throws Exception = throw Exception()
```

## Output

```scala
3 |def fail(): Unit throws Exception = throw Exception()
  |                                    ^^^^^^^^^^^^^^^^^
  |                                    The capability to throw exception Exception is missing.
  |                                    The capability can be provided by one of the following:
  |                                     - Adding a using clause `(using CanThrow[Exception])` to the definition of the enclosing method
  |                                     - Adding `throws Exception` clause after the result type of the enclosing method
  |                                     - Wrapping this piece of code with a `try` block that catches Exception
  |
  |                                    The following import might fix the problem:
  |
  |                                      import unsafeExceptions.canThrowAny
  |
1 error found
```

It compiles normally with a `using CanThrow[Exception]` clause instead of `throws Exception`.

## Expectation

Same behavior as for `using` clause.

**Comment by natsukagami** [comment]
Can you provide me with more details?
I cannot produce a compilation error with your minimized example (both on https://github.com/lampepfl/dotty/commit/e422066c3da9fb02db9f9495e27cfddef719703e and on latest main)

**Comment by reftrans** [comment]
I tried it again, and it was still broken for me so I looked a bit deeper: The problem is reproducible only after an incremental build of Dotty from an earlier commit. The following should show the problem with fail.scala is the minimised code above:
```sh
# inside lampepfl/dotty repo:
git checkout f02f7dda64
bin/scalac fail.scala
# builds previous version of scalac and compiles successfully
git checkout e422066c3d
bin/scalac fail.scala
# builds "next" version of scalac and and shows the error message above
```

I was able to avoid the problem by cloning a fresh Dotty repository and rebuilding from clean.

So, you're right, the error is not reproducible in general. Sorry for wasting your time, @natsukagami. Hopefully this is useful for anyone else who is building Dotty from source, though.

**Comment by natsukagami** [comment]
It seems like a problem with library rebuilding. I’m not sure what’s the
best way to resolve it either, but usually a clean build fixes it ;)

Benoît ***@***.***> schrieb am Di. 7. März 2023 um 12:13 PM:

**Comment by odersky** [comment]
One should never require a clean build. Something must be wrong with the logic that requires this. It's usually some piece of state that should not exist.

**Comment by natsukagami** [comment]
What happened was that the cached `$throws[T, E]` in the library was previously compiled into `scala.ErasedContextFunction1[CanThrow[E], T]`; and is compiled into a `scala.runtime.ErasedFunction` now. 
I wonder how would the incremental compilation would deal with this (since there is no change to the library, just how it was compiled). 
In fact, following the above mentioned step with a definition that would not throw a `TypeError`, such as
```scala
import language.experimental.saferExeptions

def fail: Int throws Exception = ???
```
will cause the compiler to crash, since `scala.ErasedContextFunction1` is no longer a thing.

**Comment by natsukagami** [comment]
I think this is a TASTy incompatibility problem...?
