### PR TITLE
Fix #7421: Insert missing <outdent> tokens where a region ends

### LINKED ISSUE #7421: Dotty fails to compile with `}` and `else` on the same line
The following style if/else statements are failing to compile on Dotty version 0.19.0-RC1

## minimized code
```
object Main {

  def main(args: Array[String]): Unit = {
    if (args.length > 0)
      {
        println(args)
      } else {
      println("Hello world!")
    }
  }
}
```

## expectation

This should compile as it does in Scala 2.12

## actual
This fails to compile:
```
[error] -- Error: D:\code\dotty-cont\dottyplayground\src\main\scala\Main.scala:7:8 -----
[error] 7 |      } else {                                                                                               [error]   |        ^^^^                                                                                                 [error]   |        end of statement expected but else found                                                             [error] -- [E040] Syntax Error: D:\code\dotty-cont\dottyplayground\src\main\scala\Main.scala:7:13
[error] 7 |      } else {                                                                                               [error]   |             ^                                                                                               [error]   |             ';' expected, but '{' found                                                                     [error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 5 s, completed Oct 13, 2019 9:12:30 PM
```
The workaround is simple but this behavior is unexpected.

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by odersky** [comment]
@smarter: No, it works with or without `then`.

**Comment by smarter** [comment]
I worry this might be too permissive, e.g. the following becomes valid:
```scala
    if (args.length > 0)
      1
      if (args.length > 1)
        2
      else 3 else 4
```
Maybe a warning recommending adding a new unindented line would be appropriate.

**Comment by smarter** [comment]
> I worry this might be too permissive

Maybe we can restrict this by only calling `in.observeOutdented()` if the previous token was a closing brace ?

**Comment by odersky** [comment]
> I worry this might be too permissive, e.g. the following becomes valid:

But why reject it?
