### PR TITLE
Fix quoted pattens with references to private fields

### LINKED ISSUE #15676: Package private method cannot be matched using quotes API
Community build regression for https://github.com/ciaraobrien/dottytags (maintainer @ciaraobrien)
Based on [Open Community Build #1858](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/1858/)
Part of https://github.com/lampepfl/dotty/issues/15647 regressions tracker
## Compiler version
Works with 3.1.0
Fails in 3.1.1
Fails in 3.2.1-RC1-bin-20220712-7e20b81-NIGHTLYon` instead).

## Minimized code

```Scala
package dottytags

import scala.quoted.*

class TagClass private[dottytags] (val name: String)
private[dottytags] object TagClass:
  def apply(name: String): TagClass = new TagClass(name)

inline def tag(inline name: String): TagClass = ${ tagClassMacro('name) }
private def tagClassMacro(nameExpr: Expr[String])(using Quotes): Expr[TagClass] = {
  val tgExpr = Expr(TagClass(nameExpr.value.get))
  TagClassFromExpr.unapply(tgExpr).foreach(println) // To trigger failure
  tgExpr
}

private given TagClassFromExpr: FromExpr[TagClass] with
  def unapply(x: Expr[TagClass])(using Quotes): Option[TagClass] =
    x match
      case '{ TagClass(${ Expr(name: String) }) } =>
        println(s"in apply, name=$name)")
        Some(TagClass(name))
      case _ =>
        import quotes.reflect.report
        report.error(s"Failed to extract value from ${x.show}")
        None

private given TagClassToExpr: ToExpr[TagClass] with
  def apply(x: TagClass)(using Quotes): Expr[TagClass] = '{ TagClass(${ Expr(x.name) }) }
```

## Output

```scala
-- Error: test.scala:4:13 -------------------------------------------------------------------------------------------------------
4 |  println(tag("html"))
  |          ^^^^^^^^^^^
  |          Failed to extract value from dottytags.macro$package.inline$TagClass.apply("html")
1 error found
```

## Expectation
Compiles with the same output as in 3.1.0:
```
in apply, name=html)
dottytags.TagClass@5b3a8bea
```

### PR DESCRIPTION
**Pull request by nicolasstucki**
Reverts 0b072d6b7df6d9c65d6ffce779c3417df42b47bd

Fixes #15676

### CODE REVIEW

**Comment by KacperFKorban** [comment]
It seems that not making pattern quotes inlinable actually fixed `quill`, because the same part of CI failed in https://github.com/lampepfl/dotty/pull/13547 before https://github.com/lampepfl/dotty/commit/0b072d6b7df6d9c65d6ffce779c3417df42b47bd. :thinking: 
```scala
[error] -- Error: /__w/dotty/dotty/community-build/community-projects/protoquill/quill-sql/src/main/scala/io/getquill/parser/Parser.scala:655:14 
[error] 655 |    case '{ ($i: InfixValue).generic.pure.as[t] } => genericInfix(i)(true, Quat.Generic)
[error]     |              ^
[error]     |              access to InfixParser.this from wrong staging level:
[error]     |               - the definition is at level 0,
[error]     |               - but the access is at level 1.
[error] one error found
[error] (quill-sql / Compile / compileIncremental) Compilation failed
[error] Total time: 24 s, completed Aug 9, 2022 11:57:12 AM
```

**Comment by nicolasstucki** [comment]
To fix this we will need to minimize the failure of quill. I do not have time to do it now.

**Comment by KacperFKorban** [comment]
OK, I'll try to minimize it then

**Comment by KacperFKorban** [comment]
The minimized code looks like so:
```scala
package getquill

import scala.quoted.*

class InfixParser(using Quotes) {
  import quotes.reflect.*
  def attempt: Expr[Any] => Unit = {
    case '{ ($i: InfixValue).a } => ???
    case '{ ($i: InfixValue).b } => ??? // error
  }
}

private[getquill] trait InfixValue {
  def a: InfixValue
  private[getquill] def b: InfixValue
}
```

Error msg:
```scala
[error] ./quill-bug/_1.scala:9:15: access to InfixParser.this from wrong staging level:
[error]  - the definition is at level 0,
[error]  - but the access is at level 1.
[error]     case '{ ($i: InfixValue).b } => ???
[error]               ^
```

An accessor is generated for `b`, since it is qualified private and then it is accessed as `this.inline$b$i1` in the case pattern.

**Comment by nicolasstucki** [comment]
Minimized the quill example furder
```scala
package foo

class Test:
  import scala.quoted.*
  def test(i: Expr[A])(using Quotes): Expr[Unit] = '{ $i.b }

trait A:
  private[foo] def b: Unit
```
```
5 |  def test(i: Expr[A])(using Quotes): Expr[Unit] = '{ $i.b }
  |                                                      ^
  |                             access to Test.this from wrong staging level:
  |                              - the definition is at level 0,
  |                              - but the access is at level 1.
```

The code after typer is 
```scala
package foo {
  class Test() extends Object() {
    import scala.quoted.*
    def test(i: quoted.Expr[foo.A])(using x$2: quoted.Quotes): quoted.Expr[Unit]
       = 
    '{
      this.inline$b$i1(
        ${
          {
            def $anonfun(using evidence$1: quoted.Quotes): quoted.Expr[foo.A] = 
              i
            closure($anonfun)
          }
        }
      )
    }.apply(x$2)
    def inline$b$i1(x$0: foo.A): Unit = x$0.b
  }
  trait A() extends Object {
    private[foo] def b: Unit
  }
}
```
Note that `inline$b$i1` is added in the `Test` class. This is why we have the extra `Test.this` reference. This method should be added in some a static scope to work properly. This is related to #13215.

File: compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala [hunk 1]
```diff
@@ -49,7 +49,7 @@ trait QuotesAndSplices {
       report.error(em"Quotes require stable Quotes, but found non stable $qctx", qctx.srcPos)
 
     if ctx.mode.is(Mode.Pattern) then
-      typedQuotePattern(tree, pt, qctx).withSpan(tree.span)
+      makeInlineable(typedQuotePattern(tree, pt, qctx).withSpan(tree.span))
```
Comment (jchyb) [inline compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala:52]:
```suggestion
      PrepareInlineable.makeInlineable(typedQuotePattern(tree, pt, qctx).withSpan(tree.span))
```
No real idea why but ignoring the Context switch from makeInlinleable (and instead using PrepareInlineable.makeInlineable directly) seems to fix both the dottytags and quill regressions minimalisations

**Comment by ckipp01** [comment]
Is this still being worked on, or are you waiting for another review @nicolasstucki? Just wanting to know if I should mark this as a draft or not.

**Comment by nicolasstucki** [comment]
We need #16992 to fix this issue

**Comment by WojciechMazur** [comment]
What's the state of this PR? Can it be restored with added `@publicInBinary` or we're waiting until it leaves experimental stage?

**Comment by nicolasstucki** [comment]
> What's the state of this PR? Can it be restored with added `@publicInBinary` or we're waiting until it leaves experimental stage?

Not sure, I will need to reinvestagate the current interaction of `@publicInBinary` and this fix.
