### PR TITLE
update `StringBuilder.toString` to have an empty parameter list

### LINKED ISSUE #19616: `Map.+=` not a member of `Map[String, String]` (using scala2-library-tasty)
## Compiler version

3.4.0-RC2

## Minimized code

```Scala
// Test.scala

def test: Unit =
  val sb = new StringBuilder
  var key = ""
  var map = Map.empty[String, String]
  map += key -> sb.toString()
```

```
sbt> set ThisBuild/Build.scala2Library := Build.Scala2LibraryCCTasty
sbt> scala3-bootstrapped/scalac Test.scala
```

## Output

```
-- [E008] Not Found Error: Test.scala:5:6 ------------------------------------
5 |  map += key -> sb.toString()
  |  ^^^^^^
  |value += is not a member of Map[String, String] - did you mean Map[String, String].!=? or perhaps Map[String, String].++ or Map[String, String].++ or Map[String, String].==?
```

## Expectation

Should compile as it does when we use the Scala 2 compiled library.

### PR DESCRIPTION
**Pull request by hamzaremmal**
This change is both source compatible and binary compatible. This might only break macros but they should be able to call `ensureApplied` now in `3.8.0` (#24160).

This used to be working in `3.7.4`.

Closes #19616

### CODE REVIEW

**Comment by hamzaremmal** [comment]
Note that this still doesn't solve the root issue but rather closes that very specific issue.

**Comment by hamzaremmal** [comment]
Closed in favor of the more general PR (#24461)
