### ISSUE TITLE
Regression since 3.0.0-M3: Issue with inlining in transparent macros

### ISSUE THREAD

**Issue by jorge-vasquez-2301** [lampepfl/dotty#12368]
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
object TransparentMacro:
    transparent inline def apply(inline n: Int): Any = ${applyImpl('n)}
    
    def applyImpl(n: Expr[Int])(using Quotes): Expr[Any] = if n.valueOrError > 0 then n else Expr("negative")

// In other file
object Test extends App:
   inline def x = -5
   println(TransparentMacro(x))
```

## Output

Compilation error:

```scala
|Expected a known value. 
[error]    |
[error]    |The value of: com.example.Test.x
[error]    |could not be extracted using scala.quoted.FromExpr$PrimitiveFromExpr@4eae616
[error]    | This location contains code that was inlined from Test.scala:23
```

## Expectation

The above code compiles in 3.0.0-M3. It should also compile in 3.0.0-RC3.

**Comment by liufengyun** [comment]
I think the following changes will make it work:

```diff
- inline def x = -5
+ inline val x = -5
```

@nicolasstucki : is it an intentional change to reject `def x` after the support for `inline val`?

**Comment by jorge-vasquez-2301** [comment]
Yeah, in fact it works with `inline val x = -5`, however it seems using `inline val` to store the result of calling other macro won't work. I've tried that in the actual code I'm implementing,  but I get a similar error to the one in the PR description (In `3.0.0-M3` I got this error: `inline value must have a literal constant type`)

**Comment by jorge-vasquez-2301** [comment]
And also, `inline def x = -5` works if I define `Transparentmacro.apply` just as `inline def` instead of `transparent inline def`

**Comment by liufengyun** [comment]
> And also, `inline def x = -5` works if I define `TransparentMacro.apply` just as `inline def` instead of `transparent inline def`

That explains it: `transparent inline` are expanded in an earlier phase. Thus at the time when expanding `apply`, `x` is not yet inlined. If you add `transparent` to `inline def x = -5`, it may work as well.

**Comment by jorge-vasquez-2301** [comment]
Ahhh, wasn't aware of that, and yeah, it works with `transparent inline def x = -5`. Well, thanks a lot for your help!
