### ISSUE TITLE
Could not infer type 

### ISSUE THREAD

**Issue by biuld** [lampepfl/dotty#16446]
## Compiler version
3.2.1

## Minimized code
```Scala
trait Functor[F[_]]:
  extension [A](fa: F[A]) def map[B](f: A => B): F[B]

trait Applicative[F[_]] extends Functor[F]:
  def pure[A](a: A): F[A]
  extension [A](fa: F[A]) def ap[B](fab: F[A => B]): F[B]

trait Monad[F[_]] extends Applicative[F]:
  extension [A](fa: F[A]) def bind[B](f: A => F[B]): F[B]

enum Option[+T]:
  case None
  case Some(x: T)

given Monad[Option] with
  override def pure[A](a: A): Option[A] = Option.Some(a)
  extension [A](fa: Option[A])
    override def map[B](f: A => B): Option[B] = fa match
      case Option.None    => Option.None
      case Option.Some(x) => Option.Some(f(x))

    override def ap[B](fab: Option[A => B]): Option[B] = fa match
      case Option.None    => Option.None
      case Option.Some(x) => fab.map(f => f(x))

    override def bind[B](f: A => Option[B]): Option[B] = fa match
      case Option.None    => Option.None
      case Option.Some(x) => f(x)

def test()(using optionMonad: Monad[Option]) =
  optionMonad
    .pure(1)
    .map(a => a * 2)
    .ap(optionMonad.pure(_ * 2))
    .bind(a => optionMonad.pure(a * 2))

@main def run = println(test())
```

## Output

```scala
Compiling project (Scala 3.2.1, JVM)
[error] ./Fun.scala:39:33: value * is not a member of Any, but could be made available as an extension method.
[error] 
[error] One of the following imports might make progress towards fixing the problem:
[error] 
[error]   import math.Fractional.Implicits.infixFractionalOps
[error]   import math.Integral.Implicits.infixIntegralOps
[error]   import math.Numeric.Implicits.infixNumericOps
[error] 
[error]     .bind(a => optionMonad.pure(a * 2))
[error]                                 ^^^
Error compiling project (Scala 3.2.1, JVM)
Compilation failed
```

## Expectation
I don't know whether this is really a bug or if I missed something at start.

**Comment by SethTisue** [comment]
I'm not able to reproduce the error. The code runs and prints `Some(8)`. It works in the Scala 3.2.1 REPL, and it works with `scala-cli -S 3.2.1 S.scala`, too.

**Comment by biuld** [comment]
@SethTisue 
Did you inline `optionMonad.pure(_ * 2)` like I said?
<img width="1284" alt="截屏2022-12-01 09 27 36" src="https://user-images.githubusercontent.com/36144654/204943820-fd9fffcc-6b9b-41d7-bc52-0ce946ae18ca.png">

**Comment by SethTisue** [comment]
> Did you inline optionMonad.pure(_ * 2) like I said?

No. We expect a bug report to include the actual code that didn't work — it's really better if we don't have to follow ambiguous verbal instructions in order to try this out for ourselves.

Screen shots don't make for good bug reports, either — please provide the failing code directly, so we can copy and paste it into our own environments.

**Comment by SethTisue** [comment]
Okay, the next step here is that the code you've provided is nowhere near minimized.

Here's something somewhat closer to minimal:

```scala
trait Monad[F[_]]:
  extension [A](fa: F[A]) def bind[B](f: A => F[B]): F[B]
  extension [A](fa: F[A]) def ap[B](fab: F[A => B]): F[B]

given Monad[Option] with
  extension [A](fa: Option[A])
    override def ap[B](fab: Option[A => B]): Option[B] = ???
    override def bind[B](f: A => Option[B]): Option[B] = ???

def test()(using optionMonad: Monad[Option]) =
  Some(1)
    .ap(Some(_ * 2))
    .bind(a => Some(a * 2))
```

but this is almost certainly still considerably more code than is actually necessary to demonstrate the problem you're experiencing. Are you able to minimize it any further and still get the error?

Reducing the problem to the bare minimum of code is part of what distinguishes asking a question (welcome on https://users.scala-lang.org) from reporting a bug (which is what this bug tracker is for).

Are `given` and `using` really necessary here, or is the problem reproducible without involving givens?

Is `extension` really necessary here, or is the problem reproducible with normal methods and functions?

And so on...

**Comment by biuld** [comment]
I tried again:
```Scala
enum Option[+T]:
  case None
  case Some(x: T)

extension [A](fa: Option[A])
  def ap[B](fab: Option[A => B]): Option[B] = fa match
    case Option.None => Option.None
    case Option.Some(x) =>
      fab match
        case Option.None    => Option.None
        case Option.Some(f) => Option.Some(f(x))

  def bind[B](f: A => Option[B]): Option[B] = fa match
    case Option.None    => Option.None
    case Option.Some(x) => f(x)

def test() =
  Option.Some(2)
    .ap(Option.Some(_ * 2))
    .bind(a => Option.Some(a * 2))

@main def run = println(test())
```
and same error here
```
Compiling project (Scala 3.2.1, JVM)
[error] ./Mini.scala:22:28: value * is not a member of Any, but could be made available as an extension method.
[error] 
[error] One of the following imports might make progress towards fixing the problem:
[error] 
[error]   import math.Fractional.Implicits.infixFractionalOps
[error]   import math.Integral.Implicits.infixIntegralOps
[error]   import math.Numeric.Implicits.infixNumericOps
[error] 
[error]     .bind(a => Option.Some(a * 2))
[error]                            ^^^
Error compiling project (Scala 3.2.1, JVM)
Compilation failed
```
It seems the compiler cannot infer for an extension method without explicit type hints. This below compiles correctly. I guess this hint is necessary and I would close this issue.
```
def test() = 
  Option.Some(2)
    .ap[Int](Option.Some(_ * 2))
    .bind(a => Option.Some(a * 2))
```
In the end, thanks for your patience and I apologize for recklessly opening an issue.

**Comment by SethTisue** [comment]
Note that the problem is not specific to extension methods. Here is a further minimization:

```scala
case class Option[A](x: A):
  def ap[B](fab: Option[A => B]): Option[B] = ???
def test() =
  val x = Option(2).ap(Option(_ * 2))
  x: Option[Int]
```

The error message "Found:    (x : Option[Any])" shows that the compiler is inferring `Any` when you wanted it to infer `Int`.

It isn't obvious to me whether type inference could be improved so that `Int` is inferred here.

**Comment by SethTisue** [comment]
Scala 2 refuses to infer the type at all:

```
error: missing parameter type for expanded function ((<x$1: error>) => x$1.$times(2))
```

The Scala 2 behavior is arguably preferable, as it's usually unwanted for `Any` ever to be inferred.
