### PR TITLE
Reimplement support for type aliases in SAM types

### LINKED ISSUE #18315: Output type mismatch in SAM
## Compiler version

3.4.0-RC1-bin-20230729-a73316a-NIGHTLY - failing, current nightly
3.3.2-RC1-bin-20230715-4851278-NIGHTLY - first bad release (first bad commit: 18f90d9701)
3.3.2-RC1-bin-20230714-04eae14-NIGHTLY - last good release

## Minimized code

```scala
trait Zippable[-A, -B] {
  type Out
  def zip(left: A, right: B): Out
}

object Zippable extends ZippableLowPrio:
  given append[A <: Tuple, B]: (Zippable[A, B] { type Out = Tuple.Append[A, B] }) =
    (left, right) => left :* right

trait ZippableLowPrio:
  given pair[A, B]: (Zippable[A, B] { type Out = (A, B) }) =
    (left, right) => (left, right)

def zip[A, B](a: A, b: B)(using z: Zippable[A, B]) = z.zip(a, b)

object Test:
  val x1: (Int, Int)           = zip(1, 2)
  val x2: (Int, Int, Int)      = zip((1, 2), 3)
  val x3: (Int, Int, Int, Int) = zip((1, 2, 3), 4)
```

## Output

```scala
-- [E008] Not Found Error: Zippable.scala:8:26 
8 |    (left, right) => left :* right
  |                     ^^^^^^^
  |                     value :* is not a member of A
-- [E007] Type Mismatch Error: Zippable.scala:12:21 
12 |    (left, right) => (left, right)
   |                     ^^^^^^^^^^^^^
   |                     Found:    (A, B)
   |                     Required: Zippable.this.Out
   |
   | longer explanation available when compiling with `-explain`
```

With `-explain` enabled:

```scala
[error] Zippable.scala:8:22
[error] value :* is not a member of A
[error]     (left, right) => left :* right
[error]                      ^^^^^^^
[error] Zippable.scala:12:22
[error] Found:    (A, B)
[error] Required: Zippable.this.Out
[error] 
[error] Explanation
[error] ===========
[error] 
[error] Tree: Tuple2.apply[A, B](left, right)
[error] I tried to show that
[error]   (A, B)
[error] conforms to
[error]   Zippable.this.Out
[error] but the comparison trace ended with `false`:
[error] 
[error]   ==> (A, B)  <:  Zippable.this.Out
[error]   <== (A, B)  <:  Zippable.this.Out = false
[error] 
[error] The tests were made under the empty constraint
[error]     (left, right) => (left, right)
[error]                      ^^^^^^^^^^^^^
```

## Expectation

The code should compile successfully

### PR DESCRIPTION
**Pull request by smarter**
This was dropped in #18201 which restricted SAM types to valid parent types, but it turns out that there is code in the wild that relies on refinements being allowed here.

To support this properly, we had to enhance ExpandSAMs to move refinements into type members to pass Ycheck (previous Scala 3 releases would accept the code in tests/run/i18315.scala but fail Ycheck).

Fixes #18315.

This should be backported to any branch where #18201 is backported.

### CODE REVIEW

**Comment by dwijnand** [comment]
Missing the test case?

**Comment by smarter** [comment]
oops yes

File: tests/run/i18315.scala [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+  def apply(x: T): T
+
+trait Sam2:
+  var x: Int = 1 // To force anonymous class generation
+  type T
+  def apply(x: T): T
+
+object Test:
+  def main(args: Array[String]): Unit =
+    val s1: Sam1 { type T = String } = x => x.trim
```
[the remark this answers is not in the document]
Comment (sjrd) [reply tests/run/i18315.scala:12]: We should definitely not make *more* things work in this space. What this PR "fixes" is already off-spec, because it is not legal to put a refinement type in an `extends` clause. It happened to work in 3.3.0 by accident, and so we're preserving the status quo in the name of backward compatibility within a patch series. But we should in fact make it an error in 3.4.x.

[the remark this answers is not in the document]
Comment (smarter) [reply tests/run/i18315.scala:12]: Yeah, I wouldn't want to add more than this and definitely not in a PR that fixes a regression
