### ISSUE TITLE
define a alias of annotation

### ISSUE THREAD

**Issue by cjdxhjj** [lampepfl/dotty#18802]
## Compiler version

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

```Scala
package com.nxin.product.domain

import org.axonframework.modelling.command.TargetAggregateIdentifier
import scala.annotation.meta.getter

type JLong = java.lang.Long
type JList[T] = java.util.List[T]
type JInt = java.lang.Integer
type JBool = java.lang.Boolean
type JMap[K, V] = java.util.Map[K, V]

type aggregateId = TargetAggregateIdentifier @getter
```

## Output
[Error] C:/Users/petzold/IdeaProjects/product-center/product-center-domain/src/main/scala/com/nxin/product/domain/PreDef.scala:12:20: Cyclic reference involving val <import>
[Error] C:/Users/petzold/IdeaProjects/product-center/product-center-domain/src/main/scala/com/nxin/product/domain/PreDef.scala:3:12: value axonframework is not a member of com.nxin.product.domain.org
```scala
// TODO add output here
```

## Expectation

then i change my code to
```scala
package com.nxin.product.domain

import scala.annotation.meta.getter

type JLong = java.lang.Long
type JList[T] = java.util.List[T]
type JInt = java.lang.Integer
type JBool = java.lang.Boolean
type JMap[K, V] = java.util.Map[K, V]

type aggregateId = org.axonframework.modelling.command.TargetAggregateIdentifier @getter
```
and use it 
![image](https://github.com/lampepfl/dotty/assets/5616997/aca53855-8f08-48c5-a2e1-f72a3c84ec4c)

it report another error
![image](https://github.com/lampepfl/dotty/assets/5616997/0179b41a-3445-4827-8208-e85a1c30f6de)

**Comment by sjrd** [comment]
Is this something that worked in an earlier version? It seems to me that the latter error is valid: an annotated type of the form `C @annot` does not have a constructor, and therefore cannot be used as an annotation itself. Only `C` has a constructor.

**Comment by cjdxhjj** [comment]
the earlier version is scala 2.13, i'm trying to upgrade to scala 3.3.1 the error appear

**Comment by cjdxhjj** [comment]
the first version report the error 'Cyclic reference involving val' and 'value axonframework is not a member of com.nxin.product.domain.org', why?

**Comment by cjdxhjj** [comment]
the TargetAggregateIdentifier definition is
![image](https://github.com/lampepfl/dotty/assets/5616997/a2f0e5d0-a1df-4936-94f3-06c9409dc946)

**Comment by cjdxhjj** [comment]
the command id must decorate the TargetAggregateIdentifier annotation at field
![image](https://github.com/lampepfl/dotty/assets/5616997/0f2d3715-cdd2-4efd-b0be-0e92f9f6ccb0)
![image](https://github.com/lampepfl/dotty/assets/5616997/bbaea478-d440-4271-9cea-8c8da9954b76)

that work on scala 2.13
