### ISSUE TITLE
Right-bias during implicit resolution of instances associated with "injected" polymorphic types. 

### ISSUE THREAD

**Issue by Baccata** [lampepfl/dotty#14176]
It is hard to provide a proper description in English, without knowing the compiler lingo much, so you'll find a minified reproduction of the problem below : 

## Compiler version

3.1.0

## Minimized code

```scala
trait Functor[F[_]] {
  def map[A, B](fa: F[A])(f: A => B): F[B]
}

object Functor {

  implicit class Syntax[F[_], A](fa: F[A]) {
    def map[B](f: A => B)(implicit F: Functor[F]): F[B] = F.map(fa)(f)
  }

}

trait Polymorphic[F[_, _]] {
  def call(): F[Int, Int]
}

object Program {

  import Functor._

  trait Inject[F[_]] {
    type Left[A, B] = F[A]
    type Right[A, B] = F[B]
  }

  type PolyRight[F[_]] = Polymorphic[Inject[F]#Right]

  // Succeeds
  def program[F[_]: Functor](poly: PolyRight[F]) =
    poly.call().map(_ + 1)

  type PolyLeft[F[_]] = Polymorphic[Inject[F]#Left]

  // Succeeds on Scala 2, Fails on Scala 3 with:
  //
  // no implicit argument of type Functor[([B] =>> Program.Inject[F]#Left[Int, B])] was found for parameter F of method map in class Syntax
  //
  //  where:    F is a type in method program2 with bounds <: [_] =>> Any
  //
  def program2[F[_]: Functor](poly: PolyLeft[F]) =
    poly.call().map(_ + 1)

  // Succeeds
  def program3[F[_]: Functor](poly: PolyLeft[F]) =
    (poly.call(): F[Int]).map(_ + 1)

}

```

## Output

```
Compiling project (Scala 3.1.0, JVM)
[error] ./foo.scala:41:21: value + is not a member of Any, but could be made available as an extension method.
[error] 
[error] One of the following imports might make progress towards fixing the problem:
[error] 
[error]   import math.Fractional.Implicits.infixFractionalOps
[error]   import math.Integral.Implicits.infixIntegralOps
[error]   import math.Numeric.Implicits.infixNumericOps
[error] 
[error]     poly.call().map(_ + 1)
[error]                     ^^^
[error] ./foo.scala:41:27: no implicit argument of type Functor[([B] =>> Program.Inject[F]#Left[Int, B])] was found for parameter F of method map in class Syntax
[error] 
[error] where:    F is a type in method program2 with bounds <: [_] =>> Any
[error] .
[error] I found:
[error] 
[error]     evidence$2
[error] 
[error] But parameter evidence$2 does not match type Functor[([B] =>> Program.Inject[F]#Left[Int, B])].
[error]     poly.call().map(_ + 1)
[error]                           ^
Error compiling project (Scala 3.1.0, JVM)
```

## Expectation

I'd expect the code to compile in Scala 3.1.0.

I am aware that using Scala 3's type lambdas work : 

```scala 
  // Succeeds
  type PolyLeftLambda[F[_]] = Polymorphic[[A, B] =>> F[A]]

  def program4[F[_]: Functor](poly: PolyLeftLambda[F]) =
    poly.call().map(_ + 1)
```

but I'm trying to produce code that would cross-compile between Scala 2 and Scala 3. 

Kind regards

**Comment by joroKr21** [comment]
It might work more or less by accident in Scala 2 because the type projection `Inject[F]#Left` forces the type to be dealiased resulting in `F[Int]`. But in general type unification **should not** dealias types - instead partial unification makes a hole from the rightmost type argument to unify `Left[Int, Int]` with `F[A]`.

To see the same behaviour in Scala 2 try adding one more layer of aliasing:
```scala
trait Polymorphic[F[_, _]] {
  type G[A, B] = F[A, B]
  def call(): G[Int, Int]
}
```

And you will see an error:
```scala
          poly.call().map(_ + 1)
                          ^
On line 42: error: could not find implicit value for parameter F: Functor[[B]poly.G[Int,B]]
```

It's not really specified when exactly the compiler resolves type aliases but in general the less often the better.
So I would say this is not a bug.

**Comment by Baccata** [comment]
Can you elaborate on why unification should not dealias types ? I don't mind if the behaviour is considered not a bug, but I'd like to understand the fundamental reason behind it making my life difficult 😅

**Comment by smarter** [comment]
> Can you elaborate on why unification should not dealias types ?

See https://github.com/lampepfl/dotty/commit/fb7bc51eb85f46f537a07b0305622a86057e20ad

Also see https://github.com/lampepfl/dotty/blob/c94b333fdd31e81d7dab0ac2cf21c72b760fbc7e/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L912-L962 for the exact rules governing partial unification.

**Comment by Baccata** [comment]
Thank you, Guillaume. I think I understand the rationale. 

Also I think I've figured a suitable replacement for my usecase: rather than Injecting the F into a higher-kinded shape, I can project the interface in a lower kinded one as such, and have type inference work as I expect. 

``` 
  type ClassicTF[Alg[_[_, _]], F[_]] = Alg[[A, B] =>> F[A]]
  type PolyLeft[F[_]] = ClassicTF[Polymorphic, F]
```

Although `ClassicTF` will not cross-compile, I have control over it (or rather, its conceptual equivalent) in my codebase. I'm more interested about the ability for `PolyLeft` alias to cross-compile, as this happens in user-land, in a code-generation pipeline.  

With all this in mind, I'm happy for this issue to be closed.
