### PR TITLE
Remove linearization requirement for override ref checks from java classes

### LINKED ISSUE #18654: "has weaker access privileges; it should be public" error when compiling against jOOQ
## Compiler version

Scala 3.3.1

## Minimized code

See: https://github.com/tpunder/scala3_jooq_bug_access_privileges

The only Scala source file is:

```scala
package com.example

import org.jooq.impl.AbstractRoutine

// Works in Scala 2.12 and 2.13 but is broken in Scala 3
class MyRoutineScala extends AbstractRoutine[String] {

}
```

The equivalent Java source compiles file:

```java
package com.example;

import org.jooq.impl.AbstractRoutine;

// Works fine
class MyRoutineJava extends AbstractRoutine<String> {

}
```

## Output

```
[info] Setting Scala version to 3.3.1 on 1 projects.
[info] Reapplying settings...
[info] set current project to scala3_jooq_bug_access_privileges (in build file:/Users/tim/code/personal/scala3_jooq_bug_access_privileges/)
[info] compiling 1 Scala source and 6 Java sources to /Users/tim/code/personal/scala3_jooq_bug_access_privileges/target/scala-3.3.1/classes ...
[error] -- [E164] Declaration Error: /Users/tim/code/personal/scala3_jooq_bug_access_privileges/src/main/scala/com/example/MyRoutineScala.scala:6:6
[error] 6 |class MyRoutineScala extends AbstractRoutine[String] {
[error]   |      ^
[error]   |error overriding method configuration in trait Attachable of type (): org.jooq.Configuration;
[error]   |  method configuration in class AbstractQueryPart of type (): org.jooq.Configuration has weaker access privileges; it should be public
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed Oct 5, 2023, 2:11:58 PM
```

## Expectation

The code works fine under Scala 2.12 and 2.13:

```
[info] Setting Scala version to 2.12.18 on 1 projects.
[info] Reapplying settings...
[info] set current project to scala3_jooq_bug_access_privileges (in build file:/Users/tim/code/personal/scala3_jooq_bug_access_privileges/)
[info] compiling 1 Scala source to /Users/tim/code/personal/scala3_jooq_bug_access_privileges/target/scala-2.12/classes ...
[success] Total time: 1 s, completed Oct 5, 2023, 2:11:55 PM
[info] Setting Scala version to 2.13.10 on 1 projects.
[info] Reapplying settings...
[info] set current project to scala3_jooq_bug_access_privileges (in build file:/Users/tim/code/personal/scala3_jooq_bug_access_privileges/)
[info] compiling 1 Scala source to /Users/tim/code/personal/scala3_jooq_bug_access_privileges/target/scala-2.13/classes ...
[success] Total time: 1 s, completed Oct 5, 2023, 2:11:56 PM
```

There is a similar jOOQ related bug here: https://github.com/lampepfl/dotty/issues/16844

### LINKED ISSUE #18764: scalac 3 can't compile code that worked with scalac 2 and Java, when extending Java class with lots of covariant overrides
## Compiler version

3.3.1

## Minimized code

The bug arises when using jOOQ generated code that compiles against the jOOQ runtime library. Download https://repo1.maven.org/maven2/org/jooq/jooq/3.18.7/jooq-3.18.7.jar, and then compile the following minimal reproducer:

```scala
import org.jooq.impl.TableRecordImpl

class TRecord extends TableRecordImpl[TRecord](null) {}
```

Compile with:

```
scalac -classpath jooq-3.18.7.jar Test.scala -explain
```

## Output

```
-- [E164] Declaration Error: Test.scala:3:6 ------------------------------------
3 |class TRecord extends TableRecordImpl[TRecord](null) {}
  |      ^
  |error overriding method with in trait QualifiedRecord of type [T](x$0: org.jooq.Field[T], x$1: T): TRecord;
  |  method with² in class AbstractRecord of type [T](x$0: org.jooq.Field[T²], x$1: T²): org.jooq.Record has incompatible type;
  |other members with override errors are:: method original
  |
  |where:    T     is a type variable with constraint <: Object
  |          T²    is a type variable with constraint <: Object
  |          with  is a method in trait QualifiedRecord
  |          with² is a method in class AbstractRecord
  |-----------------------------------------------------------------------------
  | Explanation (enabled by `-explain`)
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  | I tried to show that
  |   [T](x$0: org.jooq.Field[T], x$1: T): org.jooq.Record
  | conforms to
  |   [T](x$0: org.jooq.Field[T], x$1: T): TRecord
  | but the comparison trace ended with `false`:
  |
  |   ==> [T](x$0: org.jooq.Field[T], x$1: T): org.jooq.Record  <:  [T](x$0: org.jooq.Field[T], x$1: T): TRecord
  |     ==> type bounds []  <:  type bounds [] in frozen constraint
  |     <== type bounds []  <:  type bounds [] in frozen constraint = true
  |     ==> (x$0: org.jooq.Field[T], x$1: T): org.jooq.Record  <:  (x$0: org.jooq.Field[T], x$1: T): TRecord
  |       ==> org.jooq.Record  <:  TRecord
  |       <== org.jooq.Record  <:  TRecord = false
  |     <== (x$0: org.jooq.Field[T], x$1: T): org.jooq.Record  <:  (x$0: org.jooq.Field[T], x$1: T): TRecord = false
  |   <== [T](x$0: org.jooq.Field[T], x$1: T): org.jooq.Record  <:  [T](x$0: org.jooq.Field[T], x$1: T): TRecord = false
  |
  | The tests were made under the empty constraint
   -----------------------------------------------------------------------------
1 error found
```

## Expectation

The code should compile just fine as it did with 2.13.12, for example, or in Scala. I think the lookup algorithm trips somewhere as it seems to find only the override `[T](x$0: org.jooq.Field[T], x$1: T): org.jooq.Record`, which is overridden covariantly to produce compatible versions.

### LINKED ISSUE #19007: error overriding method with different access levels in inheritors
## Compiler version
3.3.1

## Minimized code
**3 Java files**
```java
public interface RunConfiguration extends Cloneable {
  RunConfiguration clone();
}
```
```java
public abstract class RunConfigurationBase<T> extends UserDataHolderBase implements RunConfiguration {
    @Override
    public RunConfiguration clone() {
        return null;
    }
}
```
```java
import java.util.concurrent.atomic.AtomicReference;

public class UserDataHolderBase extends AtomicReference<String> {
    @Override
    protected Object clone() {
        return null;
    }
}

```

**Main Scala File** 
```scala
class MyRunConfigurationScala extends RunConfigurationBase
```

## Output
Compile the code.
Observe compilation error:
```
.../src/main/scala/MyRunConfigurationScala.scala
error overriding method clone in trait RunConfiguration of type (): RunConfiguration;
  method clone² in class UserDataHolderBase of type (): Object has weaker access privileges; it should be public

where:    clone  is a method in trait RunConfiguration
          clone² is a method in class UserDataHolderBase

class MyRunConfigurationScala extends RunConfigurationBase
```

## Expectation
The code compiles fine.
Note that it compiles with Scala 2 compiler.
Also Java compiler compiles fine a similar code:
`MyRunConfigurationJava.java`
```java
public class MyRunConfigurationJava extends RunConfigurationBase {
}
```

Note that this is a minimised example from the Scala Plugin project.
I tried to extract another module to Scala 3 and got this error.
Java classes are from library (IntelliJ SDK).

### PR DESCRIPTION
**Pull request by EugeneFlesselle**
When checking overriding/overriden pairs references, we can exclude those handled by the parent class, which requires them to be in linearization order. If the parent is java class however, this ordering should not be checked as linearization does not apply to them.

Closes #18654, closes #19007, and closes #18764

In particular, it fixes both:
- https://github.com/tpunder/scala3_jooq_bug_access_privileges
- https://github.com/tpunder/scala3_jooq_bug_overriding

But it does not fix https://scastie.scala-lang.org/3ioAIaRaQJ282KS69KugxA or any of its minimisations which have an external dependency.

@tpunder

### CODE REVIEW

**Review by odersky — APPROVED** [review]
LGTM!
