### ISSUE TITLE
A Question about Macro Changes from M3 to RC1

### ISSUE THREAD

**Issue by ShapelessCat** [lampepfl/dotty#11554]
## Compiler version

Scala 3.0.0-RC1

## Question

I tried to update the Scala 3 version used in [lampepfl/dotty-macro-examples](https://github.com/lampepfl/dotty-macro-examples) to 3.0.0-RC1. The update process is simple for most of the code, except the example `macroTypeclassDerivation`.

I first updated `macroTypeclassDerivation` to fit 3.0.0-M2 and 3.0.0-M3, which is simple. At first glance, it seems I don't need to change the code when I further update the version to 3.0.0-RC1. However, the same code doesn't work in 3.0.0-RC1. It seems the _given instances_ derivation failed.

Is this an expected behavior? or a bug?

## Minimized example

[The master branch of my fork](https://github.com/ShapelessCat/dotty-macro-examples/tree/master) is using 3.0.0-M3.
In [The RC1 branch of my fork](https://github.com/ShapelessCat/dotty-macro-examples/tree/upgrade-to-RC1) you can see the not workable `macroTypeclassDerivation`, which is the same as that in the master branch.

## Output

Checkout the **upgrade-to-RC1** branch of my fork mentioned above, run `mill macroTypeclassDerivation.run`, and you can see the output:

```test
[27/38] macroTypeclassDerivation.compile 
[info] compiling 3 Scala sources to /home/shapeless-cat/IdeaProjects/dotty-macro-examples/out/macroTypeclassDerivation/compile/dest/classes ...
[error] -- Error: /home/shapeless-cat/IdeaProjects/dotty-macro-examples/macroTypeclassDerivation/src/Test.scala:28:13 
[error] 28 |  display(p1)
[error]    |             ^
[error]    |Exception occurred while executing macro expansion.
[error]    |scala.MatchError: SearchFailureIdent(/* missing */) (of class dotty.tools.dotc.ast.Trees$SearchFailureIdent)
[error]    |	at dummy.macro$package$.lookupShowFor(macro.scala:72)
[error]    |	at dummy.macro$package$.$anonfun$1(macro.scala:25)
[error]    |	at scala.collection.immutable.List.map(List.scala:246)
[error]    |	at dummy.macro$package$.showBody$1(macro.scala:26)
[error]    |	at dummy.macro$package$.deriveTraitShow$$anonfun$4(macro.scala:32)
[error]    |	at dummy.macro$package$.deriveTraitShow$$anonfun$adapted$2(macro.scala:32)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:81)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1355)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1394)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1422)
[error]    |	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1422)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1420)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1401)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1398)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1422)
[error]    |	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1422)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1420)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1335)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:120)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:61)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl.unpickleExpr(QuotesImpl.scala:2879)
[error]    |	at dummy.macro$package$.deriveTraitShow(macro.scala:32)
[error]    |	at dummy.macro$package$.deriveShowImpl(macro.scala:11)
[error]    |
[error]    | This location contains code that was inlined from Test.scala:28
[error]    | This location contains code that was inlined from Test.scala:16
[error] -- Error: /home/shapeless-cat/IdeaProjects/dotty-macro-examples/macroTypeclassDerivation/src/Test.scala:29:13 
[error] 29 |  display(p2)
[error]    |             ^
[error]    |Exception occurred while executing macro expansion.
[error]    |scala.MatchError: SearchFailureIdent(/* missing */) (of class dotty.tools.dotc.ast.Trees$SearchFailureIdent)
[error]    |	at dummy.macro$package$.lookupShowFor(macro.scala:72)
[error]    |	at dummy.macro$package$.$anonfun$1(macro.scala:25)
[error]    |	at scala.collection.immutable.List.map(List.scala:246)
[error]    |	at dummy.macro$package$.showBody$1(macro.scala:26)
[error]    |	at dummy.macro$package$.deriveTraitShow$$anonfun$4(macro.scala:32)
[error]    |	at dummy.macro$package$.deriveTraitShow$$anonfun$adapted$2(macro.scala:32)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:81)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1355)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1394)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1422)
[error]    |	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1422)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1420)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1401)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1398)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1422)
[error]    |	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1422)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1420)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1335)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:120)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:61)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl.unpickleExpr(QuotesImpl.scala:2879)
[error]    |	at dummy.macro$package$.deriveTraitShow(macro.scala:32)
[error]    |	at dummy.macro$package$.deriveShowImpl(macro.scala:11)
[error]    |
[error]    | This location contains code that was inlined from Test.scala:29
[error]    | This location contains code that was inlined from Test.scala:16
[error] -- Error: /home/shapeless-cat/IdeaProjects/dotty-macro-examples/macroTypeclassDerivation/src/Test.scala:30:12 
[error] 30 |  display(c)
[error]    |            ^
[error]    |Exception occurred while executing macro expansion.
[error]    |scala.MatchError: SearchFailureIdent(/* missing */) (of class dotty.tools.dotc.ast.Trees$SearchFailureIdent)
[error]    |	at dummy.macro$package$.lookupShowFor(macro.scala:72)
[error]    |	at dummy.macro$package$.$anonfun$1(macro.scala:25)
[error]    |	at scala.collection.immutable.List.map(List.scala:246)
[error]    |	at dummy.macro$package$.showBody$1(macro.scala:26)
[error]    |	at dummy.macro$package$.deriveTraitShow$$anonfun$4(macro.scala:32)
[error]    |	at dummy.macro$package$.deriveTraitShow$$anonfun$adapted$2(macro.scala:32)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:81)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1355)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1394)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1422)
[error]    |	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1422)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1420)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1401)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1398)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1422)
[error]    |	at scala.collection.immutable.List.mapConserve(List.scala:472)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1422)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformStats(Trees.scala:1420)
[error]    |	at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1335)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:105)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:120)
[error]    |	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:61)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl.unpickleExpr(QuotesImpl.scala:2879)
[error]    |	at dummy.macro$package$.deriveTraitShow(macro.scala:32)
[error]    |	at dummy.macro$package$.deriveShowImpl(macro.scala:11)
[error]    |
[error]    | This location contains code that was inlined from Test.scala:30
[error]    | This location contains code that was inlined from Test.scala:16
[error] three errors found
[error] three errors found
1 targets failed
macroTypeclassDerivation.compile Compilation failed
```

**Comment by nicolasstucki** [comment]
That might be caused by #11557,  #11538 or #11479. All issues with implicit scopes not being added when expanding macros. Those issues are different manifestations of the same core bug. It would be good to see if the implicit is in one of the categories that we are fixing right now. Otherwise, we would need to minimize this issue.

**Comment by odersky** [comment]
@ShaneDelmore Can you try with latest nightly? That should have fixes for the issues @nicolasstucki mentioned.

**Comment by ShapelessCat** [comment]
@odersky I guess you tried to @ me, the creator of this issue, not ShaneDelmore.

@odersky @nicolasstucki I tried, and this bug was fixed since 3.0.0-RC2-bin-20210304-5fa55b1-NIGHTLY.

Thanks!
