### PR TITLE
Add top-level definitions to scope in TreeMapWithImplicits

### LINKED ISSUE #11479: summonInline can't deduce summon, passed  via type parameter  [Regression]
## Compiler version

3.0.0-RC1
Latest Dotty nightly build version: 3.0.0-RC2-bin-20210219-aa7c21e-NIGHTLY

## Minimized code

fixe X.scala:

```Scala
package x

import scala.concurrent.Future
import scala.quoted._
import scala.compiletime._

trait CpsMonad[F[_]]

given FutureCpsMonad:  CpsMonad[Future] with {}


class SLLoop[F[_]:CpsMonad]:

 inline def apply(inline pf: PartialFunction[Any,Boolean]): Unit =
    ${
      SLLoop.loopImpl[F]('pf, '{summonInline[CpsMonad[F]]})
    }


object SLLoop:

    def loopImpl[F[_]:Type](pf: Expr[PartialFunction[Any,Boolean]], m:Expr[CpsMonad[F]])(using Quotes): Expr[Unit] =
      println(s"loopImpl: ${pf}")
      '{ }
```

file Main.scala
```
package x

import scala.concurrent.Future

object Main:

  def main(args:Array[String]):Unit =
    SLLoop[Future].apply{
      case "AAA" => true
    }
```

## Output

```scala
Latest Dotty nightly build version: 3.0.0-RC2-bin-20210219-aa7c21e-NIGHTLY
[info] loading settings for project root from build.sbt ...
[info] set current project to test (in build file:/Users/rssh/tests/dotty/summon-inline/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 2 Scala sources to /Users/rssh/tests/dotty/summon-inline/target/scala-3.0.0-RC2/classes ...
[error] -- Error: /Users/rssh/tests/dotty/summon-inline/src/main/scala/x/Main.scala:8:24 
[error] 8 |    SLLoop[Future].apply{
[error]    |    ^
[error]    |    cannot reduce summonFrom with
[error]    |     patterns :  case t @ _:x.CpsMonad[concurrent.Future]
[error]    | This location contains code that was inlined from package.scala:144
[error]    | This location contains code that was inlined from X.scala:16
[error] 9 |      case "AAA" => true
[error] 10 |    }
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## Expectation

  Should compile.
(it works in 3.0.0-M3)

### PR DESCRIPTION
**Pull request by nicolasstucki**
Fixes #11479

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Reproduce current issues with 
```scala
sbt> testCompilation tests/pos/t3642
```
or 

```scala
sbt> testCompilation --from-tasty <test-name>
// were <test-name> is one of
// tests/run/inlineAddDeserializeLambda.scala
// tests/run/inline-param-semantics.scala
// tests/run/rescue.scala
// tests/run/erased-inline-vals.scala
// tests/run/tuple-ops.scala
// tests/run/toList.scala
// tests/run/enum-nat.scala
// tests/run/transparent-object.scala
// tests/run/i8530.scala
// tests/run/inline-override.scala
// tests/run/i8058.scala
// tests/run/i4496b.scala
// tests/run/tuples-empty.scala
// tests/run/i9473.scala
// tests/run/constValueTuple.scala
// tests/run/i10724.scala
// tests/run/i7110.scala
// tests/run/singleton-ops-flags.scala
// tests/run/i8530-b.scala
// tests/run/tuple-product.scala
// tests/run/typelevel-overrides.scala
// tests/run/transparent-foreach.scala
// tests/run/reduce-projections.scala
// tests/run/transparentProtected.scala
// tests/run/summonAll.scala
// tests/run/fragables-extension.scala
// tests/run/inline-override-num.scala
// tests/run/i2360.scala
// tests/run/i4523.scala
// tests/run/dead-code-elimination.scala
// tests/run/typeCheckErrors.scala
// tests/run/implicit-functors2.scala
// tests/pos/t3642
```

**Comment by nicolasstucki** [comment]
Replaced by #11591
