### PR TITLE
Improvements for implicit searches with top-level type variables

### LINKED ISSUE #13986: Scala 2 Regression: Upper bound of a higher-kinded type variable is not included into implicit search scope
## Compiler version
 
`3.1.2-RC1-bin-20211118-2b37257-NIGHTLY`

## Minimized code

Scastie: https://scastie.scala-lang.org/mBqRVwrfQpqZeLBUKzf8xQ

```scala
package example

sealed trait Xa[T]
sealed trait Mu[T] extends Xa[T]
object Xa {
  implicit def convertMu[X[x] <: Xa[x], A, B](implicit t: X[A]): X[B] = t.asInstanceOf[X[B]]
}
object Mu {
  implicit def mu: Mu[Int] = new Mu[Int]
}

object App extends App {
  def constrain(a: Mu[Long]): Unit = println(a)
  constrain(Xa.convertMu)
}
```

## Output

```scala
no implicit argument of type X[A] was found for parameter t of method convertMu in object Xa

where:    A is a type variable
          X is a type variable with constraint <: example.Mu


The following import might fix the problem:

  import example.Mu.mu
```

## Expectation

Expected to work, as in Scala 2: https://scastie.scala-lang.org/MesjnzXeRCSarfLr7HCGHA
This seems to affect only higher-kinded types, I could not reproduce it with a non-parameterized implicit with a roughly similar setup - https://scastie.scala-lang.org/XW8Yy4CXQmSXgslU0Wktew

* NOTE 1: Specifying _just_ the type `Mu` explicitly, e.g. using partial application below will get rid of the error:
  ```scala
  def convertMuPartial[X[x] <: Xa[x]]: [A, B] => X[A] ?=> () => X[B] = {
    [A, B] => (t: X[A]) ?=> () => Xa.convertMu[X, A, B](t)
  }
  constrain(convertMuPartial[Mu]())
  ```
  The implicit scope gets lost only when the searchable becomes a type parameter at some point in the search.

* NOTE 2: The searched-for type is determined correctly and applying the suggestion to `import example.Mu.mu` will get rid of the error. However, this import should not be required because Mu companion object should be included in implicit scope, brought in by constraint on X <: example.Mu.

In addition, varying the above setup slightly produces an `assertion failure` compiler crash: \<a new issue link will be added here shortly\>

This error currently blocks me from porting Izumi BIO to Scala 3, where a similar implicit is used https://github.com/7mind/izumi/blob/develop/fundamentals/fundamentals-bio/src/main/scala/izumi/functional/bio/Root.scala#L120

### LINKED ISSUE #15160: Type inference bug in Scala 3.1.2
I'm unsure if I'm reporting this issue in the right place.

## Compiler version

`3.1.2` — the issue does not happen in `3.0.x` or in `3.1.1`.

First bad commit db5956b36a7e62b77f4b3a9335ab1587e0e47e2c in #13886

## Minimized code

Noticed it while upgrading to 3.1.2 in [monix/newtypes](https://github.com/monix/newtypes):

```scala
trait Eq[A] {
  def eqv(a1: A, a2: A): Boolean
}

given stringEq: Eq[String] with {
  def eqv(a1: String, a2: String) = a1 == a2
}

abstract class Newtype[Src] {
  opaque type Type = Src

  protected final def derive[F[_]](using ev: F[Src]): F[Type] = ev
}

object Sample extends Newtype[String] {
  given eq: Eq[Type] = derive
}
```

## Output

```scala
[error] -- Error: .../Sample.scala:16:29
[error] 16 |  given eq: Eq[Type] = derive
[error]    |                             ^
[error]    |no implicit argument of type F[String] was found for parameter ev of method derive in class Newtype
[error]    |
[error]    |where:    F is a type variable with constraint <: Eq
[error] one error found
```

## Expectation

The code should compile just fine, as it does with `3.1.1`, `3.0.2`, or `2.13.x`.

### LINKED ISSUE #15670: Implicit value can no longer be accessed via implicit conversion
Community build regression for https://github.com/giiita/refuel (maintainer @giiita)
Based on [Open Community Build #1884](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/1884/)
Part of https://github.com/lampepfl/dotty/issues/15647 regressions tracker

## Compiler version

Works in 3.1.1
Fails in 3.1.2 and 3.1.3
Fails in 3.2.0-RC* and 3.2.1-RC1-bin-20220711-6efd92d-NIGHTLY

## Minimized code

```Scala
trait JsonRowEntry {
  def readAs[E](implicit c: Read[E]): Option[E] = ???
}
trait Read[T]
trait Codec[T] extends Read[T]
trait CodecTypeProjection[C[_]]
object JsonTransform  {
  given SetCodec[T, C[_]: CodecTypeProjection]: scala.Conversion[C[T], C[Set[T]]] = ???
  given SetCodecExp[T, C[_]: CodecTypeProjection](using codec: C[T]): C[Set[T]] = codec
  given Codec[String] = ???
  given CodecTypeProjection[Read] = ???
}

@main def Test() = {
  import JsonTransform.given
  val tree = new JsonRowEntry {}
  tree.readAs[Set[String]]
}
```

## Output

```scala
rror] ./test.scala:17:27: No given instance of type Read[Set[String]] was found for parameter c of method readAs in trait JsonRowEntry.
[error] I found:
[error] 
[error]     JsonTransform.SetCodecExp[String, C](
[error]       JsonTransform.given_CodecTypeProjection_Read
[error]     , /* missing */summon[C[String]])
[error] 
[error] But no implicit values were found that match type C[String].
[error]   tree.readAs[Set[String]]
[error]              
```

## Expectation
Should be able to find correct implicit value by usage of implicit conversion

### LINKED ISSUE #15820: Regression in implicit params lookup of recursive calls
Based on  [Open CB #2105](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/2105/) 

## Compiler version
Works in 3.1.1
Fails since 3.1.2
Fails in 3.2.0-RC3

## Minimized code

```Scala
sealed trait Domain[E]

final def splitBounds[E, D[X] <: Domain[X]](
    bounds: Seq[E],
  )( using domain: D[E]): Seq[E] =
      val newBounds: Seq[E] = ???
      splitBounds(newBounds) // does not compile
      splitBounds[E,D](newBounds) // does compile
```

## Output

```scala
[error] ./test.scala:7:29: no given instance of type D[E] was found for parameter domain of method splitBounds
[error] 
[error] where:    D is a type variable with constraint <: Domain
[error]       splitBounds(newBounds) // does not compile
[error]         
 ```

## Expectation
Should compile by resuing implicit Domain parameter

### LINKED ISSUE #15998: Implicit conversion not applied for the arguments of extension method
Regression found in [Open CB #4749](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/4749/) for [scala-tessella/ring-seq](https://github.com/scala-tessella/ring-seq)
Part of the Scala 3.2.1-RC1 regression tracker #15949 

Gathering bisect info might be problematic, due to another regression existing in 3.1.2 fixed in 3.1.3

## Compiler version
Fails in 3.1.3, 3.2.0, 3.2.1-RC1
Works in 3.1.1

## Minimized code

```Scala
import scala.collection.SeqOps

trait ComparingOps:
  extension[A, CC[B] <: SeqOps[B, CC, CC[B]]](ring: CC[A])
    def isRotationOf(that: CC[A]): Boolean = ???

object RingSeq extends ComparingOps 
import RingSeq.*

@main def Test = 
  RingSeq.isRotationOf("DAB") // error
  "ABCD".isRotationOf("DAB")  // error
  
  // workaround 
  RingSeq.isRotationOf[Char, IndexedSeq]("DAB")
  RingSeq.isRotationOf(wrapString("DAB"))
  wrapString("ABCD").isRotationOf("DAB")
```

## Output

```scala
ompiling project (Scala 3.2.2-RC1-bin-20220907-a503b7a-NIGHTLY, JVM)
[error] ./repo4/repro/test.scala:11:24: 
[error] Found:    ("DAB" : String)
[error] Required: CC[A]
[error] 
[error] where:    A  is a type variable
[error]           CC is a type variable with constraint <: [B] =>> collection.SeqOps[B, CC, CC[B]]
[error]   RingSeq.isRotationOf("DAB") // error
[error]                        ^^^^^
[error] ./repo4/repro/test.scala:12:3: value isRotationOf is not a member of String.
[error] An extension method was tried, but could not be fully constructed:
[error] 
[error]     RingSeq.isRotationOf[A, CC]("ABCD")    failed with
[error] 
[error]         Found:    ("ABCD" : String)
[error]         Required: CC[A]
[error]         
[error]         where:    A  is a type variable
[error]                   CC is a type variable with constraint <: [B] =>> collection.SeqOps[B, CC, CC[B]]
[error]         
[error]   "ABCD".isRotationOf("DAB")  // error
```

## Expectation
Should compile by applying implicit conversion

### PR DESCRIPTION
**Pull request by odersky**
Two improvements for implicit searches involving type variables.

 1. We now always add a comment when an implicit search is rejected due to the "too unspecific" criterion of #13886, commit
[Refine checking for underspecified implicit queries](https://github.com/lampepfl/dotty/pull/13886/commits/db5956b36a7e62b77f4b3a9335ab1587e0e47e2c).

   There have been quite a few regressions that hit that problem, so it is good to know immediately what
   the issue is. 

 2. There is now a better wildcard approximation of higher-kinded type applications. This makes several programs (including original #15998) compile, which were classified as not specific enough before.

Fixes #15998
Fixes #15820
Fixes #15670
Fixes #15160 
Fixes #13986

### CODE REVIEW

File: compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala [hunk 1]
```diff
@@ -822,17 +822,22 @@ object ProtoTypes {
...
       else tp.derivedSelect(wildApprox(tp.prefix, theMap, seen, internal))
     case tp @ AppliedType(tycon, args) =>
+      def wildArgs = args.mapConserve(arg => wildApprox(arg, theMap, seen, internal))
       wildApprox(tycon, theMap, seen, internal) match {
-        case _: WildcardType => WildcardType // this ensures we get a * type
-        case tycon1 => tp.derivedAppliedType(tycon1,
-          args.mapConserve(arg => wildApprox(arg, theMap, seen, internal)))
+        case WildcardType(TypeBounds(lo, hi)) if hi.typeParams.hasSameLengthAs(args) =>
+          val lo1 = if lo.typeParams.hasSameLengthAs(args) then lo.appliedTo(wildArgs) else lo
+          WildcardType(TypeBounds(lo1, hi.appliedTo(wildArgs)))
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/typer/ProtoTypes.scala:837]: To avoid computing wildArgs twice this could be:
```suggestion
          val args1 = wildArgs
          val lo1 = if lo.typeParams.hasSameLengthAs(args) then lo.appliedTo(args1) else lo
          WildcardType(TypeBounds(lo1, hi.appliedTo(args1)))
```

**Review by smarter — APPROVED** [review]
LGTM, nice improvement!
