### ISSUE TITLE
An implicit val should not be available for defining itself?

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#6114]
The following code compiles in Scalac 2.12. However, if we give explicit type to `x`, it compiles neither in Scalac nor Dotty.

```Scala
class Test {
  implicit val m: Int = 10
  def get(implicit x: Int): Int = ???
  def bar: Unit = {
    implicit val x = get
    // implicit val x: Int = get
  }
}
```

Error message:

```Scala
5 |    implicit val x: Int = get
  |                             ^
  |               x is a forward reference extending over the definition of x
```

Such code exists in [ScalaTest](https://github.com/scalatest/scalatest/blob/3.1.x/scalactic-test/src/test/scala/org/scalactic/ChainSpec.scala#L292):

```Scala
implicit val strEq = StringNormalizations.lowerCased.toEquality
es.contains("one") shouldBe true;
es.contains("ONE") shouldBe false

trait NormalizingEquality[A] extends Equality[A]

trait Uniformity[A] extends Normalization[A] {
    final def toEquality(implicit equality: Equality[A]): NormalizingEquality[A] = ...
}


```

**Comment by smarter** [comment]
Paging @milessabin since this reminds me of [`cachedImplicit` in shapeless ](https://github.com/milessabin/shapeless/blob/906875e9eaedbcdedb3a7b63e5d34bd2b70f2def/core/src/main/scala/shapeless/package.scala#L111) whose semantics I'm sure he can explain :).

**Comment by allanrenucci** [comment]
Forward definitions, also are available to the implicit scope:
```scala
scala> def test: Unit = { implicitly[Int]; implicit val foo: Int = 1 }
<console>:11: error: forward reference extends over definition of value foo
       def test: Unit = { implicitly[Int]; implicit val foo: Int = 1 }
```

Some discussions about what should be and not be in the implicit scope happened [here](https://github.com/lampepfl/dotty/issues/4709#issuecomment-400035341).

If I remember correctly, at the time @odersky said it was tricky to exclude some vals from the implicit scope and better to have the forward reference checker reports invalid implicitly inferred references.

**Comment by milessabin** [comment]
You're seeing the forward reference error in this case because `x` is a local definition. If you move it to the top level it'll compile with the explicit type annotation.

Self references of this sort are unproblematic and should be accepted if the implicit argument they correspond to is by-name, ie. `def get(implicit x: => Int): Int = ???`.

**Comment by liufengyun** [comment]
> Self references of this sort are unproblematic and should be accepted if the implicit argument they correspond to is by-name, ie. `def get(implicit x: => Int): Int = ???`.

It has to do with initialization, if `x` is used inside `get` eagerly, then `x` will be an uninitialized default value `0`, which is unsafe.

**Comment by milessabin** [comment]
> if x is used inside get eagerly, then x will be an uninitialized default value 0, which is unsafe.

Yes, but that's orthogonal to the implicitness or otherwise of the definitions and arguments here.

**Comment by liufengyun** [comment]
@odersky suggested that a migration for the following code:

```Scala
  def libMethod(implicit x: Int): Int = ???

  implicit val m: Int = 10
  def bar: Unit = {
      implicit val x = libMethod
      implicitly[Int]
  }
```

would be like the follows:

```Scala
  def libMethod(implicit x: Int): Int = ???

  implicit val m: Int = 10
  def bar: Unit = {
      implicit def x(implicit x: Int): Int = libMethod
      implicitly[Int]
  }
```

I verified that it indeed works in Dotty. However, the code above doesn't compile in Scala 2.12.

**Comment by odersky** [comment]
> I verified that it indeed works in Dotty. However, the code above doesn't compile in Scala 2.12.

Why does it not compile? Is it that you get a divergence error?

**Comment by liufengyun** [comment]
Scala2 produces the following error:

```
examples/test.scala:6: error: ambiguous implicit values:
 both value m in object Test of type => Int
 and value x of type Int
 match expected type Int
      implicit def x(implicit x: Int): Int = libMethod
                                             ^
examples/test.scala:7: error: ambiguous implicit values:
 both method x of type (implicit x: Int)Int
 and value m in object Test of type => Int
 match expected type Int
      implicitly[Int]
                ^
two errors found
```

/cc: @adriaanm  @milessabin

**Comment by OlivierBlanvillain** [comment]
Looking back at the initial example it seams like it's exploiting a loop hole in scalac which which requires an implicit without explicit return type. Is there any action to be taken here or should we just close the issue?

**Comment by liufengyun** [comment]
Close, the Dotty behavior is principled.
