### ISSUE TITLE
Surprising error in `3.3.0-RC2` with `-Xcheck-macros`

### ISSUE THREAD

**Issue by arainko** [lampepfl/dotty#16793]
## Compiler version

3.3.0-RC2, 3.3.1-RC1-bin-20230130-3e21f03-NIGHTLY

## Minimized code

```scala
// -Xcheck-macros is needed for the error to trigger
import scala.quoted.*

trait ReproTransformer[A, B] {
  def transform(value: A): B
}

object ReproTransformer {
  given identity[A]: ReproTransformer[A, A] with {
    def transform(value: A): A = value
  }

  inline given toAnyVal[A, B <: AnyVal]: ReproTransformer[A, B] = ${ toAnyValTransformer[A, B] }

  inline def summon[A, B]: ReproTransformer[A, B] = ${ summonTransformer[A, B] }

  private def summonTransformer[A: Type, B: Type](using Quotes) = Expr.summon[ReproTransformer[A, B]].get

  private def toAnyValTransformer[A: Type, B <: AnyVal: Type](using Quotes): Expr[ReproTransformer[A, B]] = 
    '{ value => ${ transform[A, B]('value) } }
  
  private def transform[Source: Type, Dest <: AnyVal: Type](source: Expr[Source])(using Quotes): Expr[Dest] = {
    import quotes.reflect.*

    val tpe = TypeRepr.of[Dest]

    New(Inferred(tpe))
      .select(tpe.typeSymbol.primaryConstructor)
      .appliedTo(source.asTerm)
      .asExprOf[Dest]
  }
}
```

```scala
// -Xcheck-macros is needed for the error to trigger

import scala.compiletime.*

object usage {
  val works1 = summon[ReproTransformer[String, String]]
  val works2 = summonInline[ReproTransformer[String, String]]

  /*
    Exception occurred while executing macro expansion.
    dotty.tools.dotc.reporting.UnhandledError: too many arguments for constructor AnyVal in class AnyVal: (): AnyVal
    ...
  */
  val error = ReproTransformer.summon[String, String]
}
```

## Output

<details>
<summary>

```scala
Exception occurred while executing macro expansion.
dotty.tools.dotc.reporting.UnhandledError: too many arguments for constructor AnyVal in class AnyVal: (): AnyVal
	at dotty.tools.dotc.reporting.ThrowingReporter.doReport(ThrowingReporter.scala:14)
...
```

</summary>

```scala
Exception occurred while executing macro expansion.
dotty.tools.dotc.reporting.UnhandledError: too many arguments for constructor AnyVal in class AnyVal: (): AnyVal
	at dotty.tools.dotc.reporting.ThrowingReporter.doReport(ThrowingReporter.scala:14)
	at dotty.tools.dotc.reporting.Reporter.issueUnconfigured(Reporter.scala:158)
	at dotty.tools.dotc.reporting.Reporter.go$1(Reporter.scala:181)
	at dotty.tools.dotc.reporting.Reporter.issueIfNotSuppressed(Reporter.scala:200)
	at dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:203)
	at dotty.tools.dotc.reporting.Reporter.flush$$anonfun$1(Reporter.scala:261)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.reporting.Reporter.flush(Reporter.scala:261)
	at dotty.tools.dotc.core.TyperState.commit(TyperState.scala:175)
	at dotty.tools.dotc.typer.Applications.fail$1(Applications.scala:1048)
	at dotty.tools.dotc.typer.Applications.realApply$1$$anonfun$3$$anonfun$1(Applications.scala:1054)
	at scala.Option.getOrElse(Option.scala:201)
	at dotty.tools.dotc.typer.Applications.realApply$1$$anonfun$3(Applications.scala:1055)
	at dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:3201)
	at dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:1056)
	at dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1094)
	at dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:352)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedApply(TreeChecker.scala:499)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2928)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2991)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:395)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:378)
	at dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1955)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedInlined$$anonfun$1(TreeChecker.scala:610)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:245)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedInlined(TreeChecker.scala:610)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2950)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2991)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:395)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:378)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3174)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1102)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1$$anonfun$1(TreeChecker.scala:607)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:245)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1(TreeChecker.scala:607)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withBlock(TreeChecker.scala:273)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock(TreeChecker.scala:607)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2936)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2991)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:395)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:378)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3174)
	at dotty.tools.dotc.typer.Typer.$anonfun$49(Typer.scala:2382)
	at dotty.tools.dotc.inlines.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:249)
	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2382)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef$$anonfun$1(TreeChecker.scala:582)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:245)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedDefDef(TreeChecker.scala:585)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2904)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2990)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:395)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:378)
	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3084)
	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3130)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedStats(TreeChecker.scala:625)
	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1096)
	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1100)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1$$anonfun$1(TreeChecker.scala:607)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:245)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock$$anonfun$1(TreeChecker.scala:607)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withBlock(TreeChecker.scala:273)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedBlock(TreeChecker.scala:607)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2936)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2991)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:395)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:378)
	at dotty.tools.dotc.typer.Typer.typedInlined(Typer.scala:1955)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedInlined$$anonfun$1(TreeChecker.scala:610)
	at dotty.tools.dotc.transform.TreeChecker$Checker.withDefinedSyms(TreeChecker.scala:245)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedInlined(TreeChecker.scala:610)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2950)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2991)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:395)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:378)
	at dotty.tools.dotc.transform.TreeChecker$.checkMacroGeneratedTree(TreeChecker.scala:729)
	at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedApply(Inliner.scala:819)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2928)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2991)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
	at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:904)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
	at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:64)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2933)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2991)
	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:126)
	at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:904)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3058)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3055)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3062)
	at dotty.tools.dotc.inlines.Inliner.inlined(Inliner.scala:671)
	at dotty.tools.dotc.inlines.Inlines$InlineCall.expand(Inlines.scala:444)
	at dotty.tools.dotc.inlines.Inlines$.inlineCall(Inlines.scala:151)
	at dotty.tools.dotc.typer.Typer.adaptNoArgsOther$1(Typer.scala:3807)
	at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3907)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4120)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3435)
	at dotty.tools.dotc.typer.Typer.readapt$1(Typer.scala:3446)
	at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4107)
	at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3435)
	at dotty.tools.dotc.typer.Implicits.typedImplicit(Implicits.scala:1079)
	at dotty.tools.dotc.typer.Implicits.typedImplicit$(Implicits.scala:806)
	at dotty.tools.dotc.typer.Typer.typedImplicit(Typer.scala:115)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.tryImplicit(Implicits.scala:1201)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.rank$1(Implicits.scala:1300)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1470)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1498)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1506)
	at dotty.tools.dotc.typer.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1531)
	at dotty.tools.dotc.typer.Implicits.inferImplicit(Implicits.scala:1022)
	at dotty.tools.dotc.typer.Implicits.inferImplicit$(Implicits.scala:806)
	at dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:115)
	at dotty.tools.dotc.typer.Implicits.inferImplicitArg(Implicits.scala:872)
	at dotty.tools.dotc.typer.Implicits.inferImplicitArg$(Implicits.scala:806)
	at dotty.tools.dotc.typer.Typer.inferImplicitArg(Typer.scala:115)
	at scala.quoted.runtime.impl.QuotesImpl$reflect$Implicits$.search(QuotesImpl.scala:2408)
	at scala.quoted.runtime.impl.QuotesImpl$reflect$Implicits$.search(QuotesImpl.scala:2406)
	at scala.quoted.Expr$.summon(Expr.scala:232)
	at io.github.arainko.ducktape.ReproTransformer$.summonTransformer(ReproTransformer.scala:18)
	at io.github.arainko.ducktape.ReproTransformer$.inline$summonTransformer(ReproTransformer.scala:18)
```

</details>

## Expectation
No error

## Context
I decided to check how [ducktape](https://github.com/arainko/ducktape) fares on `3.3.0-RC2` and the newest nightly at the time and to my surprise none on my tests were compiling and everything was red.
After diving deeper, it turned out that `-Xcheck-macros` was causing this in some way, which may imply I was the one to mess some trees up.
The real one to blame was a macro that generated transformers for unwrapped values to their wrapped `AnyVal` counterparts and how it interacted with implicit search triggered with `Implicits.search` which triggers the `AnyVal` wrapping macro which then aborts the whole expansion instead of just failing the search. I still don't see how I might've messed up there so here I'm reporting this suspicious behavior :smile: 

This of course can be worked around by not using `-Xcheck-macros` but I'd rather not do it for a codebase that is 90% macros, plus the same code compiles on `3.2.2` and `3.2.1`

**Comment by nicolasstucki** [comment]
In the case that fails you construct `new scala.AnyVal(value)`. This failure is expected.

Not sure why this code does not fail without `-Xcheck-macros`.

**Comment by arainko** [comment]
I've investigated that a little bit further by altering the `transform` method with a `println` to see what actually happens:

```scala
private def transform[Source: Type, Dest <: AnyVal: Type](source: Expr[Source])(using Quotes): Expr[Dest] = {
    import quotes.reflect.*

    val tpe = TypeRepr.of[Dest]
    
    println(s"Evaluating 'transform' with Source: ${Type.show[Source]} and Dest: ${Type.show[Dest]}")

    New(Inferred(tpe))
      .select(tpe.typeSymbol.primaryConstructor)
      .appliedTo(source.asTerm)
      .asExprOf[Dest]
  }
```

and after a `clean; compile` got this output:
```bash
Evaluating 'transform' with Source: scala.Any and Dest: scala.AnyVal
[error] -- Error: /home/aleksander/repos/ducktape/ducktape/src/main/scala/io/github/arainko/ducktape/usage.scala:14:37 
[error] 14 |  val error = ReproTransformer.summon[String, String]
[error]    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Exception occurred while executing macro expansion.
[error]    |dotty.tools.dotc.reporting.UnhandledError: too many arguments for constructor AnyVal in class AnyVal: (): AnyVal
[error]    |    at dotty.tools.dotc.reporting.ThrowingReporter.doReport(ThrowingReporter.scala:14)
[error]    |    at dotty.tools.dotc.reporting.Reporter.issueUnconfigured(Reporter.scala:158)
```

So yeah, looks like it that method gets evaluated despite the types (`String` and `String`) not matching the the bounds (`String <!:< AnyVal`) but the types seem to be... Widened (?) to `Any` and `AnyVal` hence the error.

What's interesting is if I drop the `B <: AnyVal` bound from all of the methods and use evidence in `toAnyValTransformer`, like so:
```scala
  inline given toAnyVal[A, B](using B <:< AnyVal): ReproTransformer[A, B] = ${ toAnyValTransformer[A, B] }

  inline def summon[A, B]: ReproTransformer[A, B] = ${ summonTransformer[A, B] }

  private def summonTransformer[A: Type, B: Type](using Quotes) = Expr.summon[ReproTransformer[A, B]].get

  private def toAnyValTransformer[A: Type, B: Type](using Quotes): Expr[ReproTransformer[A, B]] = 
    '{ value => ${ transform[A, B]('value) } }
  
  private def transform[Source: Type, Dest: Type](source: Expr[Source])(using Quotes): Expr[Dest] = {
    import quotes.reflect.*

    val tpe = TypeRepr.of[Dest]

    println(s"Evaluating 'transform' with Source: ${Type.show[Source]} and Dest: ${Type.show[Dest]}")

    New(Inferred(tpe))
      .select(tpe.typeSymbol.primaryConstructor)
      .appliedTo(source.asTerm)
      .asExprOf[Dest]
  }
```

the usages work as expected and after a `clean; compile` nothing is printed to the terminal (ergo, `transform` is not evaluated) which of course makes perfect sense from the implicit resolution point of view, it's just that I'd expect the version with a type bound to work the same I guess.

Nevertheless, I think it all works as expected, plus the additional checks in `-Xcheck-macros` do their work perfectly as I observed the same behavior on 3.2.1 (a lot of widening to `Any` and `AnyVal` for types that do not match and subsequent drops from macro expansion which gets fixed by just using the evidence pattern instead of a type bound for givens).
