### ISSUE TITLE
Function type ascription needs parenthesis 

### ISSUE THREAD

**Issue by mlachkar** [lampepfl/dotty#9993]
## Minimized code

```Scala
def foo[T]: () => T = ??? : () => T
```

## Output

```scala
[error] -- [E040] Syntax Error: /Users/meriamlachkar/perso/dotty/src/main/scala/Show.scala:4:29 
[error] 4 |def foo[T]: () => T = ??? : () => T
[error]   |                             ^
[error]   |                             an identifier expected, but ')' found
[error] -- Error: /Users/meriamlachkar/perso/dotty/src/main/scala/Show.scala:4:31 ------
[error] 4 |def foo[T]: () => T = ??? : () => T
[error]   |                               ^
[error]   |             parentheses are required around the parameter of a lambda
[error]   |             This construct can be rewritten automatically under -rewrite.
[error] -- [E006] Not Found Error: /Users/meriamlachkar/perso/dotty/src/main/scala/Show.scala:4:34 
[error] 4 |def foo[T]: () => T = ??? : () => T
[error]   |                                  ^
[error]   |                                  Not found: T
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed
```

## Expectation
This compiles in scala 2.13, and it could be nice if it compiles in dotty too.
To make this compile in dotty: 
```Scala
def foo[T]: () => T = ??? : (() => T)
```

**Comment by odersky** [comment]
The Scala syntax defines:
```
Ascription        ::=  ‘:’ InfixType
                      |  ‘:’ Annotation {Annotation}
                      |  ‘:’ ‘_’ ‘*’
```
So this example should not compile. There's a discrepancy between the Scala 2.13 parser and the syntax in the spec. It would be hard to change the syntax in general to be more permissive, sio I think we need to close this one.
