### ISSUE TITLE
Can not load WeakPairMap$Pair$Weak$1 classfile

### ISSUE THREAD

**Issue by Linyxus** [lampepfl/dotty#12643]
## Compiler version

3.0.0

## Minimized code

```Scala
def foo: java.lang.WeakPairMap$Pair$Weak$1 = ???
```

## Output

```scala
[info] running (fork) dotty.tools.dotc.Main -classpath /Users/linyxus/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar:/Users/linyxus/Develop/dotty/library/../out/bootstrap/scala3-library-bootstrapped/scala-3.0.0-RC2/scala3-library_3.0.0-RC2-3.0.0-RC2-bin-SNAPSHOT.jar -color:never issue/weak-pair-map-classfile.scala
error while loading WeakPairMap$Pair$Weak$1,
class file /modules/java.base/java/lang/WeakPairMap$Pair$Weak$1.class is broken, reading aborted with class java.util.NoSuchElementException
key not found: K2
-- [E008] Not Found Error: issue/weak-pair-map-classfile.scala:1:19 ------------------------------------------------------------------------------------------------------------------------------------------
1 |def foo: java.lang.WeakPairMap$Pair$Weak$1 = ???
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |         type WeakPairMap$Pair$Weak$1 is not a member of java.lang - did you mean lang.WeakPairMap$Pair$Weak$1?
2 errors found
[error] Nonzero exit code returned from runner: 1
[error] (scala3-compiler / Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 3 s, completed May 26, 2021, 2:36:49 PM
```

## Expectation

The compiler should load the classfile properly.

**Comment by smarter** [comment]
This does not work in a recent Scala 2.12 or 2.13 either and I don't see why it should work, inner classes are implementation details, moreover here, even java.lang.WeakPairMap by itself is not public.

**Comment by abgruszecki** [comment]
@smarter the problem here is that we cannot load the classfile at all. Do you mean to say that this is expected behaviour for inner classes?

**Comment by abgruszecki** [comment]
This came up when we were (accidentally) trying to load all types in a package, which eventually led to loading this class and the compiler blowing up on it.

I'm tentatively re-opening the issue.

**Comment by smarter** [comment]
In source code, you're not supposed to refer to an inner class by its encoded name `Foo$Bla$...`, instead you can refer to it as `Outer#Inner`, but that's only valid if Outer is accessbile to you, java.lang.WeakPairMap is not public so it's not accessible to you.

**Comment by abgruszecki** [comment]
So do I understand correctly that we're supposed to be unable to load classfiles of inner classes? You've seen this part of the error message, right?
```
error while loading WeakPairMap$Pair$Weak$1,
class file /modules/java.base/java/lang/WeakPairMap$Pair$Weak$1.class is broken, reading aborted with class java.util.NoSuchElementException
key not found: K2
```

**Comment by smarter** [comment]
Ah no, I missed the "is broken" part, that shouldn't happen indeed.

**Comment by abgruszecki** [comment]
@Linyxus can you add your JVM version to the issue?

From myself I can add that other (?) classfile parses also seem to be having analogous problems: https://github.com/mockk/mockk/issues/130

**Comment by smarter** [comment]
Ah nevermind, I can reproduce this on Java 16 but not on Java 8, so here's the stacktrace:
```scala
java.util.NoSuchElementException: key not found: K2
        at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:225)
        at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:221)
        at dotty.tools.dotc.core.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:455)
        at dotty.tools.dotc.core.classfile.ClassfileParser.processTypeArgs$1(ClassfileParser.scala:383)
        at dotty.tools.dotc.core.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:398)
        at dotty.tools.dotc.core.classfile.ClassfileParser.dotty$tools$dotc$core$classfile$ClassfileParser$$sigToType(ClassfileParser.scala:522)
        at dotty.tools.dotc.core.classfile.ClassfileParser$AttributeCompleter.complete(ClassfileParser.scala:665)
        at dotty.tools.dotc.core.classfile.ClassfileParser.parseClass(ClassfileParser.scala:190)
        at dotty.tools.dotc.core.classfile.ClassfileParser.$anonfun$1(ClassfileParser.scala:87)
        at dotty.tools.dotc.core.classfile.ClassfileParser.run(ClassfileParser.scala:82)
        at dotty.tools.dotc.core.ClassfileLoader.load(SymbolLoaders.scala:414)
        at dotty.tools.dotc.core.ClassfileLoader.doComplete(SymbolLoaders.scala:409)
        at dotty.tools.dotc.core.SymbolLoader.complete(SymbolLoaders.scala:343)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:167)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeOnce(SymDenotations.scala:361)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.isAbsent(SymDenotations.scala:571)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.isAccessibleFrom(SymDenotations.scala:870)
        at dotty.tools.dotc.typer.ProtoTypes$SelectionProto.qualifies$1(ProtoTypes.scala:200)
        at dotty.tools.dotc.typer.ProtoTypes$SelectionProto.isMatchedBy(ProtoTypes.scala:207)
        at dotty.tools.dotc.core.TypeComparer.isMatchedByProto(TypeComparer.scala:1856)
        at dotty.tools.dotc.core.TypeComparer.firstTry$1(TypeComparer.scala:305)
        at dotty.tools.dotc.core.TypeComparer.recur(TypeComparer.scala:1282)
        at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:185)
        at dotty.tools.dotc.core.TypeComparer.isSubType(TypeComparer.scala:195)
        at dotty.tools.dotc.core.TypeComparer.topLevelSubType(TypeComparer.scala:128)
        at dotty.tools.dotc.core.TypeComparer.testSubType(TypeComparer.scala:144)
        at dotty.tools.dotc.core.TypeComparer$.testSubType(TypeComparer.scala:2690)
        at dotty.tools.dotc.typer.Typer.adaptNoArgsOther$4(Typer.scala:3524)
        at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:3620)
        at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3811)
        at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3163)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2823)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2827)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2943)
        at dotty.tools.dotc.typer.Typer.typeSelectOnTerm$1(Typer.scala:609)
        at dotty.tools.dotc.typer.Typer.typedSelect(Typer.scala:659)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2665)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2757)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2823)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2827)
        at dotty.tools.dotc.typer.Namer.typedAheadType$$anonfun$1(Namer.scala:1389)
        at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1381)
        at dotty.tools.dotc.typer.Namer.typedAheadType(Namer.scala:1389)
        at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1635)
        at dotty.tools.dotc.typer.Namer.defDefSig(Namer.scala:1685)
        at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:703)
        at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:826)
        at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:727)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:167)
        at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
        at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
        at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:369)
        at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2637)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2662)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2757)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2823)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2827)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2849)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2899)
        at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2354)
        at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2683)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2687)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2757)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2823)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2827)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2849)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2899)
        at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2477)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2728)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2758)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2823)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2827)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2943)
        at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
        at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
        at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:43)
        at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
        at dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:120)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:120)
        at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$5(Run.scala:216)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:224)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:231)
        at dotty.tools.dotc.Run.compileSources(Run.scala:166)
        at dotty.tools.dotc.Run.compile(Run.scala:150)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
        at dotty.tools.dotc.Driver.process(Driver.scala:199)
        at dotty.tools.dotc.Driver.process(Driver.scala:167)
        at dotty.tools.dotc.Driver.process(Driver.scala:179)
        at dotty.tools.dotc.Driver.main(Driver.scala:209)
        at dotty.tools.dotc.Main.main(Main.scala)
java.io.IOException: class file /modules/java.base/java/lang/WeakPairMap$Pair$Weak$1.class is broken, reading aborted with class java.util.NoSuchElementException
```

**Comment by abgruszecki** [comment]
@smarter yep, this only happens starting from JDK 11 I believe.

**Comment by smarter** [comment]
The same issue is also reproducible on Scala 2 so you might want to report it there too, but it'd be helpful both here and there to explain why this could be a problem in practice.
