### ISSUE TITLE
MapProxy: cant find outer this

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#940]
```
./scala-scala/src/library/scala/collection/immutable/MapProxy.scala:40: error: MapProxy is not an enclosing class
  override def keySet: immutable.Set[A] = new SetProxy[A] { val self = MapProxy.this.self.keySet }
```

Does not happen if compiled separately.

**Comment by DarkDimius** [comment]
fixed
