### ISSUE TITLE
Traits do not have static forwarders in bytecode

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7328]
## minimized code

compile with dotc `19.0-RC1`
```Scala
trait Foo { def foo: String = "foo" }
```

compile with https://github.com/scalacenter/scala/commit/a8f11efb7513a15646f08d05f746acfed6e04cd7
```Scala
object TestFoo {
  def main(args: Array[String]): Unit = {
    assert(new Foo {}.foo == "foo")
  }
}
```

runtime error:

```
Exception in thread "main" java.lang.NoSuchMethodError: Foo.foo$(LFoo;)Ljava/lang/String;
	at TestFoo$$anon$1.foo(TestFoo.scala:5)
	at TestFoo$.main(TestFoo.scala:5)
	at TestFoo.main(TestFoo.scala)
        ...
```

## expectation

Anonymous subclasses of traits generated by Scala 2.13.x implement methods by calling a static forwarder on the generated Interface.

**Comment by smarter** [comment]
Dotty and Scala 2 use a some what different trait encodings. For differences in forwaders see https://github.com/lampepfl/dotty/issues/5928, for differences in initialization see https://github.com/scala/scala-dev/issues/642. It's likely that we'll end up changing both scalac and dotty to converge to a single representation, but until that happens feel free to make a PR adding static forwarders to Dotty if that makes your work easier.

**Comment by bishabosha** [comment]
So I believe this should be closed in favour of an issue to move the whole scala 2 scheme over, as seen here field initialisation and access just isn't compatible

The following trait is compiled with Dotty
```scala
trait TraitWithSideEffects {
  val map: mutable.AnyRefMap[String, Boolean] = mutable.AnyRefMap.empty

  map += "True"  -> true
  map += "False" -> false
}
```

an anonymous subclass for TraitWithSideEffects looks like this in scalac with tasty reader: (using CFR 0.146)
```java
public final class TraitWithSideEffects$.anon.1
implements TraitWithSideEffects {
    @Override
    public AnyRefMap<String, Object> map() {
        return TraitWithSideEffects.map$((TraitWithSideEffects)this);
    }
}
```

and the correct implementation produced by dotty:

```java
private static final class TraitWithSideEffects$.anon.1
implements TraitWithSideEffects {
    private final AnyRefMap map = TraitWithSideEffects.super.initial$map();

    public AnyRefMap map() {
        return this.map;
    }
}
```

**Comment by sjrd** [comment]
Fixed in #8652.
