### ISSUE TITLE
Output type mismatch in SAM

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#18315]
## Compiler version

3.4.0-RC1-bin-20230729-a73316a-NIGHTLY - failing, current nightly
3.3.2-RC1-bin-20230715-4851278-NIGHTLY - first bad release (first bad commit: 18f90d9701)
3.3.2-RC1-bin-20230714-04eae14-NIGHTLY - last good release

## Minimized code

```scala
trait Zippable[-A, -B] {
  type Out
  def zip(left: A, right: B): Out
}

object Zippable extends ZippableLowPrio:
  given append[A <: Tuple, B]: (Zippable[A, B] { type Out = Tuple.Append[A, B] }) =
    (left, right) => left :* right

trait ZippableLowPrio:
  given pair[A, B]: (Zippable[A, B] { type Out = (A, B) }) =
    (left, right) => (left, right)

def zip[A, B](a: A, b: B)(using z: Zippable[A, B]) = z.zip(a, b)

object Test:
  val x1: (Int, Int)           = zip(1, 2)
  val x2: (Int, Int, Int)      = zip((1, 2), 3)
  val x3: (Int, Int, Int, Int) = zip((1, 2, 3), 4)
```

## Output

```scala
-- [E008] Not Found Error: Zippable.scala:8:26 
8 |    (left, right) => left :* right
  |                     ^^^^^^^
  |                     value :* is not a member of A
-- [E007] Type Mismatch Error: Zippable.scala:12:21 
12 |    (left, right) => (left, right)
   |                     ^^^^^^^^^^^^^
   |                     Found:    (A, B)
   |                     Required: Zippable.this.Out
   |
   | longer explanation available when compiling with `-explain`
```

With `-explain` enabled:

```scala
[error] Zippable.scala:8:22
[error] value :* is not a member of A
[error]     (left, right) => left :* right
[error]                      ^^^^^^^
[error] Zippable.scala:12:22
[error] Found:    (A, B)
[error] Required: Zippable.this.Out
[error] 
[error] Explanation
[error] ===========
[error] 
[error] Tree: Tuple2.apply[A, B](left, right)
[error] I tried to show that
[error]   (A, B)
[error] conforms to
[error]   Zippable.this.Out
[error] but the comparison trace ended with `false`:
[error] 
[error]   ==> (A, B)  <:  Zippable.this.Out
[error]   <== (A, B)  <:  Zippable.this.Out = false
[error] 
[error] The tests were made under the empty constraint
[error]     (left, right) => (left, right)
[error]                      ^^^^^^^^^^^^^
```

## Expectation

The code should compile successfully

**Comment by prolativ** [comment]
It looks like it's not really only about the output type. The following code also stopped compiling because of the regression:
```scala
trait Foo {
  type XXX
  def foo(x: Int): Int
}

def makeFoo: Foo { type XXX = String } =
  x => x
```
Compilation error (with `-explain`):
```scala
[error] Foo.scala:7:3
[error] Found:    <notype>
[error] Required: Foo{type XXX = String}
[error] 
[error] Explanation
[error] ===========
[error] 
[error] Tree: {
[error]   def $anonfun(x: Int): Int =
[error]     {
[error]       x
[error]     }
[error]   closure($anonfun:<notype>)
[error] }
[error] I tried to show that
[error]   <notype>
[error] conforms to
[error]   Foo{type XXX = String}
[error] but the comparison trace ended with `false`:
[error] 
[error]   ==> <notype>  <:  Foo{type XXX = String}
[error]     ==> <notype>  <:  Foo
[error]     <== <notype>  <:  Foo = false
[error]   <== <notype>  <:  Foo{type XXX = String} = false
[error] 
[error] The tests were made under the empty constraint
[error]   x => x
[error]   ^^^^^^
```
The error disappears when `Foo { type XXX = String }` gets replaced with just `Foo`

**Comment by smarter** [comment]
It looks like this only worked by chance. Scala 2 doesn't support refinements in SAM types, and supporting them properly when a SAM type closure is expanded into an anonymous class is non-trivial (the refinement has to be moved inside the class). For example, Scala 3.3.0 compiles the following code, but it crashes with `-Ycheck:all` because of the malformed tree after phase ExpandSAMs:
```scala
trait Foo {
  var x: Int = 1
  type XXX
  def foo(x: Int): Int
}

object Test {
  def makeFoo: Foo { type XXX = String } =
    x => x
}
```
```scala
java.lang.AssertionError: assertion failed:
Found:    Object with Foo {...}
Required: Foo{type XXX = String}
```

I see you've put this in the 3.3.2 milestone, but there is currently no release-3.3.2 branch and main is now on 3.4.x, so I don't know if https://github.com/lampepfl/dotty/pull/18201 is in what will become 3.3.2 /cc @Kordyjan .

**Comment by prolativ** [comment]
If we can't make this work, we should at least make the error message clear, warning users that SAM conversions don't work with refinements
