### ISSUE TITLE
VSCode refuses to start

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#4160]
I get on current master:

    vscode-dotty/test/extension.test.ts(15,1): error TS2304: Cannot find name 'suite'.

    15 suite("vscode-dotty tests", function () {
       ~~~~~


    vscode-dotty/test/extension.test.ts(18,5): error TS2304: Cannot find name 'test'.

    18     test("dummy test", function() {
           ~~~~

    [error] Running command "/Users/odersky/workspace/dotty/vscode-dotty/node_modules/.bin/tsc --pretty --project /Users/odersky/workspace/dotty/vscode-dotty" failed.
    [error] (vscode-dotty/compile:compile) Running command "/Users/odersky/workspace/dotty/vscode-dotty/node_modules/.bin/tsc --pretty --project 
    /Users/odersky/workspace/dotty/vscode-dotty" failed.
    [error] Total time: 1 s, completed Mar 22, 2018 7:16:38 PM

@smarter Any idea what could be the cause of this?

**Comment by odersky** [comment]
The failing test was recently added in #4136.

**Comment by smarter** [comment]
woops indeed, I'm on it.
