### ISSUE TITLE
Crash AssertionError with ZIO http Response builder - only when hanlding a method

### ISSUE THREAD

**Issue by giulianods** [lampepfl/dotty#19547]
## Compiler version

version 3.3.1

## Dependencies

libraryDependencies := Seq("dev.zio" %% "zio" % "2.0.19", "dev.zio" %% "zio-http" % "3.0.0-RC4")

## Minimized code

```Scala
import zio.*
import zio.http.*
object Main extends ZIOAppDefault{
  private def getSymbols(): ZIO[Any, Throwable, Seq[String]] = ZIO.succeed(Seq("a", "b", "c"))
  private val app: HttpApp[Any] =
    Routes(
      // This line works fine
      Method.GET / "symbols" -> Handler.fromZIO(ZIO.succeed(Seq("a", "b", "c")).map(r => Response.text(r.mkString("\n")))),

      // this line causes a crash in the compiler (commenting this line will pass the compilation) !
      Method.GET / "symbols2" -> Handler.fromZIO(getSymbols().map(r => Response.text(r.mkString("\n")))),
    ).toHttpApp
  override val run =
    Server.serve(app).provide(Server.default)
}


```

## Output (click arrow to expand)

Crash while compiling

<details>

```scala
[info]
[info]                 tree: EmptyTree
[info]        tree position: :<unknown>
[info]            tree type: <notype>
[info]               symbol: val <none>
[info]            call site: package <root> in module class <root>
[info]
[info]   == Source file context for tree position ==
[info]
[error] ## Exception when compiling 1 sources to C:\....\target\scala-3.3.1\classes
[error] java.lang.AssertionError: assertion failed
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
[error] dotty.tools.dotc.ast.tpd$.TypeApply(tpd.scala:60)
[error] dotty.tools.dotc.ast.tpd$TreeOps$.appliedToTypeTrees$extension(tpd.scala:985)
[error] dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4255)
[error] dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3587)
[error] dotty.tools.dotc.typer.ProtoTypes$FunProto.typedArg(ProtoTypes.scala:497)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:897)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.typedArg(Applications.scala:897)
[error] dotty.tools.dotc.typer.Applications$Application.addTyped$1(Applications.scala:589)
[error] dotty.tools.dotc.typer.Applications$Application.matchArgs(Applications.scala:653)
[error] dotty.tools.dotc.typer.Applications$Application.init(Applications.scala:492)
[error] dotty.tools.dotc.typer.Applications$TypedApply.<init>(Applications.scala:779)
[error] dotty.tools.dotc.typer.Applications$ApplyToUntyped.<init>(Applications.scala:896)
[error] dotty.tools.dotc.typer.Applications.ApplyTo(Applications.scala:1126)
[error] dotty.tools.dotc.typer.Applications.ApplyTo$(Applications.scala:352)
[error] dotty.tools.dotc.typer.Typer.ApplyTo(Typer.scala:116)
[error] dotty.tools.dotc.typer.Applications.simpleApply$1(Applications.scala:969)
[error] dotty.tools.dotc.typer.Applications.realApply$1$$anonfun$2(Applications.scala:1052)
[error] dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:3324)
[error] dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:1063)
[error] dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1101)
[error] dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:352)
[error] dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:116)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3048)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3112)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3184)
[error] dotty.tools.dotc.typer.Implicits.tryConversion$1(Implicits.scala:1136)
[error] dotty.tools.dotc.typer.Implicits.typedImplicit(Implicits.scala:1167)
[error] dotty.tools.dotc.typer.Implicits.typedImplicit$(Implicits.scala:818)
[error] dotty.tools.dotc.typer.Typer.typedImplicit(Typer.scala:116)
[error] dotty.tools.dotc.typer.Implicits$ImplicitSearch.tryImplicit(Implicits.scala:1242)
[error] dotty.tools.dotc.typer.Implicits$ImplicitSearch.rank$1(Implicits.scala:1341)
[error] dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1511)
[error] dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1539)
[error] dotty.tools.dotc.typer.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1547)
[error] dotty.tools.dotc.typer.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1572)
[error] dotty.tools.dotc.typer.Implicits.inferImplicit(Implicits.scala:1060)
[error] dotty.tools.dotc.typer.Implicits.inferImplicit$(Implicits.scala:818)
[error] dotty.tools.dotc.typer.Typer.inferImplicit(Typer.scala:116)
[error] dotty.tools.dotc.typer.Implicits.inferView(Implicits.scala:856)
[error] dotty.tools.dotc.typer.Implicits.inferView$(Implicits.scala:818)
[error] dotty.tools.dotc.typer.Typer.inferView(Typer.scala:116)
[error] dotty.tools.dotc.typer.Implicits.viewExists(Implicits.scala:831)
[error] dotty.tools.dotc.typer.Implicits.viewExists$(Implicits.scala:818)
[error] dotty.tools.dotc.typer.Typer.viewExists(Typer.scala:116)
[error] dotty.tools.dotc.typer.Implicits.ignoredConvertibleImplicits$1$$anonfun$3(Implicits.scala:960)
[error] scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:479)
[error] scala.collection.Iterator.isEmpty(Iterator.scala:466)
[error] scala.collection.Iterator.isEmpty$(Iterator.scala:466)
[error] scala.collection.AbstractIterator.isEmpty(Iterator.scala:1300)
[error] scala.collection.View$Filter.isEmpty(View.scala:146)
[error] scala.collection.IterableOnceOps.nonEmpty(IterableOnce.scala:833)
[error] scala.collection.IterableOnceOps.nonEmpty$(IterableOnce.scala:833)
[error] scala.collection.AbstractIterable.nonEmpty(Iterable.scala:933)
[error] dotty.tools.dotc.reporting.MissingImplicitArgument.noChainConversionsNote$1(messages.scala:2838)
[error] dotty.tools.dotc.reporting.MissingImplicitArgument.msgPostscript$$anonfun$4(messages.scala:2846)
[error] scala.Option.orElse(Option.scala:477)
[error] dotty.tools.dotc.reporting.MissingImplicitArgument.msgPostscript(messages.scala:2846)
[error] dotty.tools.dotc.reporting.Message.message$$anonfun$1(Message.scala:345)
[error] dotty.tools.dotc.reporting.Message.inMessageContext(Message.scala:341)
[error] dotty.tools.dotc.reporting.Message.message(Message.scala:345)
[error] dotty.tools.dotc.reporting.Message.isNonSensical(Message.scala:322)
[error] dotty.tools.dotc.reporting.HideNonSensicalMessages.isHidden(HideNonSensicalMessages.scala:16)
[error] dotty.tools.dotc.reporting.HideNonSensicalMessages.isHidden$(HideNonSensicalMessages.scala:10)
[error] dotty.tools.dotc.reporting.AbstractReporter.isHidden(AbstractReporter.scala:8)
[error] dotty.tools.dotc.reporting.Reporter.issueUnconfigured(Reporter.scala:156)
[error] dotty.tools.dotc.reporting.Reporter.go$1(Reporter.scala:181)
[error] dotty.tools.dotc.reporting.Reporter.issueIfNotSuppressed(Reporter.scala:200)
[error] dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:203)
[error] dotty.tools.dotc.report$.error(report.scala:68)
[error] dotty.tools.dotc.typer.Typer.issueErrors$1$$anonfun$1(Typer.scala:3808)
[error] scala.runtime.function.JProcedure3.apply(JProcedure3.java:15)
[error] scala.runtime.function.JProcedure3.apply(JProcedure3.java:10)
[error] scala.collection.LazyZip3.foreach(LazyZipOps.scala:248)
[error] dotty.tools.dotc.typer.Typer.issueErrors$1(Typer.scala:3810)
[error] dotty.tools.dotc.typer.Typer.addImplicitArgs$1(Typer.scala:3832)
[error] dotty.tools.dotc.typer.Typer.adaptNoArgsImplicitMethod$1(Typer.scala:3849)
[error] dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:4038)
[error] dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4268)
[error] dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3587)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3184)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3188)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3300)
[error] dotty.tools.dotc.typer.Typer.typedValDef(Typer.scala:2424)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3021)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3111)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3184)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3188)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3210)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3256)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2669)
[error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$1(Typer.scala:3036)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3040)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3111)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3184)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3188)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3210)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3256)
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2812)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3081)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3112)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3184)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:3188)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3300)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$1(TyperPhase.scala:44)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck$$anonfun$adapted$1(TyperPhase.scala:54)
[error] scala.Function0.apply$mcV$sp(Function0.scala:42)
[error] dotty.tools.dotc.core.Phases$Phase.monitor(Phases.scala:440)
[error] dotty.tools.dotc.typer.TyperPhase.typeCheck(TyperPhase.scala:54)
[error] dotty.tools.dotc.typer.TyperPhase.runOn$$anonfun$3(TyperPhase.scala:88)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.typer.TyperPhase.runOn(TyperPhase.scala:88)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:246)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:262)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:270)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:279)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:279)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:194)
[error] dotty.tools.dotc.Run.compile(Run.scala:179)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:180)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:178)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:464)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:419)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:406)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:172)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2371)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2321)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:31)
[error] sbt.internal.io.Retry$.apply(Retry.scala:47)
[error] sbt.internal.io.Retry$.apply(Retry.scala:29)
[error] sbt.internal.io.Retry$.apply(Retry.scala:24)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2319)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] sbt.Execute.work(Execute.scala:292)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] java.base/java.lang.Thread.run(Thread.java:1583)
```
</details>

**Comment by giulianods** [comment]
A hint, the Handler object requires the error-type to be a subtype of response (in my case it's not - it's a Throwable). So the line will have to give a compilation error for that.
I still haven't managed to create an example without any dependencies

``
def @@[Env1 <: R, Ctx, In1 <: In](aspect: HandlerAspect[Env1, Unit])(implicit
    in: In1 <:< Request,
    out: Out <:< Response,
    err: Err <:< Response,
``

**Comment by WojciechMazur** [comment]
Thank you for the report. It's one of the well known regressions introduced in 3.3.1. This issue is already fixed in 3.3.2-RC1 and 3.4.0-RC2. These versions should be soon available in the final version. It works in correctly also in 3.3.0.
