### ISSUE TITLE
Type inference doesn't look broader scope

### ISSUE THREAD

**Issue by andreaTP** [lampepfl/dotty#6672]
Repro:
```scala
trait Y4 {
  def foo = 1
}
trait X4

val z = new Y4 with X4 {}
z match {
  case a: X4 => a.foo
}
```

trigger:
```
value foo is not a member of X4
```

this code compile with scalac 2.12

**Comment by smarter** [comment]
Duplicate of https://github.com/lampepfl/dotty/issues/3208
