### ISSUE TITLE
Copying of function application with default macro casue an error with -Xcheck-macro. (regression)

### ISSUE THREAD

**Issue by rssh** [lampepfl/dotty#17445]
## Compiler version

3.1.1-RC1-bin-SNAPSHOT. (master at May. 9.2023)

## Minimized code

Macro.scala:
```Scala
package x

import scala.quoted.*
import scala.collection.*


object Macro {

    def myIndexWhere[A](arrOps: ArrayOps[A])(p: A=>Boolean, from:Int):Int =
      ???

    inline def changeIndexWhere[A](inline expr:A):A = ${
        changeIndexWhereImpl('expr)
    }

    def changeIndexWhereImpl[A:Type](expr:Expr[A])(using Quotes):Expr[A] = {
        import quotes.reflect.*
        val r0 = expr.asTerm 
        val checker = new TreeMap() {}
        val r = checker.transformTerm(r0)(Symbol.spliceOwner)
        r0.asExprOf[A]
    }

}
```

X.scala:
```Scala
package x

object X {

  def complileMe:Int = {
    Macro.changeIndexWhere{
      val arr = Array(1,2,3)
      val result = arr.indexWhere(_==2)
      result
    }
  }

}
```

## Output

```scala
info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 2 Scala sources to /Users/rssh/tests/dotty/fail-defparam/target/scala-3.3.1-RC1-bin-SNAPSHOT/classes ...
[error] -- Error: /Users/rssh/tests/dotty/fail-defparam/src/main/scala/x/X.scala:8:26 --
[error]  8 |    Macro.changeIndexWhere{
[error]    |    ^
[error]    |Malformed tree was found while expanding macro with -Xcheck-macros.
[error]    |               |The tree does not conform to the compiler's tree invariants.
[error]    |               |
[error]    |               |Macro was:
[error]    |               |scala.quoted.runtime.Expr.splice[scala.Int](((evidence$2: scala.quoted.Quotes) ?=> x.Macro.changeIndexWhereImpl[scala.Int](scala.quoted.runtime.Expr.quote[scala.Int]({
[error]    |  val arr: scala.Array[scala.Int] = scala.Array.apply(1, 2, 3)
[error]    |  val result: scala.Int = {
[error]    |    val $2$: scala.collection.ArrayOps[scala.Int] = scala.Predef.intArrayOps(arr)
[error]    |    $2$.indexWhere(((_$2: scala.Int) => _$2.==(2)), $2$.indexWhere$default$2)
[error]    |  }
[error]    |
[error]    |  (result: scala.Int)
[error]    |}).apply(using evidence$2))(scala.quoted.Type.of[scala.Int](evidence$2), evidence$2)))
[error]    |               |
[error]    |               |The macro returned:
[error]    |               |{
[error]    |  val arr: scala.Array[scala.Int] = scala.Array.apply(1, 2, 3)
[error]    |  val result: scala.Int = {
[error]    |    val $2$: scala.collection.ArrayOps[scala.Int] = scala.Predef.intArrayOps(arr)
[error]    |    $2$.indexWhere(((_$2: scala.Int) => _$2.==(2)), $2$.indexWhere$default$2)
[error]    |  }
[error]    |
[error]    |  (result: scala.Int)
[error]    |}
[error]    |               |
[error]    |               |Error:
[error]    |               |assertion failed: symbols differ for $2$.indexWhere$default$2
[error]    |was                 : method indexWhere$default$2
[error]    |alternatives by type:  of types 
[error]    |qualifier type      : ($2$ : scala.collection.ArrayOps[Int])
[error]    |tree type           : ($2$.indexWhere$default$2 : => Int @uncheckedVariance) of class class dotty.tools.dotc.core.Types$CachedTermRe
[error]    |               |
[error]    |stacktrace available when compiling with `-Ydebug`
[error]    |               |
[error]  9 |      val arr = Array(1,2,3)
[error] 10 |      val result = arr.indexWhere(_==2)
[error] 11 |      result
[error] 12 |    }
[error]    |----------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from Macro.scala:12
[error] 12 |    inline def changeIndexWhere[A](inline expr:A):A = ${
[error]    |                                                      ^
[error] 13 |        changeIndexWhereImpl('expr)
[error] 14 |    }
[error]     ----------------------------------------------------------------------------
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 5 s, completed 9 May 2023, 18:12:50
```

## Expectation

It should be compiled.

After a short investigation,  I have discovered that in TreeChecker, we seek for existence of SimpleName for indexWhere$default$2
when `decl.members` of the appropriate symbol contains DerivedName

**Comment by prolativ** [comment]
According to the bisect script:
```
Last good release: 3.3.0-RC1-bin-20230115-ed5b119-NIGHTLY
First bad release: 3.3.0-RC1-bin-20230116-d99d9bf-NIGHTLY

bisect found first bad commitPrevious HEAD position was 49df37931f Use tree checker for macro expanded trees
```
This seems to point to https://github.com/lampepfl/dotty/pull/16570

**Comment by rssh** [comment]
Here is a simpler reproducer with case class `copy` default getters:

**Macro.scala:**
```scala
import scala.quoted.*

object TestMacro:

  inline def identityTreeMap[T](inline body: T): T =
    ${ identityTreeMapImpl[T]('body) }

  def identityTreeMapImpl[T: Type](body: Expr[T])(using Quotes): Expr[T] =
    import quotes.reflect.*
    val mapped = new TreeMap {}.transformTerm(body.asTerm)(Symbol.spliceOwner)
    mapped.asExprOf[T]
```

**Test.scala:**
```scala
//> using scala 3.3.7
//> using scalacOption -Xcheck-macros

case class P(x: Int, y: Int)

@main def test(): Unit =
  val result = TestMacro.identityTreeMap {
    val p = P(3, 4)
    p.copy(y = 7)
  }
  assert(result == P(3, 7))
  println("Test passed!")
```

Error:
```
assertion failed: symbols differ for p.copy$default$1
was                 : method copy$default$1
alternatives by type:  of types 
qualifier type      : (p : P)
tree type           : (p.copy$default$1 : => Int @uncheckedVariance) of class class dotty.tools.dotc.core.Types$CachedTermRef
```

Still reproduces on 3.3.7. The identity `TreeMap` doesn't change anything in the tree, yet `-Xcheck-macros` rejects it.

**Comment by rssh** [comment]
Why it need SIP?   The question: are we allowed to get derived names via reflection?
But if we expose the TreeMap functionality, it should work.

**Comment by rssh** [comment]
Yet one interesting thing -- why the 'Regression' label is removed:  use TreeMao over any code, it's a functionality that worked before.  
Also looks like we have some problem with github notigications -- I have no received messages about status change.

**Comment by Gedochao** [comment]
> Why it need SIP? The question: are we allowed to get derived names via reflection? But if we expose the TreeMap functionality, it should work.

@hamzaremmal do you remember the context? I vaguely recall we considered a fix that would need SIP approval, but it seems we didn't put the context in a comment.

> Yet one interesting thing -- why the 'Regression' label is removed: use TreeMao over any code, it's a functionality that worked before.

I assume that would also cover why we no longer consider this a regression. The change (being a regression) was likely as a change (we fixed something, but broke this, and fixing both breaks some compat and/or requires a SIP).
Sorry for the confusion, we should've put the context in a comment this when the labels were changed.

I saw the solution PR, I'll make sure it gets looked at.

**Comment by jchyb** [comment]
I recall there being an idea at some point to add explicit TermNames and their subtypes to the api and stop using Strings in their place, which would need SIP (but I personally think it's too late for a change like that).

**Comment by hamzaremmal** [comment]
Yea, exactly what @jchyb said but we were thinking about `NameKind` (which is a change in the stdlib, not the language so it is not SIP).
