### ISSUE TITLE
Incompatible types when referencing type alias from java

### ISSUE THREAD

**Issue by liosedhel** [lampepfl/dotty#14298]
## Compiler version

Scala 3.1.0

## Minimized code

```scala
//1.scala
import java.time.LocalDate

case class Interval[ELEM_TYPE]() {
  def from: Option[ELEM_TYPE] = None
}

class GenerateTimeRange {
  type TimeRange = Interval[LocalDate]
  def timeRange(): TimeRange = ???
}
```

```java
//Reproduce.java
class Reproduce {

    public Reproduce() {
        dateMethod(new GenerateTimeRange().timeRange().from().get());
    }

    public void dateMethod(java.time.LocalDate localDate) {

    }
}
```

## Output

```scala
[error] Reproduce.java:5:1: incompatible types: java.lang.Object cannot be converted to java.time.LocalDate
[error] new GenerateTimeRange().timeRange().from().get()
```

## Expectation
Type should be resolved as `java.time.LocalDate`, works correctly in scala 2.13.7
