### ISSUE TITLE
"sbt dotr" does not automatically put scala-library on the classpath anymore

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3496]
This was recently broken (I guess by https://github.com/lampepfl/dotty/pull/3436):
```scala
> dotc tests/pos/HelloWorld.scala
> dotr HelloWorld
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Predef$
        at HelloWorld$.main(HelloWorld.scala:2)
        at HelloWorld.main(HelloWorld.scala)
Caused by: java.lang.ClassNotFoundException: scala.Predef$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
```

Workaround: doing `dotr -classpath /path/to/scala-library-2.12.4.jar` or using the `./bin/dotr` script.

**Comment by gosubpl** [comment]
Works now like a charm. Thanks @nicolasstucki !
