### ISSUE TITLE
Regression: new <type alias> should compile

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11781]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
object Ah {
  final case class Values[B, +A](a: A)

  trait Object[B] {
    final type Values[+A] = Ah.Values[B, A]
    object Values {
      def blah: Values[Unit] =
        new Values(())
    }
  }
}
```

## Output

```
-- Error: as.scala:8:12 --------------------------------------------------------
8 |        new Values(())
  |            ^^^^^^
  |            Object.this.Values is not a class type
-- Error: as.scala:8:19 --------------------------------------------------------
8 |        new Values(())
  |                   ^^
  |     too many arguments for constructor Object in class Object: (): Object
2 errors found
```

## Expectation

It should compile. It compiles with Scala 2.12 and 2.13.

**Comment by odersky** [comment]
Further minimization:
```scala
object Test:
  class C1[A](a: A)
  type D1[A] = C1[A]
  new D1(1)    // works

  class C2[B, A](a: A)
  type D2[A] = C2[Int, A]
  new D2(1)    // error
```
The problem arises if the type alias does not simply forward all its type parameters to the class.

**Comment by odersky** [comment]
As a workaround you can explicitly pass the type argument.
```scala
new D2[Int](1)   // works
```
