### ISSUE TITLE
Possibly incorrect unreacahble case error on Scala >= 3.3.1 (but not 3.3.0 or 3.2.2)

### ISSUE THREAD

**Issue by keynmol** [lampepfl/dotty#19863]
Warning, I was not able to minimise this so far. Can use some help.

This code: https://github.com/disneystreaming/weaver-test/blob/main/modules/framework/src-jvm/RunnerCompat.scala#L60-L62

Causes this error (see it on [CI](https://github.com/disneystreaming/weaver-test/actions/runs/8123929912/job/22204866485?pr=732#step:5:27)):

```
[error] -- [E030] Match case Unreachable Error: /Users/antonsviridov/projects/disneystreaming/weaver-test/modules/framework/src-jvm/RunnerCompat.scala:62:21
[error] 62 |    }.collect { case (taskDef, Some(suite)) => (taskDef, suite) }
[error]    |                     ^^^^^^^^^^^^^^^^^^^^^^
[error]    |                     Unreachable case
[error] one error found
[error] (framework3 / Compile / compileIncremental) Compilation failed
```

Which doesn't seem right, especially as I add the type annotations:

```scala
  val tasksAndSuites = taskDefs.toList.map { taskDef =>
    val t: (TaskDef, Option[suiteLoader.Loader]) = taskDef -> suiteLoader(taskDef)
    t
  }.collect { case (taskDef, Some(suite)) => (taskDef, suite) }
```

Project compiles fine on both 2.13 and 2.12.

Am I missing something here? 

## Compiler version

Errors start with 3.3.1, works fine on 3.3.0 and 3.2.2

## Minimized code

Unfortunately, so far I've not been able to minimise. Here's an attempt, but doesn't trigger the issue:

```scala
//> using scala 3.3.3

trait SuiteLoader[F[_]]:

  def apply(taskDef: TaskDef): Option[Loader]

  sealed trait Loader


class TaskDef

trait Compat[F[_]]:

  protected val suiteLoader: SuiteLoader[F]

  def bla(taskDefs: Array[TaskDef]) = 
    val tasksAndSuites = taskDefs.toList.map { taskDef =>
      taskDef -> suiteLoader(taskDef)
    }.collect { case (taskDef, Some(suite)) => (taskDef, suite) }

```

**Comment by prolativ** [comment]
Minimized:
```scala
trait Outer[F[_]]:
  def get(): Option[Inner]
  sealed trait Inner
  case class Impl(x: Int) extends Inner

trait User[F[_]]:
  val outer: Outer[F]
  def run() = List(1).map(_ -> outer.get()).collect { case (k, Some(v)) => (k, v) }
```
The warning is still there for scala 3.3.1, as reported
```scala
[warn] Unreachable case
[warn]   def run() = List(1).map(_ -> outer.get()).collect { case (k, Some(v)) => (k, v) }
[warn]                                                            ^^^^^^^^^^^^
```
But for 3.8.3 and 3.3.7 it's gone, so the issue seems already fixed to me
