### ISSUE TITLE
Transient failure: `pipelining-scala-java-basic` in `scripted-tests`

### ISSUE THREAD

**Issue by mbovel** [lampepfl/dotty#25797]
CI failing in `pipelining-scala-java-basic`:

```scala

[info] [error] -- [E006] Not Found Error: /tmp/sbt_8dc6354b/c/src/main/scala/c/C.scala:4:7 ----
[info] [error] 4 |import b.B
[info] [error]   |       ^
[info] [error]   |       Not found: b
[info] [error]   |
[info] [error]   | longer explanation available when compiling with `-explain`
[info] [warn] -- Warning: /tmp/sbt_8dc6354b/c/src/main/scala/c/C.scala:12:4 ------------------
[info] [warn] 12 |    assert(A.foo(1) == 2)
[info] [warn]    |    ^
[info] [warn]    |    Line is indented too far to the right, or a `{` is missing before:
[info] [warn]    |
[info] [warn]    |    assert(A.foo(0) == 1)
[info] [warn] one warning found
[info] [error] one error found
[info] [error] (c / Compile / compileIncremental) Compilation failed
[info] [error] Total time: 1 s, completed Apr 13, 2026, 5:10:53 PM
Error:  x pipelining/pipelining-scala-java-basic 
Error:   Cause of test exception: {line 1}  Command failed: c/run failed
```

_Originally posted by @mbovel in https://github.com/scala/scala3/issues/25776#issuecomment-4238296678_

**Comment by mbovel** [comment]
Not sure if this was fixed by #25776 in the end or not. Let's post here if we see CI failures on main after #25776.

**Comment by SolalPirelli** [comment]
failed in https://github.com/scala/scala3/actions/runs/24508000967/job/71631404946?pr=25826

**Comment by mbovel** [comment]
failed in https://github.com/scala/scala3/actions/runs/24577664889/job/71867102185#step:5:582

**Comment by mbovel** [comment]
I am working on this.

**Comment by som-snytt** [comment]
https://github.com/scala/scala3/actions/runs/24909801677/job/72948281468?pr=15635
