### ISSUE TITLE
type error member not found, when clearly the class has the member

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#18111]
for some reason the compiler is inventing some non existent `object caps`, and then reporting that member `cap` is not found on it, but it should be looking inside the `Glicko` class

## Compiler version

c62909009506171b03e092c4a391483b044d3b49 (somewhere between here and `3.3.2-RC1-bin-20230629-90c59bd-NIGHTLY`)

## Minimized code

this snippet from [lichess-org/lila](ccee0cf648cbaffa9c179403580e8cb6b78b459a) fails to compile with latest `main` but works with `3.3.2-RC1-bin-20230629-90c59bd-NIGHTLY`

```Scala
Glicko(
  rating = puzzleRating.rating
    .atMost(puzzle.glicko.rating + Glicko.maxRatingDelta)
    .atLeast(puzzle.glicko.rating - Glicko.maxRatingDelta),
  deviation = puzzleRating.ratingDeviation,
  volatility = puzzleRating.volatility
).cap
```

## Output

```scala
[lila] $ puzzle/compile
[info] compiling 29 Scala sources to /Users/jamie/workspace/lila/modules/puzzle/target/scala-3.3.2-RC1-bin-SNAPSHOT/classes ...
[error] -- Error: /Users/jamie/workspace/lila/modules/puzzle/src/main/PuzzleFinisher.scala:98:22 
[error] 98 |                    ).cap,
[error]    |                      ^
[error]    |                  object caps does not have a member field or getter cap
[error] one error found
[error] (puzzle / Compile / compileIncremental) Compilation failed
[error] Total time: 12 s, completed 30 Jun 2023, 18:15:08
```

## Expectation
this should work because clearly the class `Glicko` (defined in another module of `lila`) contains the method `cap`

**Comment by odersky** [comment]
Can we get a minimization of this? I
