### ISSUE TITLE
value xx is not a member of Array

### ISSUE THREAD

**Issue by cjdxhjj** [lampepfl/dotty#18591]
## Compiler version
3.3.1
If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

```Scala
class CreateBrandCommand(@BeanProperty val id: Long, @BeanProperty val name: String, @BeanProperty val logo: String, @BeanProperty val scope: Int, @BeanProperty val groupId: Long, @BeanProperty val orgId: Long, @BeanProperty val tertiary: Long, @BeanProperty val tertiaryType: Int, @BeanProperty val isEnable: Boolean, @BeanProperty val source: Int, @BeanProperty val creator: Long, @BeanProperty val description: String)

def addBrandBatch(brandList: Array[CreateBrandCommand])(using Trace, ExecutionContext): Task[ActionListResult[Brand]] = {
    ZIO.ifZIO(queryGateway.zioOne[Boolean](new IsOrgGroupMatchQuery(brandList.map(x => new OrgRecord(x.orgId, x.groupId)))))({
      ZIO.ifZIO(queryGateway.zioOne[Boolean](new CanCreateBrandsQuery(brandList.map(x => new BrandGroupName(x.groupId, x.name)))))({
        ZIO.ifZIO({
          val idList = brandList.map(_.id).filter(_ > 0).distinct
          if (idList.isEmpty) ZIO.succeed(false) else queryGateway.zioOne[Boolean](new IsAnyBrandExistQuery(idList))
        })(ZIO.succeed(ActionListResult(23003, List(), "部分品牌已存在")), commandGateway.zioMsg[ActionListResult[Brand]](new BatchCreateBrandCommand(brandList)))
      }, ZIO.succeed(ActionListResult(23002, List(), "品牌名称重复")))
    }, ZIO.succeed(ActionListResult(23001, List(), "集团与现有设置不匹配")))
  }
```

![image](https://github.com/lampepfl/dotty/assets/5616997/b875e7b6-06e7-4a65-89b2-5b1a61a11887)
![image](https://github.com/lampepfl/dotty/assets/5616997/7c06c488-3aa3-4e1b-8eda-8792c67b4fd0)

## Output
value orgId is not a member of Array[com.nxin.product.domain.brand.command.CreateBrandCommand]
```scala
// TODO add output here
```
why the complier treat x as Array[CreateBrandCommand] ?

**Comment by WojciechMazur** [comment]
It this problem only visible in the InteliJ or is it only present in normal compilation using sbt/mill or other build tool? 
InteliJ has it's own presentation compiler, which might be bugged - might show errors for code which would compile correctly when using actual Scala compiler.

**Comment by cjdxhjj** [comment]
i'm using gradle 8.3, when i use the gradle cli, it report the same error
![image](https://github.com/lampepfl/dotty/assets/5616997/f681b385-d5a5-4184-bb79-5bd81223f7f2)
![image](https://github.com/lampepfl/dotty/assets/5616997/ac73ed5b-b944-4a42-ab61-781e4f1860ed)
![image](https://github.com/lampepfl/dotty/assets/5616997/ca4aab0d-12c1-4633-8dc9-68de2e1b951d)
i'm wanted to upgrade from scala 2.13.11 to 3.3.1, but it alway report that error,

**Comment by cjdxhjj** [comment]
the issure appear half a year, i have tried scala 3.0, 3.1,3.2, jdk 11, jdk 17, zio 1.16, zio 2, i hava no idea to slove that problem, the error may cause by other mistake, but the error report is error

**Comment by cjdxhjj** [comment]
the project work fine on scala 2.13

**Comment by cjdxhjj** [comment]
my idea is 2023.2.2 and scala plugin is 2023.2.23

**Comment by He-Pin** [comment]
@cjdxhjj is it possible for you to minimalize it?

**Comment by cjdxhjj** [comment]
@He-Pin yes, i will try to provider an demo, but i'm not sure i could provider it

**Comment by cjdxhjj** [comment]
@He-Pin i can't provider an minimalize demo to repeat that complie error, i guess some other thing went wrong, but the compile report the wrong error
[scala3test.zip](https://github.com/lampepfl/dotty/files/12724212/scala3test.zip)

**Comment by cjdxhjj** [comment]
![image](https://github.com/lampepfl/dotty/assets/5616997/45432129-d770-4221-b3c0-d405b44f3bed)

**Comment by cjdxhjj** [comment]
@WojciechMazur there is any suggest, the project is write by scala 2.13 for three years age, i have upgrade the zio to 2.17, when i upgrade scala from 2 to 3, the error appear.

**Comment by He-Pin** [comment]
@cjdxhjj It would be better you have a simple code to demo this, you can post it with text block，better  with scala-cli.

你把这个问题搞个小文件复现下，这样大家都好看。比如 ```scala ...``` 这样的代码块儿。

**Comment by WojciechMazur** [comment]
@cjdxhjj Thank you for publishing the code, but it also is working fine on my machine. I really can't tell what might be happening here without the working reproducer leading to compilation error. I doesn't look like issue with the Scala typer, unless there is happening something very strange. You can try to check if there is no imports/package definitions that might shadow the `scala.Predef.Array` in some way or you can try to use this type directly in the failing method just to be sure.

**Comment by cjdxhjj** [comment]
@WojciechMazur the demo work fine, but my project build error, the error report point out the code error look like correct

**Comment by cjdxhjj** [comment]
@He-Pin @WojciechMazur i have copy my project and delete some module, the error report again
[scala3p.zip](https://github.com/lampepfl/dotty/files/12745891/scala3p.zip)

**Comment by SethTisue** [comment]
@cjdxhjj your repo has about 1000 lines of Scala in it. most compiler issues can be demonstrated in about 5–20 lines of code. it's rare for a minimal reproduction to require 50, let alone 1000

**Comment by cjdxhjj** [comment]
@SethTisue i will try to reduce some code, but i can't figure out what code cause the problem,

**Comment by cjdxhjj** [comment]
after delete some unused class.

[scala3p.zip](https://github.com/lampepfl/dotty/files/12747559/scala3p.zip)

**Comment by WojciechMazur** [comment]
What happened here is the implicit conversion, in this case it's `PreDef.futureWrapper`

The following code: 
```scala 
import com.example.domain.shared.PreDef.*

class Foo {
  def addBrandBatch2(brandList: Array[CreateBrandCommand]): ActionListResult[Brand] = {
     brandList.map(x =>x.orgId)
     ???
  }
}
```

is being converted to 
```Scala
class Foo() extends Object() {
    def addBrandBatch2(
      brandList: Array[com.example.domain.brand.command.CreateBrandCommand]):
      com.example.domain.shared.entity.ActionListResult[
        com.example.domain.brand.entity.Brand]
     =
      {
        com.example.domain.shared.PreDef.futureWrapper[
          Array[com.example.domain.brand.command.CreateBrandCommand]](brandList)
          .map[Any](
          {
            def $anonfun(
              x: Array[com.example.domain.brand.command.CreateBrandCommand]):
              Any = x.orgId
            closure($anonfun)
          }
        )(/* missing */summon[scala.concurrent.ExecutionContext])
        ???
      }
  } 
``` 

You should build your project with `-feature` flag to get more info about where implicit conversion is used in your code. 
To get the similar implicits semantics as in Scala 2 use `Conversion` type class instead 
```Scala 

  given futureWrapper[T]: Conversion[T, Future[T]] = Future.successful(_)
  // implicit def futureWrapper[T](data: => T): Future[T] = Future.successful(data)
``` 
With this change project compiles

**Comment by SethTisue** [comment]
if you have more questions like this in the future, https://users.scala-lang.org is a better place

**Comment by cjdxhjj** [comment]
thanks very much, @SethTisue @SethTisue
