### PR TITLE
Revert #24431

### LINKED ISSUE #25690: Type mismatch regression in inline call with macro-generated path-dependent type
Based on the OpenCB failures in 64 projects, regression is critical for the ZIO ecosystem

- alterationx10/opinionated-zio - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/alterationx10/opinionated-zio/builds/3.8.4-RC1%3A2026-04-02/logs)
- bilal-fazlani/csv-schema - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/bilal-fazlani/csv-schema/builds/3.8.4-RC1%3A2026-04-02/logs)
- bilal-fazlani/zio-ulid - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/bilal-fazlani/zio-ulid/builds/3.8.4-RC1%3A2026-04-02/logs)
- bitlap/rolls - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/bitlap/rolls/builds/3.8.4-RC1%3A2026-04-02/logs)
- bitlap/zio-pekko - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/bitlap/zio-pekko/builds/3.8.4-RC1%3A2026-04-02/logs)
- broij/zarrow - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/broij/zarrow/builds/3.8.4-RC1%3A2026-04-02/logs)
- carlos-verdes/zio-resource - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/carlos-verdes/zio-resource/builds/3.8.4-RC1%3A2026-04-02/logs)
- coralogix/zio-k8s - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/coralogix/zio-k8s/builds/3.8.4-RC1%3A2026-04-02/logs)
- gchudnov/swearwolf - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/gchudnov/swearwolf/builds/3.8.4-RC1%3A2026-04-02/logs)
- geirolz/secret - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/geirolz/secret/builds/3.8.4-RC1%3A2026-04-02/logs)
- guizmaii-opensource/scala-nimbus-jose-jwt - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/guizmaii-opensource/scala-nimbus-jose-jwt/builds/3.8.4-RC1%3A2026-04-02/logs)
- guymers/foobie - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/guymers/foobie/builds/3.8.4-RC1%3A2026-04-02/logs)
- gzoller/dynalens - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/gzoller/dynalens/builds/3.8.4-RC1%3A2026-04-02/logs)
- janlisse/zio-jwt-validator - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/janlisse/zio-jwt-validator/builds/3.8.4-RC1%3A2026-04-02/logs)
- kaizen-solutions/virgil - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/kaizen-solutions/virgil/builds/3.8.4-RC1%3A2026-04-02/logs)
- kaizen-solutions/zio-newrelic-events - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/kaizen-solutions/zio-newrelic-events/builds/3.8.4-RC1%3A2026-04-02/logs)
- kalin-rudnicki/harness - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/kalin-rudnicki/harness/builds/3.8.4-RC1%3A2026-04-02/logs)
- kalin-rudnicki/oxygen - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/kalin-rudnicki/oxygen/builds/3.8.4-RC1%3A2026-04-02/logs)
- kalin-rudnicki/slyce-zio - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/kalin-rudnicki/slyce-zio/builds/3.8.4-RC1%3A2026-04-02/logs)
- kirill5k/mongo4cats - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/kirill5k/mongo4cats/builds/3.8.4-RC1%3A2026-04-02/logs)
- kitlangton/neotype - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/kitlangton/neotype/builds/3.8.4-RC1%3A2026-04-02/logs)
- kitlangton/stubby - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/kitlangton/stubby/builds/3.8.4-RC1%3A2026-04-02/logs)
- lambdaworks/zio-elasticsearch - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/lambdaworks/zio-elasticsearch/builds/3.8.4-RC1%3A2026-04-02/logs)
- laserdisc-io/tamer - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/laserdisc-io/tamer/builds/3.8.4-RC1%3A2026-04-02/logs)
- laserdisc-io/zio-oci-objectstorage - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/laserdisc-io/zio-oci-objectstorage/builds/3.8.4-RC1%3A2026-04-02/logs)
- makiftutuncu/e - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/makiftutuncu/e/builds/3.8.4-RC1%3A2026-04-02/logs)
- narma/tranzactio - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/narma/tranzactio/builds/3.8.4-RC1%3A2026-04-02/logs)
- nebula-contrib/testcontainers-nebula - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/nebula-contrib/testcontainers-nebula/builds/3.8.4-RC1%3A2026-04-02/logs)
- palanga/parana - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/palanga/parana/builds/3.8.4-RC1%3A2026-04-02/logs)
- pidoveproject/scala-showdown-api - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/pidoveproject/scala-showdown-api/builds/3.8.4-RC1%3A2026-04-02/logs)
- pjfanning/zio-metrics-micrometer - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/pjfanning/zio-metrics-micrometer/builds/3.8.4-RC1%3A2026-04-02/logs)
- pme123/orchescala - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/pme123/orchescala/builds/3.8.4-RC1%3A2026-04-02/logs)
- scalamock/scalamock - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/scalamock/scalamock/builds/3.8.4-RC1%3A2026-04-02/logs)
- senia-psm/zio-test-akka-http - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/senia-psm/zio-test-akka-http/builds/3.8.4-RC1%3A2026-04-02/logs)
- stuartapp/zcaffeine - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/stuartapp/zcaffeine/builds/3.8.4-RC1%3A2026-04-02/logs)
- swaldman/latest - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/swaldman/latest/builds/3.8.4-RC1%3A2026-04-02/logs)
- tharwaninitin/cron4zio - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/tharwaninitin/cron4zio/builds/3.8.4-RC1%3A2026-04-02/logs)
- tharwaninitin/etlflow - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/tharwaninitin/etlflow/builds/3.8.4-RC1%3A2026-04-02/logs)
- tharwaninitin/gcp4zio - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/tharwaninitin/gcp4zio/builds/3.8.4-RC1%3A2026-04-02/logs)
- vigoo/clipp - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/vigoo/clipp/builds/3.8.4-RC1%3A2026-04-02/logs)
- vigoo/desert - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/vigoo/desert/builds/3.8.4-RC1%3A2026-04-02/logs)
- vitaliihonta/zio-temporal - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/vitaliihonta/zio-temporal/builds/3.8.4-RC1%3A2026-04-02/logs)
- yurikpanic/zio-postgres - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/yurikpanic/zio-postgres/builds/3.8.4-RC1%3A2026-04-02/logs)
- zeal18/zio-mongodb - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zeal18/zio-mongodb/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio-archive/interop-guava - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio-archive/interop-guava/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio-archive/interop-monix - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio-archive/interop-monix/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio-archive/interop-reactive-streams - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio-archive/interop-reactive-streams/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio-archive/zio-connect - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio-archive/zio-connect/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio-archive/zio-metrics-legacy - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio-archive/zio-metrics-legacy/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio-archive/zio-nio - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio-archive/zio-nio/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio-archive/zio-optics - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio-archive/zio-optics/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/interop-cats - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/interop-cats/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-blocks - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-blocks/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-cli - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-cli/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-config - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-config/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-direct - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-direct/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-dynamodb - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-dynamodb/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-json - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-json/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-prelude - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-prelude/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-process - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-process/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-profiling - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-profiling/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-query - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-query/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-rocksdb - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-rocksdb/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-s3 - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-s3/builds/3.8.4-RC1%3A2026-04-02/logs)

## Compiler version

Works in 3.8.3 
Fails in 3.8.4-RC1 

Last good release: 3.8.4-RC1-bin-20260331-724e9c3-NIGHTLY
First bad release: 3.8.4-RC1-bin-20260401-fc4cd08-NIGHTLY

<del>Bisect narrowed it to one of #25638 commits</del> 

Bisect points to https://github.com/scala/scala3/commit/d8c87a768ae3a3cf4b720133781f4962e6a9874b / https://github.com/scala/scala3/pull/24431

## Minimized code

This is dependency-free, but it needs two files because a same-file version hits cyclic macro dependencies.

```scala
// repro-macro.scala
import scala.quoted.*

object Tracer:
  trait Api:
    type Type

  val instance: Api = new Api { type Type = String }
  type Trace = instance.Type

  inline def autoTrace: Trace = ${ autoTraceImpl }

  def autoTraceImpl(using Quotes): Expr[Trace] =
    import quotes.reflect.*
    Typed(Literal(StringConstant("loc")), TypeTree.of[Trace]).asExprOf[Trace]

```

``` scala
// repro.scala
//> using file repro-macro.scala

def succeed[A](a: A)(trace: Tracer.Trace): A = a
inline def uio[A](a: A): A = succeed(a)(Tracer.autoTrace)

val u = uio(42) // error
```

## Output

```sh
> scala compile repro.scala -S 3.8.rc
Compiling project (Scala 3.8.4-RC1, JVM (21))
[error] ./repro.scala:6:9
[error] Found:    ("loc" : String)
[error] Required: Tracer.Trace
[error] val u = uio(42)
[error]         ^^^^^^^
Error compiling project (Scala 3.8.4-RC1, JVM (21))
```

## Expectation

Should compile without turning the macro-produced Trace argument into String at the inlined call site.

### LINKED ISSUE #25692: Regression in inline macro-generated using arguments with path-dependent types
Similar to #25690 

Based on OpenCB failures in 27 projects - critical regression for ZIO ecosystem 
- augustnagro/magnum - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/augustnagro/magnum/builds/3.8.4-RC1%3A2026-04-02/logs)
- bilal-fazlani/zio-maelstrom - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/bilal-fazlani/zio-maelstrom/builds/3.8.4-RC1%3A2026-04-02/logs)
- dacr/code-examples-manager - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/dacr/code-examples-manager/builds/3.8.4-RC1%3A2026-04-02/logs)
- dacr/zio-lmdb - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/dacr/zio-lmdb/builds/3.8.4-RC1%3A2026-04-02/logs)
- devsisters/shardcake - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/devsisters/shardcake/builds/3.8.4-RC1%3A2026-04-02/logs)
- durban/choam - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/durban/choam/builds/3.8.4-RC1%3A2026-04-02/logs)
- ghostdogpr/proteus - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/ghostdogpr/proteus/builds/3.8.4-RC1%3A2026-04-02/logs)
- grouzen/zio-apache-arrow - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/grouzen/zio-apache-arrow/builds/3.8.4-RC1%3A2026-04-02/logs)
- guizmaii-opensource/sbt-datadog - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/guizmaii-opensource/sbt-datadog/builds/3.8.4-RC1%3A2026-04-02/logs)
- jamesward/zio-mavencentral - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/jamesward/zio-mavencentral/builds/3.8.4-RC1%3A2026-04-02/logs)
- kaizen-solutions/trace4cats-zio-extras - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/kaizen-solutions/trace4cats-zio-extras/builds/3.8.4-RC1%3A2026-04-02/logs)
- kijuky/confluence-for-scala - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/kijuky/confluence-for-scala/builds/3.8.4-RC1%3A2026-04-02/logs)
- natural-transformation/korolev - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/natural-transformation/korolev/builds/3.8.4-RC1%3A2026-04-02/logs)
- natural-transformation/spoonbill - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/natural-transformation/spoonbill/builds/3.8.4-RC1%3A2026-04-02/logs)
- nebula-contrib/nebula4scala - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/nebula-contrib/nebula4scala/builds/3.8.4-RC1%3A2026-04-02/logs)
- ollls/zio-quartz-h2 - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/ollls/zio-quartz-h2/builds/3.8.4-RC1%3A2026-04-02/logs)
- palanga/picazio - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/palanga/picazio/builds/3.8.4-RC1%3A2026-04-02/logs)
- swaldman/feedletter - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/swaldman/feedletter/builds/3.8.4-RC1%3A2026-04-02/logs)
- tofu-tf/tofu - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/tofu-tf/tofu/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-kafka - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-kafka/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-lambda - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-lambda/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-logging - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-logging/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-metrics-connectors - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-metrics-connectors/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-redis - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-redis/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-sqs - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-sqs/builds/3.8.4-RC1%3A2026-04-02/logs)
- zio/zio-telemetry - [logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/zio/zio-telemetry/builds/3.8.4-RC1%3A2026-04-02/logs)

## Compiler version

Works in 3.8.3, fails in 3.8.4-RC1 

Last good release: 3.8.4-RC1-bin-20260331-724e9c3-NIGHTLY
First bad release: 3.8.4-RC1-bin-20260401-fc4cd08-NIGHTLY

Bisect points to https://github.com/scala/scala3/commit/d8c87a768ae3a3cf4b720133781f4962e6a9874b / https://github.com/scala/scala3/pull/24431

## Minimized code

```scala
// repro.scala
//> using file repro_macros.scala

import zio.*

val provided = broken
```
```scala
// repro_macros.scala
package zio

import zio.internal.stacktracer.Tracer

type Trace = Tracer.instance.Type & Tracer.Traced

final class ZLayer[-R, +E, +A]
object ZLayer:
  def environment[A](using Trace): ZLayer[A, Nothing, A] =
    new ZLayer[A, Nothing, A]

inline def broken: ZLayer[Any, Nothing, Any] =
  ${ zio.internal.macros.LayerMacros.brokenImpl }

package internal.stacktracer:
  import scala.quoted.*

  object Tracer:
    type Traced = Any
    inline given autoTrace: Tracer.instance.Type =
      ${ Macros.autoTraceImpl }
    val instance: Tracer = new Tracer:
      type Type = String

  sealed trait Tracer:
    type Type <: AnyRef

  object Macros:
    def autoTraceImpl(using Quotes): Expr[Tracer.instance.Type] =
      Expr("trace").asInstanceOf[Expr[Tracer.instance.Type]]

package internal.macros:
  import zio.*
  import scala.compiletime.*
  import scala.quoted.*

  object LayerMacros:
    def brokenImpl(using Quotes): Expr[ZLayer[Any, Nothing, Any]] =
      '{
        val trace = summonInline[Trace]
        ZLayer.environment[Any](using trace)
      }
```

## Output

```sh
>  scala-cli compile repro.scala -S 3.8.4-RC1-bin-20260401-fc4cd08-NIGHTLY --server=false

-- [E007] Type Mismatch Error: repro.scala:5:15
5 |val provided = broken
  |               ^^^^^^
  |           Found:    ("trace" : String)
  |           Required: zio.internal.stacktracer.Tracer.instance.Type & Any
  |----------------------------------------------------------------------------
  |Inline stack trace
  |This location contains code that was inlined from repro_support.scala:22
42 |        val trace = summonInline[Trace]
43 |        ZLayer.environment[Any](using trace)
```

## Expectation

Should compile successfully, as it does on 3.8.4-RC1-bin-20260331-724e9c3-NIGHTLY.

### LINKED ISSUE #25697: Regression in `leviysoft/oolong`: `MatchError` in quoted `Pattern.compile` flag arguments
Based on the OpenCB failures in:
- leviysoft/oolong - [build logs](https://scala3.westeurope.cloudapp.azure.com/dashboard/projects/leviysoft/oolong/builds/3.8.4-RC1%3A2026-04-02/logs?severity=error)

## Compiler version

Observed stable boundary: `3.8.3` compiles, `3.8.4-RC1` fails.

Last good release: 3.8.4-RC1-bin-20260331-724e9c3-NIGHTLY
First bad release: 3.8.4-RC1-bin-20260401-fc4cd08-NIGHTLY
 
Bisect points to d8c87a768ae3a3cf4b720133781f4962e6a9874b / #24431 

Related to #25692 , #25690 

## Minimized code

`test.scala`
```scala
//> using file test-macro.scala
import java.util.regex.Pattern

@main def Test(): Unit =
  inline def regex   = "SomeString"
  inline def pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE | Pattern.COMMENTS)

  TinyMacro.inspect(pattern.matcher("value").matches())
```

`test-macro.scala`
```scala
import java.util.regex.Pattern
import scala.annotation.tailrec
import scala.quoted.*

object TinyMacro:
  inline def inspect(inline expr: Boolean): Unit = ${ inspectImpl('expr) }

  def inspectImpl(expr: Expr[Boolean])(using Quotes): Expr[Unit] =
    import quotes.reflect.*

    def flag(name: String): Int = name match
      case "CASE_INSENSITIVE" => Pattern.CASE_INSENSITIVE
      case "COMMENTS"         => Pattern.COMMENTS

    @tailrec
    def strip(term: Term): Term = term match
      case Inlined(_, _, inner) => strip(inner)
      case Typed(inner, _)      => strip(inner)
      case _                    => term

    def parseFlags(term: Term): List[Int] =
      @tailrec
      def loop(term: Term, acc: List[Int]): List[Int] = strip(term) match
        case Apply(term, List(Select(Ident("Pattern"), name))) => loop(term, acc :+ flag(name))
        case Select(term, "|")                                 => loop(term, acc)
        case Select(Ident("Pattern"), name)                    => acc :+ flag(name)

      loop(term, Nil)

    given FromExpr[Pattern] with
      def unapply(expr: Expr[Pattern])(using Quotes): Option[Pattern] =
        strip(expr.asTerm) match
          case Apply(
                Select(_, "compile"),
                List(Inlined(_, _, Typed(Literal(StringConstant(pattern)), _)), Literal(IntConstant(flags)))
              ) =>
            Some(Pattern.compile(pattern, flags))
          case Apply(
                Select(_, "compile"),
                List(Literal(StringConstant(pattern)), flagsTerm)
              ) =>
            Some(Pattern.compile(pattern, parseFlags(flagsTerm).reduce(_ | _)))
          case _ => None

    expr match
      case '{ ($pattern: Pattern).matcher(${ _: Expr[String] }).matches() } =>
        pattern.valueOrAbort
        '{ () }
      case _ =>
        report.errorAndAbort(expr.show)
```

## Output

```sh
scala-cli compile test.scala --scala 3.8.4-RC1 --server=false

-- Error: test.scala:8:19 ------------------------------------------------------
8 |  TinyMacro.inspect(pattern.matcher("value").matches())
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | Exception occurred while executing macro expansion.
  | scala.MatchError: Literal(Constant(6)) (of class dotty.tools.dotc.ast.Trees$Literal)
  |   at TinyMacro$.loop$1(test-macro.scala:26)
  |   at TinyMacro$.TinyMacro$$$_$parseFlags$1(test-macro.scala:28)
  |   at TinyMacro$given_FromExpr_Pattern$2$.unapply(test-macro.scala:42)
  |   at scala.quoted.runtime.impl.QuotesImpl.valueOrAbort(QuotesImpl.scala:64)
  |   at TinyMacro$.inspectImpl(test-macro.scala:47)

1 error found
Compilation failed
```

## Expectation

Should compile without throwing `scala.MatchError` during macro expansion, as it does in `3.8.3`.

### PR DESCRIPTION
**Pull request by mbovel**
Given the wide scope of the regression introduced by #24431, I think it's best to revert for now, until I figure out how to fix it.

Closes #25690, closes #25692 and closes #25697.

### CODE REVIEW

**Comment by mbovel** [comment]
Thanks for documenting these regressions Wojciech and sorry for the trouble!

**Comment by WojciechMazur** [comment]
If possible let's add the snippets the 3 PRs as future regression tests

**Comment by mbovel** [comment]
Regression test for #25690 doesn't pass with `-Xcheck-macros`:

```
completed (2/3, 0 failed, 1s)-- Error: tests/pos-macros/i25690/Test_2.scala:4:11 --------------------------------------------------------------------
 4 |val u = uio(42) // errortrapped / Test / testOnly 5s
   |        ^^^^^^^
   |Malformed tree was found while expanding macro with -Xcheck-macros.
   |The tree does not conform to the compiler's tree invariants.
   |
   |Macro was:
   |scala.quoted.runtime.Expr.splice[Tracer.instance.Type](((contextual$1: scala.quoted.Quotes) ?=> Tracer.autoTraceImpl(contextual$1)))
   |
   |The macro returned:
   |("loc": Tracer.instance.Type)
   |
   |Error:
   |assertion failed: Type Mismatch (while checking adapt):
   |Found:    ("loc" : String)
   |Required: Tracer.instance.Type
   |I tried to show that
   |  ("loc" : String)
   |conforms to
   |  Tracer.instance.Type
   |but none of the attempts shown below succeeded:
   |
   |  ==> ("loc" : String)  <:  Tracer.instance.Type
   |    ==> ("loc" : String)  <:  Nothing
   |      ==> String  <:  Nothing  = false
   |    ==> String  <:  Tracer.instance.Type
   |      ==> String  <:  Nothing  = false
   |
   |The tests were made under the empty constraint
   |tree = "loc" Literal
   |
   |stacktrace available when compiling with `-Ydebug`
   |--------------------------------------------------------------------------------------------------------------------
   |Inline stack trace
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from Macro_1.scala:10
10 |  inline def autoTrace: Trace = ${ autoTraceImpl }
   |                                ^^^^^^^^^^^^^^^^^^
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from Macro_1.scala:10
 2 |inline def uio[A](a: A): A = succeed(a)(Tracer.autoTrace)
   |                                        ^^^^^^^^^^^^^^^^
    --------------------------------------------------------------------------------------------------------------------
```

Looking at it now.
