### ISSUE TITLE
`this.synchronized` block prevents @tailrec check from passing

### ISSUE THREAD

**Issue by liosedhel** [lampepfl/dotty#14308]
## Compiler version

scala 3.1.2-RC1-bin-20220118-9e14f5f-NIGHTLY

## Minimized code

```Scala
import scala.annotation.tailrec

class XD {
  @tailrec
  private def create(x: Int): Unit = {
    this.synchronized {
      if (x == 0) ()
      else create(x - 1)
    }
  }
}
```

## Output

```scala
[error] -- Error: TailrecProblem.scala:8:17 
[error] 8 |      else create(x - 1)
[error]   |           ^^^^^^^^^^^^^
[error]   |           Cannot rewrite recursive call: it is not in tail position
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## Expectation

It compiles with scala 2.13.7, it does not with 3.1.2-RC1-bin-20220118-9e14f5f-NIGHTLY. Is it a regression or a change in behaviour and `synchronized` blocks tailrec invocation?

**Comment by odersky** [comment]
@mbovel Since you looked at tailrec last, would this be a good issue to tackle? Essentially, if a @tailrec function
has an outermost synchronized block, we should do the tailrec transformation inside this block. 

Alternatively, this could also be a spree topic, since it requires only understanding one part of the compiler. But it will require some effort.

**Comment by mbovel** [comment]
Is this really something we want to support in the compiler? Is this such a common pattern?

Why not simply writing the given example using a helper function?

```scala
private def create(x: Int): Unit = {
  @tailrec
  def loop(x: Int): Unit = {
    if (x == 0) ()
    else loop(x - 1)
  }
  this.synchronized {
      loop(x)
  }
}
```

**Comment by KacperFKorban** [comment]
This issue is not a bug in `TailRec`.
This was supported in Scala 2 as a side effect of optimization. Related issue: https://github.com/lampepfl/dotty/issues/5933

I played a bit with porting this transformation to dotty. Though I'm not quite sure which phase it should be in, since there is a problem of detecting if a function will become static.
@odersky @mbovel
