### ISSUE TITLE
plokhotnyuk/jsoniter-scala v2.17.9

### ISSUE THREAD

**Issue by dwijnand** [lampepfl/dotty#16342]
```scala
[error] -- [E008] Not Found Error: /home/jenkins/agent/workspace/buildCommunityProject/repo/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala:38:71 
[error] 38 |    def unapply(userId: Opaque): Option[String] = Option(userId).map(_.value)
[error]    |                                                                     ^^^^^^^
[error]    |value value is not a member of com.github.plokhotnyuk.jsoniter_scala.macros.UserId2.Tag
[error] -- [E008] Not Found Error: /home/jenkins/agent/workspace/buildCommunityProject/repo/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala:58:70 
[error] 58 |    def unapply(orderId: Opaque): Option[Int] = Option(orderId).map(_.value)
[error]    |                                                                    ^^^^^^^
[error]    |value value is not a member of com.github.plokhotnyuk.jsoniter_scala.macros.OrderId2.Tag
[error] two errors found
[error] (jsoniter-scala-macrosJVM / Test / compileIncremental) Compilation failed
```

```scala
  type Opaque = Base with Tag

  type Base = Any {
    type Hack
  }

  trait Tag

  object Opaque {
    def apply(value: String): Opaque = value.asInstanceOf[Opaque]

    def unapply(userId: Opaque): Option[String] = Option(userId).map(_.value)
  }

  final implicit class Ops(private val userId: Opaque) extends AnyVal {
    def value: String = userId.asInstanceOf[String]
  }
```

**Comment by odersky** [comment]
I verified that this is in fact caused by #15642. Need to dig deeper why.
