### ISSUE TITLE
Regression: Cannot extend non-static Java inner interface

### ISSUE THREAD

**Issue by akozich** [lampepfl/dotty#25722]
I use sentry library `io.sentry:sentry-logback:8.37.1` which has `SentryOptions` class with `BeforeSendCallback` interface. If I implement the interface in Scala I get the following errors on compilation

```
[error] no member new Any . <init>
[error] value <none>: <notype> does not take parameters
[error] Internal error in the incremental compiler while compiling .../server/src/main/util/CustomCallback.scala: Unhandled type <error unspecified error> of class class dotty.tools.dotc.core.Types$UnspecifiedErrorType$
[error] three errors found
[error] (server / Compile / compileIncremental) Compilation failed
[error] Total time: 7 s, completed Apr 7, 2026, 7:32:10 PM
```

This code works fine on 3.8.1

## Compiler version

3.8.3

## Minimized code

java class

```java
public class SentryOptions {
  ...
  /** The BeforeSend callback */
  public interface BeforeSendCallback {

    /**
     * Mutates or drop an event before being sent
     *
     * @param event the event
     * @param hint the hints
     * @return the original event or the mutated event or null if event was dropped
     */
    @Nullable
    SentryEvent execute(@NotNull SentryEvent event, @NotNull Hint hint);
  }
  ...
}
```

Scala class

```scala
class CustomCallback extends SentryOptions.BeforeSendCallback {

  override def execute(event: SentryEvent, hint: Hint): SentryEvent = event
}
```

## Expectation

Scala class `CustomCallback` should inherit the Java interface.

**Comment by Gedochao** [comment]
The `...` in the example suggest it's not actually minimized here.
I can't seem to reproduce, despite my best efforts.
I also had to guess at the imports and where the `@Nullable`/`@NotNull` annotations could be coming from.
The following does compile:

Java class:
```java
//> using dep io.sentry:sentry-logback:8.37.1
//> using dep org.jetbrains:annotations:26.0.2-1
import io.sentry.Hint;
import io.sentry.SentryEvent;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public class SentryOptions {
  public interface BeforeSendCallback {
    @Nullable
    SentryEvent execute(@NotNull SentryEvent event, @NotNull Hint hint);
  }
}
```

Scala class:
```scala
import io.sentry.SentryEvent
import io.sentry.Hint
class CustomCallback extends SentryOptions.BeforeSendCallback {
  override def execute(event: SentryEvent, hint: Hint): SentryEvent = event
}
```

as well as without the annotations:

```java
//> using dep io.sentry:sentry-logback:8.37.1
import io.sentry.Hint;
import io.sentry.SentryEvent;
public class SentryOptions {
  public interface BeforeSendCallback {
    SentryEvent execute(SentryEvent event, Hint hint);
  }
}
```

@akozich Please include the full contained reproduction.

**Comment by akozich** [comment]
Here's the link to my repo, where I can reproduce this issue https://github.com/akozich/scala-3.8.3-regression

**Comment by akozich** [comment]
Here's the output with `-Vprint:typer`

```
[info] compiling 2 Scala sources to /Users/aliaksei/work/projects/sentry-client-app/target/scala-3.8.3/classes ...
[info] [[syntax trees at end of                     typer]] // /Users/aliaksei/work/projects/sentry-client-app/src/main/scala/model/UserId.scala
[info] package model {
[info]   import java.util.UUID
[info]   final lazy module val UserId$package: model.UserId$package =
[info]     new model.UserId$package()
[info]   final module class UserId$package() extends Object() {
[info]     this: model.UserId$package.type =>
[info]     type UserId = java.util.UUID
[info]     final lazy module val UserId: model.UserId = new model.UserId()
[info]     final module class UserId() extends Object() { this: model.UserId.type =>
[info]       def apply(userId: String): model.UserId =
[info]         java.util.UUID.fromString(userId)
[info]       def randomUserId(): model.UserId = java.util.UUID.randomUUID()
[info]     }
[info]   }
[info] }
[info] [[syntax trees at end of                     typer]] // /Users/aliaksei/work/projects/sentry-client-app/src/main/scala/util/SentryBeforeSendCallback.scala
[info] package util {
[info]   import io.sentry.Hint
[info]   import io.sentry.HubAdapter
[info]   import io.sentry.SentryEvent
[info]   import io.sentry.SentryOptions
[info]   import org.slf4j.MDC
[info]   import scala.jdk.CollectionConverters.*
[info]   class CompositeBeforeSendCallback(
[info]     callbacks: Seq[util.SentryBeforeSendCallback] @Repeated) extends Object(),
[info]     util.SentryBeforeSendCallback {
[info]     private[this] val callbacks: Seq[util.SentryBeforeSendCallback] @Repeated
[info]     override def execute(event: io.sentry.SentryEvent, hint: io.sentry.Hint):
[info]       io.sentry.SentryEvent | Null =
[info]       {
[info]         CompositeBeforeSendCallback.this.callbacks.foldLeft[
[info]           io.sentry.SentryEvent](event)((x$1: io.sentry.SentryEvent,
[info]           x$2: util.SentryBeforeSendCallback) =>
[info]           Tuple2.apply[io.sentry.SentryEvent, util.SentryBeforeSendCallback](
[info]             x$1, x$2) match
[info]             {
[info]               case
[info]                 Tuple2.unapply[io.sentry.SentryEvent,
[info]                   io.sentry.SentryOptions.BeforeSendCallback](acc @ _,
[info]                   callback @ _)
[info]                =>
[info]                 callback.execute(acc, hint)
[info]             }
[info]         )
[info]       }
[info]   }
[info]   class MDCBeforeSendCallback(tagsProvider: () => Set[String]) extends
[info]     Object(), util.SentryBeforeSendCallback {
[info]     private val tagsProvider: () => Set[String]
[info]     override def execute(event: io.sentry.SentryEvent, hint: io.sentry.Hint):
[info]       io.sentry.SentryEvent | Null =
[info]       {
[info]         val contextMap: scala.collection.Map[? <: String | Nothing, String] =
[info]           Option.apply[scala.collection.mutable.Map[String, String]](
[info]             scala.jdk.CollectionConverters.MapHasAsScala[String, String](
[info]               org.slf4j.MDC.getCopyOfContextMap()).asScala
[info]           ).getOrElse[
[info]
[info]               scala.collection.Map[? >: String & Nothing <: String | Nothing,
[info]                 String | Nothing]
[info]
[info]           ](Map.empty[Nothing, Nothing])
[info]         val contextTags: Set[String] =
[info]           MDCBeforeSendCallback.this.tagsProvider.apply()
[info]         val $2$:
[info]           (scala.collection.Map[? <: String, String],
[info]             scala.collection.Map[? <: String, String])
[info]          =
[info]           contextMap.filter((x$1: (String | Nothing, String)) =>
[info]             {
[info]               val v: Any = x$1._2
[info]               v != null
[info]             }
[info]           ).partition((x$1: (String, String)) =>
[info]             x$1 match
[info]               {
[info]                 case Tuple2.unapply[String, String](key @ _, _) =>
[info]                   contextTags.contains(key)
[info]               }
[info]           ):
[info]
[info]               (scala.collection.Map[? <: String, String],
[info]                 scala.collection.Map[? <: String, String]) @RuntimeChecked
[info]
[info]            match
[info]             {
[info]               case
[info]                 $1$ @
[info]                   Tuple2.unapply[scala.collection.Map[? <: String, String],
[info]                     scala.collection.Map[? <: String, String]](_, _)
[info]                =>
[info]                 $1$:
[info]                   (scala.collection.Map[? <: String, String],
[info]                     scala.collection.Map[? <: String, String])
[info]             }
[info]         val tags: scala.collection.Map[? <: String, String] = $2$._1
[info]         val mdcProperties: scala.collection.Map[? <: String, String] = $2$._2
[info]         tags.foreach[Unit](
[info]           (x$0: (String)?, x$1: (String)?) => event.setTag(x$0, x$1).tupled)
[info]         if
[info]           mdcProperties.nonEmpty &&
[info]             event.getContexts().get(util.MdcCtxKey) == null
[info]          then
[info]           {
[info]             {
[info]               event.getContexts().put(util.MdcCtxKey,
[info]                 scala.jdk.CollectionConverters.MapHasAsJava[?1.CAP, String](
[info]                   mdcProperties.$asInstanceOf[
[info]                     scala.collection.Map[?1.CAP, String]]
[info]                 ).asJava
[info]               )
[info]               ()
[info]             }
[info]           }
[info]          else ()
[info]         event
[info]       }
[info]   }
[info]   final lazy module val MDCBeforeSendCallback: util.MDCBeforeSendCallback =
[info]     new util.MDCBeforeSendCallback()
[info]   final module class MDCBeforeSendCallback() extends AnyRef() {
[info]     this: util.MDCBeforeSendCallback.type =>
[info]     def $lessinit$greater$default$1: (() => Set[String]) @uncheckedVariance =
[info]       util.getContextTags
[info]   }
[info]   class MDCExcludeKeysBeforeSendCallback(excludeKeys: Set[String]) extends
[info]     Object(), util.SentryBeforeSendCallback {
[info]     private val excludeKeys: Set[String]
[info]     override def execute(event: io.sentry.SentryEvent, hint: io.sentry.Hint):
[info]       io.sentry.SentryEvent | Null =
[info]       {
[info]         val mdcContext: Option[java.util.Map[String, String]] =
[info]           Option.apply[java.util.Map[String, String]](
[info]             event.getContexts().get(util.MdcCtxKey).asInstanceOf[
[info]               java.util.Map[String, String]]
[info]           )
[info]         mdcContext.foreach[(Object)?]((ctx: java.util.Map[String, String]) =>
[info]           {
[info]             val filteredCtx: java.util.Map[String, String] =
[info]               scala.jdk.CollectionConverters.MutableMapHasAsJava[String, String]
[info]                 (
[info]                 scala.jdk.CollectionConverters.MapHasAsScala[String, String](ctx
[info]                   ).asScala.filterNot((x$1: (String, String)) =>
[info]                   x$1 match
[info]                     {
[info]                       case Tuple2.unapply[String, String](key @ _, _) =>
[info]                         MDCExcludeKeysBeforeSendCallback.this.excludeKeys.
[info]                           contains(key)
[info]                     }
[info]                 )
[info]               ).asJava
[info]             event.getContexts().put(util.MdcCtxKey, filteredCtx)
[info]           }
[info]         )
[info]         event
[info]       }
[info]   }
[info]   final lazy module val SentryBeforeSendCallback$package:
[info]     util.SentryBeforeSendCallback$package =
[info]     new util.SentryBeforeSendCallback$package()
[info]   final module class SentryBeforeSendCallback$package() extends Object() {
[info]     this: util.SentryBeforeSendCallback$package.type =>
[info]     type SentryBeforeSendCallback = io.sentry.SentryOptions.BeforeSendCallback
[info]     private[util] val MdcCtxKey: String = "MDC"
[info]     private[util] def getContextTags: () => Set[String] = () =>
[info]       scala.jdk.CollectionConverters.ListHasAsScala[String](
[info]         io.sentry.HubAdapter.getInstance().getOptions().getContextTags()).
[info]         asScala.toSet[String]
[info]   }
[info] }
[error] no member new Any . <init>
[error] value <none>: <notype> does not take parameters
[error] Internal error in the incremental compiler while compiling /Users/aliaksei/work/projects/sentry-client-app/src/main/scala/util/SentryBeforeSendCallback.scala: Unhandled type <error unspecified error> of class class dotty.tools.dotc.core.Types$UnspecifiedErrorType$
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed
```

**Comment by Gedochao** [comment]
Yep, I can reproduce now... but only with SBT, what's curious (not with Scala CLI).

**Comment by akozich** [comment]
I noticed it's only failing with `-Yexplicit-nulls` scalac option

**Comment by Gedochao** [comment]
Yeah, I did try with `-Yexplicit-nulls`, but no luck. Happens with SBT only.
We still need a self-contained minimization without the dependencies.
The minimum we have right now:
- `io.sentry:sentry-logback:8.37.1`
- `org.jetbrains:annotations:23.0.0`

**Comment by akozich** [comment]
In my example I do not have `org.jetbrains:annotations`

**Comment by akozich** [comment]
The bug was introduced in 3.8.2. This code compiles well in 3.8.1 and fails on 3.8.2 and 3.8.3

**Comment by Gedochao** [comment]
> In my example I do not have `org.jetbrains:annotations`

it's a dependency of `sentry`.

**Comment by Gedochao** [comment]
> The bug was introduced in 3.8.2. This code compiles well in 3.8.1 and fails on 3.8.2 and 3.8.3

yup, labelled as a regression.

**Comment by SolalPirelli** [comment]
Somewhat minimized but still depending on sentry:

```scala
// build.sbt 
ThisBuild / scalaVersion := "3.8.2" // works with 3.8.1
ThisBuild / scalacOptions += "-Yexplicit-nulls"
// this shows a bunch of 'cannot find annotation on classpath' warnings
//ThisBuild / scalacOptions += "-Ydebug"
lazy val root = (project in file("."))
  .settings(
    libraryDependencies += "io.sentry" % "sentry" % "8.38.0"
// adding this makes it work:
//    libraryDependencies += "org.jetbrains" % "annotations" % "23.0.0"
  )

// src/main/scala/A.scala 
def a = new java.util.Random()

// src/main/scala/B.scala
abstract class B extends io.sentry.SentryOptions.BeforeSendCallback
```

Results in:
```
[error] no member new Any . <init>
[error] value <none>: <notype> does not take parameters
[error] Internal error in the incremental compiler while compiling /private/tmp/scala-3.8.3-regression/src/main/scala/B.scala: Unhandled type <error unspecified error> of class class dotty.tools.dotc.core.Types$UnspecifiedErrorType$
[error] three errors found
```

**Comment by SolalPirelli** [comment]
@akozich does your project build if you add `libraryDependencies += "org.jetbrains" % "annotations" % "23.0.0"` ?

**Comment by prolativ** [comment]
Minimized without external dependencies:

build.sh:
```shell
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Stage 1: compile Java stubs, strip annotation classes from the JAR.
# Annotations are referenced in bytecode but absent from the Scala classpath — triggers the bug.
STUBS_CLASSES="$SCRIPT_DIR/.out/stubs-classes"
mkdir -p "$STUBS_CLASSES"
javac -d "$STUBS_CLASSES" \
  $(find "$SCRIPT_DIR/jstubs" -name "*.java")
jar cf "$SCRIPT_DIR/.out/stubs-full.jar" -C "$STUBS_CLASSES" .
cp "$SCRIPT_DIR/.out/stubs-full.jar" "$SCRIPT_DIR/.out/stubs.jar"
zip -q -d "$SCRIPT_DIR/.out/stubs.jar" "org/jetbrains/annotations/*"

# Stage 2: compile Scala sources — crashes with internal compiler error in zinc
cd "$SCRIPT_DIR/scala"
scala-cli clean .
scala-cli compile . -S 3.8.3
```

jstubs/jstubs/lib/Foo.java:
```java
package lib;

import org.jetbrains.annotations.Nullable;

public class Foo {
  public interface Bar {
    @Nullable Object execute();
  }
}
```

jstubs/jstubs/org/jetbrains/annotations/Nullable.java:
```java
package org.jetbrains.annotations;

public @interface Nullable {}
```

scala/A.scala:
```scala
def a = new java.util.Random()
```

scala/B.scala:
```scala
abstract class B extends lib.Foo.Bar
```

scala/project.scala:
```scala
//> using options -Yexplicit-nulls
//> using jar ../.out/stubs.jar
```

**Comment by prolativ** [comment]
The key point here is that after the java sources were compiled, `org.jetbrains.annotations.Nullable` got removed from the classpath, which seems to have special handling in the compiler - I would expect this to be the potential source of the regression but the bisect script should be run to know that exactly

**Comment by SolalPirelli** [comment]
Yeah, this is similar to #22459 . Though what puzzles me is why `A.scala` is needed in this minimization. Something about loading the `java` package?

**Comment by prolativ** [comment]
My AI agent claims the problem is related to zinc and incremental compilation. Note that the crash doesn't occur with `scala-cli compile --server=false`

**Comment by akozich** [comment]
> @akozich does your project build if you add `libraryDependencies += "org.jetbrains" % "annotations" % "23.0.0"` ?

No. We do not explicitly use this lib

**Comment by Gedochao** [comment]
> > [@akozich](https://github.com/akozich) does your project build if you add `libraryDependencies += "org.jetbrains" % "annotations" % "23.0.0"` ?
> 
> No. We do not explicitly use this lib

I believe the intention here was to ask: can you check if it would build fine if you added that dependency explicitly?

**Comment by akozich** [comment]
I'm sorry, I misunderstood you. I checked the build with the library, and now it compiles successfully.

**Comment by SolalPirelli** [comment]
It does repro with `-Yforce-sbt-phases --server=false`

edit: ok with @prolativ 's setup above in a folder `../25722` then `scalac -classpath ../25722/.out/stubs.jar -Yexplicit-nulls -Yforce-sbt-phases ../25722/scala/A.scala ../25722/scala/B.scala` is a standalone repro
