### ISSUE TITLE
Regression in babylonhealth/lit-fhir, `IterableOps` in non collection types

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18223]
## Compiler version
3.3.0
3.3.1-RC4
3.3.2-RC nightly

Works in 3.2.2
Bisect points to d3861eeaaec1ac8acc2d3ba83f2243ef91926603 (making IterableOps transparent )

## Minimized code

```Scala
import scala.annotation.unchecked.uncheckedVariance
import scala.collection.*

class LitSeq[+T]
    extends scala.collection.IterableOps[T, LitSeq, LitSeq[T]]
    with PartialFunction[Int, T] {
  def apply(v1: Int): T = ???
  def iterator: Iterator[T] = ???
  protected def coll: LitSeq[T] = ???
  protected def fromSpecific(
      coll: IterableOnce[T @uncheckedVariance]
  ): LitSeq[T] = ???
  def iterableFactory: IterableFactory[LitSeq] = ???
  protected def newSpecificBuilder
      : mutable.Builder[T @uncheckedVariance, LitSeq[T]] = ???
  def toIterable: Iterable[T] = ???

  def isDefinedAt(x: Int): Boolean = ???
}

@main def Test() =
  val x: Any = ???
  val values = x match {
    case Some(x)       => List(x)
    case ls: LitSeq[_] => ls
    case None          => Nil
    case x             => List(x)
  }
  values.map(identity)

```

## Output

```scala
-- [E008] Not Found Error: /Users/wmazur/projects/dotty/bisect/main.scala:29:9 -
29 |  values.map(identity)
   |  ^^^^^^^^^^
   |  value map is not a member of PartialFunction[Int, Any]
```

## Expectation
Retrofitting Scala 2 stdlib into usage of transparent traits seems to be breaking code here. It should be decided should it still compile, or shall we treat it as source incompatibility since 3.3.0

**Comment by dwijnand** [comment]
I think this isn't a regression.  It's a change in inference, and I think it's additionally supported by the docs on creating a custom collection: https://docs.scala-lang.org/overviews/core/custom-collections.html.  You're meant to use Iterable or perhaps Seq as the base class.  For instance:

```scala
class LitSeq[+T] extends scala.collection.immutable.Seq[T] {
  def apply(i: Int): T = ???
  def iterator: Iterator[T] = ???
  def length: Int = ???
}
```

Then it will lub with List and give you a map method.
