### ISSUE TITLE
Do not autoimport scala.* when parsing .java files

### ISSUE THREAD

**Issue by ekrich** [lampepfl/dotty#7312]
## overview
Calling Java methods that return a non-primitive Java object from Scala causes a runtime error. Examples:
`java.lang.Long`
`java.lang.Boolean`
`...`

## minimized code
```Java
package beanconfig;

public class NumbersConfig {
    private long longVal;
    private Long longObj;

    public long getLongVal() { return longVal; }
    public void setLongVal(long longVal) { this.longVal = longVal; }
    public Long getLongObj() { return longObj; }
    public void setLongObj(Long longObj) { this.longObj = longObj; }
}
```
Calling code.
```Scala
assertEquals(4L, beanConfig.getLongObj)
```
## result
```Scala
[error] Test org.ekrich.config.impl.ConfigBeanFactoryTest.testCreateNumber failed: java.lang.NoSuchMethodError: beanconfig.NumbersConfig.getLongObj()J, took 0.059 sec
[error]     at org.ekrich.config.impl.ConfigBeanFactoryTest.testCreateNumber(ConfigBeanFactoryTest.scala:115)
```
## expectation
Code should run.

## work around
Fully specify return value
```Java
 public java.lang.Long getLongObj() { return longObj; }
```

**Comment by ekrich** [comment]
I can confirm that Java methods returning `Long` and `Double` now work on `0.27.0-bin-20200810-74ba21c-NIGHTLY`.
Reference: https://github.com/ekrich/sconfig/issues/55
