### ISSUE TITLE
Async code access to a variable in App fails in Dotty

### ISSUE THREAD

**Issue by mkotsur** [lampepfl/dotty#16149]
## Compiler version

3.2.0

## Minimized code

```Scala
import scala.concurrent.{Await, Future}
import scala.concurrent.duration._

object MapTest extends App {
  import concurrent.ExecutionContext.Implicits.global

  val test = "123"

  val dataF = Future { List("111", "222", "333", test) }

  Await.ready(dataF, 1.second)
}
```

## Output

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at MapTest.main(MapTest.scala)
Caused by: java.util.concurrent.TimeoutException: Future timed out after [1 second]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:104)
	at scala.concurrent.Await$.$anonfun$ready$1(package.scala:174)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.Await$.ready(package.scala:124)
	at MapTest$.<clinit>(MapTest.scala:13)
	... 1 more
java.lang.NoClassDefFoundError: Could not initialize class MapTest$
```

## Expectation

I'm aware of the intricacies of `DelayedInit` and `App`. However, since [this works in Scala 2.13](https://scastie.scala-lang.org/kApSowapSduZlu2Jti7OTA), I would expect this to also work in Scala 3 because the doc hasn't change: [doc dotty](https://dotty.epfl.ch/api/scala/App.html), [doc 2.13.3](https://www.scala-lang.org/api/2.13.3/scala/App.html).

Moreover, looking at this statement:

```
It should be noted that this trait is implemented using the DelayedInit functionality, which means that fields of the object will not have been initialized before the main method has been executed.
```

it's not clear why wrapping code into a Future makes any difference. Isn't access to `test` on line 3 happening before the method has been executed? 🤔

object PrintTest extends App {
  val test = "123"
  println(test)
}

**Comment by SethTisue** [comment]
maybe https://github.com/scala/scala/pull/10070 hasn't propagated to Scala 3 yet? it was included in Scala 2.13.9: https://www.scala-lang.org/api/2.13.9/scala/App.html  (it's a bit peculiar that you linked to the 2.13.3 doc above; that's a quite old version)

**Comment by som-snytt** [comment]
2.13.3 is when `-Xasync` arrived. It was the second pandemic release. The pandemic is already quite old.

**Comment by som-snytt** [comment]
There are many Scala 2 tickets about deadlocking a class initializer (object). From pandemic era:

https://github.com/scala/bug/issues/12278

There is a comment on that ticket about differences in dotty.

**Comment by odersky** [comment]
Yes, I think the dotty documentation of `App` is not up to date. I wonder where it came from? I assumed that it just copied the 2.13 docs?

**Comment by mkotsur** [comment]
Two small notes and two suggestions...

1. @SethTisue no real reason why I linked 2.13.**3**, not the latest one. Apologies if this confused you.

2. One more thing I noted: 3.1.2 has warning suppression `@nowarn("cat=deprecation&origin=scala\\.DelayedInit")` on the `App` trait, while 3.1.3 doesn't. I don't know if this is relevant.

While it would be very helpful if https://github.com/scala/scala/pull/10070 changes were present in dotty's docs, I don't think it will necessarily prevent people from wasting time on writing debugging the kind of code that I demonstrated. Even  if you carefully read the whole thing (which not many people do tbh) you may still think that it's OK to use `App` for a quick sketch and the only real risk is that it will be deprecated in the Future. Not that it will misbehave. Especially since the `DelayedInit` feature was dropped and it was said to be the cause of the funky initialization behavious.

Is there a reason not to make the trait deprecated already?
Can we put the emphasis on the recommendation to use `@main` by pulling it to the top of the text?

**Comment by SethTisue** [comment]
> Yes, I think the dotty documentation of App is not up to date. I wonder where it came from? I assumed that it just copied the 2.13 docs?

That should be resolved in 3.2.1 by https://github.com/lampepfl/dotty/pull/16074
