### PR TITLE
Don't cancel async TASTy write on success

### LINKED ISSUE #25797: Transient failure: `pipelining-scala-java-basic` in `scripted-tests`
CI failing in `pipelining-scala-java-basic`:

```scala

[info] [error] -- [E006] Not Found Error: /tmp/sbt_8dc6354b/c/src/main/scala/c/C.scala:4:7 ----
[info] [error] 4 |import b.B
[info] [error]   |       ^
[info] [error]   |       Not found: b
[info] [error]   |
[info] [error]   | longer explanation available when compiling with `-explain`
[info] [warn] -- Warning: /tmp/sbt_8dc6354b/c/src/main/scala/c/C.scala:12:4 ------------------
[info] [warn] 12 |    assert(A.foo(1) == 2)
[info] [warn]    |    ^
[info] [warn]    |    Line is indented too far to the right, or a `{` is missing before:
[info] [warn]    |
[info] [warn]    |    assert(A.foo(0) == 1)
[info] [warn] one warning found
[info] [error] one error found
[info] [error] (c / Compile / compileIncremental) Compilation failed
[info] [error] Total time: 1 s, completed Apr 13, 2026, 5:10:53 PM
Error:  x pipelining/pipelining-scala-java-basic 
Error:   Cause of test exception: {line 1}  Command failed: c/run failed
```

_Originally posted by @mbovel in https://github.com/scala/scala3/issues/25776#issuecomment-4238296678_

### PR DESCRIPTION
**Pull request by mbovel**
Fixes #25797

## Root cause

This fixes an intermittent `Not found: b` error when project `c` compiled against the early TASTy output of a Java-only project `b` in an sbt pipelining build.

The bug was introduced by #25618, which removed `async.sync()` from `GenBCode.runOn`. Before that PR, `GenBCode` always called `async.sync()` (even with an empty unit list, as is the case for Java-only projects compiled with `-Xjava-tasty`). That sync implicitly ensured the executor thread writing the early TASTy jar had completed before `cancelAsyncTasty()` was called in `Run.compile`.

After #25618, the call sequence in `Run.compile` became:

```
runPhases(...)       // GenBCode no longer syncs internally
cancelAsyncTasty()   // calls async.cancel() — always, even on success
syncAsyncTasty()     // added by #25776, but too late
```

`cancelAsyncTasty()` always called `async.cancel()`, which races with the executor thread writing TASTy:

- If the executor finishes first → `asyncTastyWritten` already resolved with `Some(state)` → `cancel()`'s `trySuccess(None)` is a harmless no-op → `apiPhaseCompleted` is called → pipelining works correctly.
- If `cancel()` wins → `asyncTastyWritten` is resolved with `None` → `backendFuture` evaluates to `None` → `apiPhaseCompleted` is **never called** → Zinc starts `c` with an empty early jar on the classpath → `Not found: b`.

The race was only reliably observable for Java-only projects because their compilation pipeline is very short after `ExtractAPI` (no JVM bytecode to generate), giving `cancel()` a large window to win. For Scala projects, `GenBCode` takes long enough that the executor always completes first.

## Fix

Move the cancel-on-error logic inside `syncAsyncTasty()`, conditioned on `ctx.reporter.hasErrors`:

```scala
// Run.scala
private def syncAsyncTasty()(using Context): Unit =
  for async <- _asyncTasty do
    // Cancel only on error: if the write task was never scheduled (e.g. Pickler
    // failed early), asyncTastyWritten would never resolve and sync() would block.
    // On success, do NOT cancel — the executor thread must complete so that
    // apiPhaseCompleted is called and Zinc can start downstream projects early.
    // See scala/scala3#25797.
    if ctx.reporter.hasErrors then
      async.cancel()

    for
      bufferedReporter <- async.sync()
      ...
```

`Run.compile` is simplified to just call `syncAsyncTasty()` after phases:

```scala
showProgress(runPhases(allPhases = fusedPhases)(using runCtx))
syncAsyncTasty()
```

On success, `syncAsyncTasty()` now waits for the executor thread to complete naturally (writing all TASTy entries and closing the jar) before `apiPhaseCompleted` is called. On error, the cancel unblocks the sync so we don't hang when the write task was never scheduled.

## How much have you relied on LLM-based tools in this contribution?

Extensively, for root cause investigation, diagnosis, and implementation of the fix.

## How was the solution tested?

New automated tests (including the issue's reproducer, if applicable)

The `pipelining/pipelining-scala-java-basic` scripted test already covers the scenario. A temporary CI step running it 30 times is added to confirm the race no longer triggers.

### CODE REVIEW

**Comment by mbovel** [comment]
```
Running pipelining/Xjava-tasty-fromjavaobject
```

blocked for 20 minutes... So the fix doesn't work.
