### PR TITLE
Enable stricter pattern binding warnings by default

### LINKED ISSUE #13832: Enable stricter pattern matching rules for 3.2
at https://docs.scala-lang.org/scala3/reference/changed-features/pattern-bindings.html it claims:

> From Scala 3.1 on, type checking rules will be tightened so that warnings are reported at compile-time instead

> In Scala 3.1, a pattern binding is only allowed if the pattern is irrefutable

> the changed behavior and additional type checks are only enabled under the `-source future` setting. They will be enabled by default in version 3.1

but 3.1 is out now and none of these claims came true.

Is the plan still to enable this by default, perhaps for 3.2?

Note that Scala 2.12.15 has now shipped with @smarter's https://github.com/scala/scala/pull/9740 (and 2.13.7 will ship in a matter of days with https://github.com/scala/scala/pull/9721), allowing `case` in Scala 2, so that will help this Scala 3 change not be a hardship for those who are cross-compiling.

### LINKED ISSUE #14615: introduce language imports for scala 3.2
add `3.2` and `3.2-migration` language modes, to `scala.runtime.stdLibPatches.language` and `dotty.tools.config.SourceVersion`

## Compiler version

3.2.0-bin-SNAPSHOT

## Minimized example

```Scala
import scala.language.`3.2`, scala.language.`3.2-migration`
```

## Output

```scala
-- [E008] Not Found Error: -----------------------------------------------------
1 |import scala.language.`3.2`
  |                      ^^^^^
  | value 3.2 is not a member of object language - did you mean language.3.0?
1 error found
                      
```

## Expectation
allow those imports

### PR DESCRIPTION
**Pull request by griggt**
The first step of a phased-in approach to tighten the rules on pattern bindings, as described at https://docs.scala-lang.org/scala3/reference/changed-features/pattern-bindings.html

In 3.2: (this PR), emit warnings by default for refutable pattern bindings. Keep the existing desugaring of for generators.
In 3.3 (or later), the above warnings become errors, and `case` is required on for generators to get filtering behavior.

Rewrites are available (under `-source 3.2-migration -rewrite`) to ease migration.

Closes #13832 
Closes #14615

### CODE REVIEW

**Comment by dwijnand** [comment]
The PR diff looks good to me (mod the Scala.js hack), but the community failures are weird:

```
[error] -- [E008] Not Found Error: /__w/dotty/dotty/community-build/community-projects/scodec/shared/src/main/scala/scodec/codecs/PaddedVarAlignedCodec.scala:56:6 
[error] 56 |      encA <- valueCodec.encode(a)
[error]    |      ^
[error]    |value withFilter is not a member of scodec.Attempt[(scodec.bits.BitVector, Long)]
[error] 57 |      padsize = calculatePadding(encA.size)
```

**Comment by dwijnand** [comment]
Nice, that went green.  So what's the plan with the Scala.js sources?  cc @sjrd

**Comment by sjrd** [comment]
IIUC, we must change this line:
https://github.com/scala-js/scala-js/blob/11e35c16c1740031d34ea5b8d595cfefde7c32c5/ir/shared/src/main/scala/org/scalajs/ir/Trees.scala#L1206
as
```diff
-        val StringLiteral(name) = propName
+        val StringLiteral(name) = propName: @unchecked
```
?

We could do that upstream. It seems to compile with 2.11, 2.12 and 2.13. (But you'll have to wait for a Scala.js 1.8.1 to be released to proceed.)

**Comment by dwijnand** [comment]
@griggt can you take care of PR'ing Scala.js and when a release comes out with that?  Basically it would suck for this PR to miss 3.2.0 or delay it.

**Comment by griggt** [comment]
Upstream PR: https://github.com/scala-js/scala-js/pull/4635

**Comment by griggt** [comment]
@sjrd Do you plan to PR the upgrade to Scala.js 1.9.0?  

[f6fe76c](https://github.com/lampepfl/dotty/pull/14294/commits/f6fe76caa2840a65d35a7a6f3fba533abbeb1656) is included here as a stand-in in anticipation of a proper upgrade PR.  It seems that at a minimum, https://github.com/scala-js/scala-js/pull/4586 needs a forward port.

**Comment by sjrd** [comment]
> Do you plan to PR the upgrade to Scala.js 1.9.0?

I'll try to do that this afternoon.

**Comment by sjrd** [comment]
See #14610.

**Comment by griggt** [comment]
Rebased on #14610

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 1]
```diff
@@ -2515,9 +2515,8 @@ object Parsers {
     def generatorRest(pat: Tree, casePat: Boolean): GenFrom =
       atSpan(startOffset(pat), accept(LARROW)) {
         val checkMode =
-          if (casePat) GenCheckMode.FilterAlways
-          else if sourceVersion.isAtLeast(future) then GenCheckMode.Check
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:2519]: I'm going to introduce a `3.2-migration` language mode, so should we keep old behaviour under that?

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:2519]: even with language modes 3.0 and 3.1 the old behaviour should stand right?

Comment (griggt) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:2519]: yes, I suppose it should. I'll rework it.

**Comment by griggt** [comment]
Now bootstrapping fails under `-source 3.2`:

```
-- [E086] Syntax Error: /__w/dotty/dotty/compiler/src/dotty/tools/dotc/core/Denotations.scala:516:10 
516 |    (for ((name1, name2, idx) <- tp1.paramNames.lazyZip(tp2.paramNames).lazyZip(tp1.paramNames.indices))
    |          ^
    |          Wrong number of parameters, expected: 3
517 |      yield if (name1 == name2) name1 else tp1.companion.syntheticParamName(idx)).toList
-- [E086] Syntax Error: /__w/dotty/dotty/compiler/src/dotty/tools/dotc/core/Symbols.scala:757:8 
757 |    for (tparam, bound) <- tparams.lazyZip(bounds) do
    |        ^
    |        Wrong number of parameters, expected: 2
758 |      tparam.info = bound
-- [E086] Syntax Error: /__w/dotty/dotty/compiler/src/dotty/tools/dotc/transform/Splicer.scala:310:14 
310 |          for (arg, info) <- args.lazyZip(argTypes) yield
    |              ^
    |              Wrong number of parameters, expected: 2
311 |            info match
312 |              case _: ExprType => () => interpretTree(arg) // by-name argument
313 |              case _ => interpretTree(arg) // by-value argument
-- [E086] Syntax Error: /__w/dotty/dotty/compiler/src/dotty/tools/dotc/typer/RefChecks.scala:143:14 
143 |          for (param, arg) <- params.lazyZip(args) do
    |              ^
    |              Wrong number of parameters, expected: 2
144 |            if !param.is(Private) then // its type can be narrowed through intersection -> a check is needed
145 |              val paramType = cls.thisType.memberInfo(param)
146 |              if !(arg.tpe <:< paramType) then
147 |                val argTypes = args.tpes
148 |                // it could still be OK but we might need to substitute arguments for parameters
149 |                // to account for dependent parameters. See pos/i11993.scala
150 |                if !(arg.tpe.subst(params, argTypes) <:< paramType.subst(params, argTypes))
151 |                then
152 |                  report.error(IllegalParameterInit(arg.tpe, paramType, param, cls), arg.srcPos)
four errors found
(scala3-compiler-bootstrapped / Compile / compileIncremental) Compilation failed
```

and I see the same errors if I try to bootstrap on `main` using `-source future-migration` (with fatal warnings disabled).

Is it expected that we need to write `case` on the generator in this circumstance, or is this a bug?

```scala
Welcome to Scala 3.1.2-RC1 (1.8.0_292, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> for (a, b) <- List("a","b","c").lazyZip(List(1,2,3)) do println(s"$a$b")
a1
b2
c3

scala> :settings -source:future

scala> for (a, b) <- List("a","b","c").lazyZip(List(1,2,3)) do println(s"$a$b")
-- [E086] Syntax Error: --------------------------------------------------------
1 |for (a, b) <- List("a","b","c").lazyZip(List(1,2,3)) do println(s"$a$b")
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |    Wrong number of parameters, expected: 2
1 error found

scala> for case (a, b) <- List("a","b","c").lazyZip(List(1,2,3)) do println(s"$a$b")
a1
b2
c3
```

File: compiler/src/dotty/tools/dotc/config/SourceVersion.scala [hunk 2]
```diff
@@ -16,7 +16,10 @@ enum SourceVersion:
   def isAtLeast(v: SourceVersion) = stable.ordinal >= v.ordinal
 
 object SourceVersion extends Property.Key[SourceVersion]:
-  def defaultSourceVersion = `3.0`
+  def defaultSourceVersion = `3.0`  // should be 3.2? but some tests fail:
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/config/SourceVersion.scala:19]: if you rebase off from https://github.com/lampepfl/dotty/pull/14629 then these still pass with 3.2 as default

File: compiler/src/dotty/tools/dotc/parsing/Parsers.scala [hunk 3]
```diff
@@ -2517,9 +2517,9 @@ object Parsers {
...
-          else GenCheckMode.FilterNow  // filter for now, to keep backwards compat
+          if casePat then GenCheckMode.FilterAlways
+          else if sourceVersion.isAtLeast(`3.2`) && !sourceVersion.isMigrating then GenCheckMode.Check
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/parsing/Parsers.scala:2521]: this current code would fail for `future-migration`
```suggestion
          else if sourceVersion.ordinal >= `3.2`.ordinal then GenCheckMode.Check
```
^ though we could perhaps add a variant of `isAtLeast` that does not consider the migration version in the same series

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/parsing/Parsers.scala:2521]: however, looking at the old code `future-migration` would use the new behaviour, so I don't think we need the "not migrating" check

**Comment by smarter** [comment]
If I understand this change correctly, it means that (when -source is not used) a piece of code that previously compiled without warnings can now fail with an error. To ease migration, could we instead emit a warning by default in 3.2 and only turn it into an error in 3.3? I imagine that the alternative is to recommend using `-source` but this seems much more cumbersome for users (they have to be aware of the flag in the first place, and need to remember to add/remove it when appropriate). This would also potentially give time for the warning to be backported to Scala 2 if someone felt like porting it to give a heads-up to Scala 2 projects that aren't cross-compiled yet.

**Comment by bishabosha** [comment]
> If I understand this change correctly, it means that (when -source is not used) a piece of code that previously compiled without warnings can now fail with an error. To ease migration, could we instead emit a warning by default in 3.2 and only turn it into an error in 3.3? I imagine that the alternative is to recommend using `-source` but this seems much more cumbersome for users (they have to be aware of the flag in the first place, and need to remember to add/remove it when appropriate). This would also potentially give time for the warning to be backported to Scala 2 if someone felt like porting it to give a heads-up to Scala 2 projects that aren't cross-compiled yet.

there's a method in report called `errorOrMigrationWarning` which can be used to make a warning for `3.2-migration` or an error if `3.2`+

**Comment by smarter** [comment]
-source and language imports help yes, but my point is that we should try to ensure a smooth migration out of the box, without requiring flags. I think going slow here is especially important since many projects are still on Scala 2, and if we pile up incompatible changes too quickly there's a risk they'll just feel overwhelmed when trying to migrate to Scala 3 and get too many errors.

**Comment by griggt** [comment]
As it currently stands, this PR enables by default two behaviors that were previously gated by `-source future`:

 1. emit warnings for refutable pattern bindings in `val` definitions and `for` expressions

 2. desugaring of `for` generators omits `withFilter` unless the pattern is prefixed by `case`

Aside from the oddity that was #14626, code that previously compiled without warnings should compile without error. However, because of (2), some previously working code may now fail with a MatchError at run time (and a warning at compile time).

The existing implementation of these two behaviors has them somewhat intertwined, however I think they could be disentangled so that we emit the warnings for 3.2 and defer the desugaring change to 3.3. I made a quick proof of concept of this which seems to work, but I have not fully investigated whether it continues to warn in all applicable cases.

**Comment by smarter** [comment]
> some previously working code may now fail with a MatchError at run time (and a warning at compile time).

Oh, I didn't realize that. To me, that's even worse than an error and whatever the version in which we change the desugaring, I'd strongly advocate for that change to also turn the warning into an error (that could be ignored using `: @unchecked`), otherwise I'm pretty sure this will result in unexpected crashes in production for someone.

**Comment by griggt** [comment]
> that's even worse than an error 

I agree wholeheartedly.  I didn't notice this at first because earlier drafts of this PR continued to use the old desugaring behavior due to a small mistake (and there are no existing tests that generators are non-filtering under `-source:future`!).  But I've been pondering what to do about it for the last week or so.

> whatever the version in which we change the desugaring, I'd strongly advocate for that change to also turn the warning into an error (that could be ignored using `: @unchecked`), 

Sounds like a good idea to me.

> otherwise I'm pretty sure this will result in unexpected crashes in production for someone.

Yep

**Comment by smarter** [comment]
For reference, 3.2.0-RC1 is now scheduled for May 17 (see https://github.com/lampepfl/dotty/milestone/36). No pressure, but let us know if you think you won't have time to update the PR before then and someone might be able to help finish it.

**Comment by griggt** [comment]
I've updated this based on the discussion above plus some additional fixes. The new phased-in approach is as follows:

  - In 3.2, emit warnings by default for refutable pattern bindings. Keep the existing desugaring of `for` generators.
  - In 3.3 (or later), the above warnings become errors, and `case` is required on `for` generators to get filtering behavior.

Rewrites are available to ease migration.

A preview of the changes and adaptations necessary for phase two can be found here: https://github.com/griggt/dotty/compare/stricter-pattern-bindings-3.2...griggt:stricter-pattern-bindings-3.3?expand=1

I'll extract the other miscellaneous fixes into separate PRs.

File: compiler/src/dotty/tools/dotc/report.scala [hunk 4]
```diff
@@ -67,11 +67,14 @@ object report:
...
-      from: SourceVersion)(using Context): Unit =
-    if sourceVersion.isAtLeast(from) then
-      if sourceVersion.isMigrating && sourceVersion.ordinal <= from.ordinal then migrationWarning(msg, pos)
-      else error(msg, pos)
+  def errorOrMigrationWarning(msg: Message, pos: SrcPos = NoSourcePosition, from: SourceVersion)(using Context): Unit =
+    gradualErrorOrMigrationWarning(msg, pos, from, from)
+
+  def gradualErrorOrMigrationWarning(msg: Message, pos: SrcPos = NoSourcePosition, warnFrom: SourceVersion, errorFrom: SourceVersion)(using Context): Unit =
+    if sourceVersion.isAtLeast(warnFrom) then
+      if sourceVersion.isMigrating && sourceVersion.ordinal <= errorFrom.ordinal then migrationWarning(msg, pos)
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/report.scala:75]: I think this only makes sense if the source version is migrating to the errorFrom version:
```suggestion
      if sourceVersion.isAtLeast(errorFrom) then
        if sourceVersion.isMigrating && sourceVersion.ordinal <= errorFrom.ordinal then migrationWarning(msg, pos)
        else error(msg, pos)
      else warning(msg, pos)
```

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/report.scala:75]: so this probably makes more sense to keep `errorOrMigrationWarning` the same, and `gradualErrorOrMigrationWarning` wraps it

**Comment by bishabosha** [comment]
I'm concerned that here there seems to be no way in the for comprehension examples to tell the compiler in a pattern match "I know what I am doing, I don't want toFilter, throw exception if it fails to match) - perhaps this can be another PR?

File: compiler/src/dotty/tools/dotc/transform/patmat/Space.scala [hunk 5]
```diff
@@ -312,8 +312,11 @@ object SpaceEngine {
    */
   def isIrrefutable(unapp: tpd.Tree, argLen: Int)(using Context): Boolean = {
     val fun1 = tpd.funPart(unapp)
-    val funRef = fun1.tpe.asInstanceOf[TermRef]
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:315]: is there something that specifically failed to prompt this change?

Comment (griggt) [reply compiler/src/dotty/tools/dotc/transform/patmat/Space.scala:315]: Yes, some tests started crashing.  This change is in a separate commit (c1b83abd5b276a95ad67a81683a4d692c12747d6) and the motivating details are in the commit message.  Basically, `fun1.tpe` can be an instance of `ErrorType` when the function is not a valid extractor.

But I agree that the code change itself is not clear, I should probably at least write `case _: ErrorType =>`

**Comment by griggt** [comment]
> I'm concerned that here there seems to be no way when pattern matching in a for comprehension to tell the compiler "I know what I am doing, I don't want `withFilter`, throw exception if it fails to match" - perhaps no one is asking for this (for a new PR), but it would add symmetry with the patterns in val defs

Did you have a particular syntax in mind? The grammar seems to disallow annotating the pattern, and we don't have the expr tree around when performing the check (although I suppose we could work around that).

**Comment by smarter** [comment]
I think it's fine to not support unchecked patterns here especially if it means we'd need to come up with a new syntax for them, we can revisit this later if there's a real need for it.

File: compiler/src/dotty/tools/dotc/report.scala (hunk 4 above)
Comment (griggt) [reply compiler/src/dotty/tools/dotc/report.scala:75]: I guess I don't have a clear understanding of the criteria for when a migration warning should be emitted vs. a regular warning.

My line of thinking was that if the current source version is `$version-migration`, and the diagnostic concerns language features or changes introduced by $version (and perhaps offers rewrites, etc.), then it should be a migration warning.

My first inclination in this case was to emit a migration warning under both `3.2` and `3.2-migration`, but it seemed that the current usage of migration warnings is limited to migration source versions.

I don't have strong feelings on this either way, but I think it might be good to document the consensus opinion to avoid any future misinterpretation.

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/report.scala:75]: from what I understand from the status-quo, migration warning is to turn errors in `3.0` into migration warnings if you use `3.0-migration`. So then once you go beyond the stable version, it is always an error. (i.e. it doesn't become again a migration warning in e.g. `3.3-migration`)

**Comment by bishabosha** [comment]
> Did you have a particular syntax in mind? The grammar seems to disallow annotating the pattern, and we don't have the expr tree around when performing the check (although I suppose we could work around that).
> I think it's fine to not support unchecked patterns here especially if it means we'd need to come up with a new syntax for them, we can revisit this later if there's a real need for it.

ok lets park the issue of unchecked patterns in for comprehensions :)

**Comment by griggt** [comment]
The thought was to keep this as a draft while #14988 and #14955 were reviewed and merged independently, then rebase and address your review comments.  Did you have any additional comments or concerns other than the implementation of  `gradualErrorOrMigrationWarning`?

**Comment by bishabosha** [comment]
> The thought was to keep this as a draft while #14988 and #14955 were reviewed and merged independently, then rebase and address your review comments.

ok this makes sense, we were discussing today what to do with this PR and I guess we forgot the other ones as they are not part of the 3.2.0-RC1 milestone (I just added them)

> Did you have any additional comments or concerns other than the implementation of `gradualErrorOrMigrationWarning`?

no other concerns

File: compiler/src/dotty/tools/dotc/report.scala (hunk 4 above)
Comment (griggt) [reply compiler/src/dotty/tools/dotc/report.scala]: done

**Comment by griggt** [comment]
This has been rebased and review comments addressed. I'm happy to rebase again just prior to merge in case another PR happens to introduce a refutable pattern binding into the codebase.

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 6]
```diff
@@ -1619,7 +1619,7 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
             tree.selector.removeAttachment(desugar.CheckIrrefutable) match {
               case Some(checkMode) if !sel.tpe.hasAnnotation(defn.UncheckedAnnot) =>
                 val isPatDef = checkMode == desugar.MatchCheck.IrrefutablePatDef
-                if !checkIrrefutable(sel, pat, isPatDef) && sourceVersion == `future-migration` then
+                if !checkIrrefutable(sel, pat, isPatDef) && sourceVersion.isAtLeast(`3.2`) && sourceVersion.isMigrating then
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/typer/Typer.scala:1622]: I think this patch should only run upto that version where we `errorFrom` in the `gradualErrorOrMigrationWarning`, so here I introduce a new SourceVersion member `isBetween`:
```suggestion
                if !checkIrrefutable(sel, pat, isPatDef) && sourceVersion.isMigrating && sourceVersion.isBetween(`3.2`, `future`) then
```

```scala
def isBetween(low: SourceVersion, high: SourceVersion): Boolean =
  require(low.ordinal < high.ordinal)
  isAtLeast(low) && stable.ordinal <= high.ordinal
```

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:1622]: perhaps also we should introduce a centralised place to control which versions each feature is enabled / warnFrom / errorFrom, so we don't need to synchronise version numbers everywhere when we enable something from `future`

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:1622]: I also wonder if the "This patch can be rewritten automatically" message should mention the full range of source versions it applies to.

**Review by bishabosha — CHANGES_REQUESTED** [review]
just a point about the patch needing to run specifically only in the migration versions for where we have the "grace period" for updating code

File: compiler/src/dotty/tools/dotc/config/Feature.scala [hunk 7]
```diff
@@ -88,8 +88,7 @@ object Feature:
   /** If current source migrates to `version`, issue given warning message
    *  and return `true`, otherwise return `false`.
    */
-  def warnOnMigration(msg: Message, pos: SrcPos,
-      version: SourceVersion)(using Context): Boolean =
+  def warnOnMigration(msg: Message, pos: SrcPos, version: SourceVersion)(using Context): Boolean =
     if sourceVersion.isMigrating && sourceVersion.stable == version
        || (version == `3.0` || version == `3.1` || version == `3.2`) && migrateTo3
```
Comment (bishabosha) [inline compiler/src/dotty/tools/dotc/config/Feature.scala:93]: `3.2` is no longer considered equivalent to `3.0`
```suggestion
       || (version == `3.0` || version == `3.1`) && migrateTo3
```

Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/config/Feature.scala:93]: this is partly the reason I wanted to introduce a "series" concept in https://github.com/lampepfl/dotty/pull/14629, so you don't need to remember all the parts of code where versions are considered equivalent

**Comment by bishabosha** [comment]
> > automatic patches should only run specifically for the migration versions that we have declared the "grace period" for updating code
> 
> Is this just a policy decision or are there technical reasons behind it? I had left the migration patches open ended as I wanted to avoid `-future-migration` having different behavior between now and, well, the future, on say a codebase moving from 3.0/3.1.

this is an interesting point, I was saying this because for example patches for `3.0` are only applied for `3.0-migration`, i.e. not for `future-migration` - i.e. once you have gone beyond that version it is no longer valid source so there is nothing to patch. This is also a minor release so source compatibility could be broken. @smarter what do you think?

**Comment by smarter** [comment]
Honestly I'm not sure, but whatever we do should be documented in https://dotty.epfl.ch/docs/reference/language-versions/source-compatibility.html

**Comment by bishabosha** [comment]
I had a discussion with @sjrd , I think it is safe to say that `future` is not meant to adhere to the same compatibility guarantees of a usual language version. Otherwise it will be frozen forever and we could never add any new `future` features

**Review by bishabosha — APPROVED** [review]

**Comment by bishabosha** [comment]
need someone else to review my last commit

File: compiler/src/dotty/tools/dotc/typer/Typer.scala [hunk 8]
```diff
@@ -1619,7 +1619,10 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
             tree.selector.removeAttachment(desugar.CheckIrrefutable) match {
               case Some(checkMode) if !sel.tpe.hasAnnotation(defn.UncheckedAnnot) =>
                 val isPatDef = checkMode == desugar.MatchCheck.IrrefutablePatDef
-                if !checkIrrefutable(sel, pat, isPatDef) && sourceVersion.isAtLeast(`3.2`) && sourceVersion.isMigrating then
+                if !checkIrrefutable(sel, pat, isPatDef)
+                  && sourceVersion.isMigrating
+                  && sourceVersion.isBetween(`3.2`, `future`)
```
[the remark this answers is not in the document]
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:1624]: yes it does nothing now, but i.e. in the future these arguments should not be magic constants, but controlled from a central location. e.g. in the future perhaps we will replace `future` by `3.3`

[the remark this answers is not in the document]
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:1624]: there have already been enough times where logic for controlling which version enables which feature is spread all through the compiler and it is tedious to update them everywhere

[the remark this answers is not in the document]
Comment (bishabosha) [reply compiler/src/dotty/tools/dotc/typer/Typer.scala:1624]: ok I can think about reintroducing this at another time
