### ISSUE TITLE
Unable to unlift StringContext in my macro after upgrading to 0.24.0-RC1

### ISSUE THREAD

**Issue by nimatrueway** [lampepfl/dotty#8888]
## Minimized code

```Scala
object Macro { 

  inline def (sc: StringContext) poql(inline args: Any*): String = ${ poqlExpr('sc, 'args) }

  private def poqlExpr(sc: Expr[StringContext], args: Expr[Seq[Any]])(using qctx: QuoteContext): Expr[String] = {
    val pattern = sc.unliftOrError.parts.mkString("_")
    (pattern, args) match {
      case ("select * from table", Varargs(Nil)) =>
        '{ "SIMPLE SELECT" }
    }
  }

}

object Main {
  
  import Macro._

  def main(args: Array[String]): Unit = {
    val ast = poql"select * from table" // should be replaced with "SIMPLE SELECT"
    println(ast)
  }

}
```

## Output

```scala
[error] 11 |    val ast = poql"select * from table"
[error]    |                   ^^^^^^^^^^^^^^^^^^^
[error]    |     Expected a known value. 
[error]    |
[error]    |     The value of: sc
[error]    |     could not be unlifted using scala.quoted.Unliftable.Tuple1_delegate
[error]    | This location contains code that was inlined from Main.scala:6
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed May 6, 2020, 9:03:42 AM
```

## Expectation

1. This used to work in `0.23.0-RC1` but not in `0.24.0-RC1` anymore.
    **Update:** changing it to `(inline sc: StringContext)` solved the problem as neko-kai suggested.

**Comment by neko-kai** [comment]
@nimatrueway Does it still happen if you mark `sc` as `inline`?

**Comment by nimatrueway** [comment]
@neko-kai Good point, your suggestion addresses my first problem! The second point will be left though, I don't know possible way except for `implicit class` + `inner object` to write an extractor for my interpolator.
