### PR TITLE
Move classType checks for new expressions to PostTyper

### LINKED ISSUE #11781: Regression: new <type alias> should compile
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
object Ah {
  final case class Values[B, +A](a: A)

  trait Object[B] {
    final type Values[+A] = Ah.Values[B, A]
    object Values {
      def blah: Values[Unit] =
        new Values(())
    }
  }
}
```

## Output

```
-- Error: as.scala:8:12 --------------------------------------------------------
8 |        new Values(())
  |            ^^^^^^
  |            Object.this.Values is not a class type
-- Error: as.scala:8:19 --------------------------------------------------------
8 |        new Values(())
  |                   ^^
  |     too many arguments for constructor Object in class Object: (): Object
2 errors found
```

## Expectation

It should compile. It compiles with Scala 2.12 and 2.13.

### PR DESCRIPTION
**Pull request by odersky**
When typechecking a new expression, we cannot reliably tell what the actual underlying
type is since this might depend on type inference that still has to happen at this point.

Fixes #11781

### CODE REVIEW

**Review by liufengyun — APPROVED** [review]
LGTM
