### ISSUE TITLE
BeanProperty annotation does not seem to work as expected in Scala 3.0.0-RC2

### ISSUE THREAD

**Issue by pjfanning** [lampepfl/dotty#11972]
## Compiler version

Scala 3.0.0-RC2 (and Scala 3.0.0-RC1)

## Minimized code

https://scastie.scala-lang.org/ItQMKLDxT5mX3d5cmfwwUQ

```Scala
import scala.beans.BeanProperty

class PojoWrittenInScala {
  @BeanProperty var fooBar: String = ""
}

val pojo = new PojoWrittenInScala

@main def main = {
  println("fooBar=" + pojo.getFooBar())
}
```

## Output

compiler error saying `value getFooBar is not a member of PojoWrittenInScala`

## Expectation

The equivalent code compiles and works in Scala 2.

I had to do this hack to a test case in jackson-module-scala to get it to compile with Scala 3.0.0-RC2 -- https://github.com/FasterXML/jackson-module-scala/commit/85e11761e58e21751fcdf83c776556ca331dd1dc

**Comment by smarter** [comment]
This is intentional: the methods generated from the scala.beans annotations are now invisible in Scala code (but visible in Java code and through reflection), because their primary usecase is interoperability with Java frameworks.

**Comment by jim-oflaherty-jr-qalocate-com** [comment]
> This is intentional: the methods generated from the scala.beans annotations are now invisible in Scala code (but visible in Java code and through reflection), because their primary usecase is interoperability with Java frameworks.

Is there a specific place this is explicitly documented?

IOW, as people hit these kinds of snags, it sure would behoove the community to have a "known place" to go to surface them as quickly as possible. For those of us who are stuck migrating Scala 2 projects we've inherited into Scala 3, the faster we can anticipate and estimate working around these kinds of problems are very helpful.

Said another way, each time a problem like this is encountered in a Scala 2 to Scala 3 migration, it just reinforces the whole "It's just as bad as the Python 2 to Python 3 migration".

**Comment by SethTisue** [comment]
> Is there a specific place this is explicitly documented?

Have you checked https://scalacenter.github.io/scala-3-migration-guide/ ?

**Comment by jim-oflaherty-jr-qalocate-com** [comment]
Tysvm, Seth. I really appreciate being pointed there.

However, my experience there is already undesirable and immediately diminished my migration confidence.

Here's what happened.

1. Entering "beanproperty" in the search box did not cause anything to happen
2. Entering "bean property" in the search box caused a 404
3. Entering "bean" in the search box dropped me into a random location in the documentation
4. Attempting to find a place to submit an issue ticket was non-trivial

Given how simple these steps were to take, and given how unpredictable the results were, it gives a terrible first impression.

I'd be happy to open an issue (or 4) to point out the above. However, I don't have the time (and for most others, the motivation) to try and figure this out as it would cause me to lose my current focus for which I came to this site in the first place.

**Comment by SethTisue** [comment]
Issues with the guide can be reported at https://github.com/scalacenter/scala-3-migration-guide

**Comment by jim-oflaherty-jr-qalocate-com** [comment]
Tysvm, again. I have submitted a ticket:
https://github.com/scalacenter/scala-3-migration-guide/issues/174

**Comment by SethTisue** [comment]
let’s Scaladoc it too: https://github.com/scala/bug/issues/12870
