### PR TITLE
activate constrainResult fix in 3.4

### LINKED ISSUE #18174: Don’t apply wildcard approximation to non-transparent inlines in 3.4
> I guess there would be another follow up to add the `3.4` source version and enable it there?

_Originally posted by @bishabosha in https://github.com/lampepfl/dotty/pull/18130#discussion_r1257922206_

Once we have a 3.4 branch, we should revert #18130.

### PR DESCRIPTION
**Pull request by bishabosha**
fixes #18174

### CODE REVIEW

**Review by julienrf — APPROVED** [review]
Thank you!

**Comment by bishabosha** [comment]
@sjrd and @julienrf asking for advice on the release notes clause

**Comment by julienrf** [comment]
I am not sure whether the note should belong to the section “Error reporting improvements” or “Changes with compatibility issues”, but here is a first suggestion:

> Before 3.4.0, compilation errors were sometimes containing incorrect suggestions. Here is an example taken from the bug report [#9685](https://github.com/lampepfl/dotty/issues/9685):
>
> ~~~ scala
>   import munit.FunSuite
>
>   class Example extends FunSuite {
>     1.asdf
> //  ^^^^^^
> // value asdf is not a member of Int, but could be made available as an extension method.
> //
> // The following import might make progress towards fixing the problem:
> //
> //    import munit.Clue.generate
>   }
> ~~~
>
> In this example, the second part of the error message, which suggest adding an import, is incorrect. Adding the suggested import would not help here.
>
> This issue is fixed in Scala 3.4.0. The error message does not anymore suggest irrelevant imports.
>
> However, the fix changed the way the result types of `inline` methods are inferred, which could cause compilation errors when upgrading to Scala 3.4.0. You can check if your Scala 3.3.x project would compile with the new type inference behavior by adding the compiler option `-source future`. In case some files of your project do not compile with Scala 3.4.0 anymore, you can switch back to the old behavior by adding ``import scala.language.`3.3` `` in the impacted files, or, preferably, fix the issue by adding more explicit types (so that the compiler does not need to infer them), or, in last resort, by making the method `transparent inline` instead of just `inline`.

That being said, it seems https://github.com/lampepfl/dotty/pull/18130, which introduces the `-source future` behavior has not been backported to Scala 3.3, so the `-source future` trick indicated above might not work. Unless I missed something?
