### ISSUE TITLE
Cannot fully construct extension method for IArray

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#11358]
## Compiler version

Dotty master 6a5565d5f90050a24451e078901e77dbb22d405a

## Minimized code

```Scala
def test1: IArray[Int] = IArray(1, 2) +++ IArray(2, 3)
def test2: IArray[Int] = IArray(1, 2) +++ List(2, 3)

extension [A](arr: IArray[A])
  def +++[B >: A: reflect.ClassTag](suffix: IArray[B]): IArray[B] = ???
  def +++[B >: A: reflect.ClassTag](suffix: IterableOnce[B]): IArray[B] = ???
```

## Output

```scala
-- [E008] Not Found Error: Foo.scala:3:38 --------------------------------------
3 |def test1: IArray[Int] = IArray(1, 2) +++ IArray(2, 3)
  |                         ^^^^^^^^^^^^^^^^
  |        value +++ is not a member of IArray[Int].
  |        An extension method was tried, but could not be fully constructed:
  |
  |            +++()    failed with
  |
  |                value +++: <overloaded +++> does not take parameters
-- [E008] Not Found Error: Foo.scala:4:38 --------------------------------------
4 |def test2: IArray[Int] = IArray(1, 2) +++ List(2, 3)
  |                         ^^^^^^^^^^^^^^^^
  |        value +++ is not a member of IArray[Int].
  |        An extension method was tried, but could not be fully constructed:
  |
  |            +++()    failed with
  |
  |                value +++: <overloaded +++> does not take parameters
2 errors found
```

## Expectation
Should compile and be equivalent to the code generated for 

```scala
def test1: IArray[Int] = IArray(1, 2) +++ IArray(2, 3)

extension [A](arr: IArray[A])
  def +++[B >: A: reflect.ClassTag](suffix: IArray[B]): IArray[B] = ???
```

```scala
def test2: IArray[Int] = IArray(1, 2) +++ List(2, 3)

extension [A](arr: IArray[A])
  def +++[B >: A: reflect.ClassTag](suffix: IterableOnce[B]): IArray[B] = ???
```
which work individually.

**Comment by nicolasstucki** [comment]
This is a blocker for #11354

**Comment by nicolasstucki** [comment]
Simpler version
```scala


def test1: IArray[Int] = IArray(1, 2) +++ IArray(2, 3)
def test2: IArray[Int] = IArray(1, 2) +++ List(2, 3)

extension [A](arr: IArray[A])
  def +++[B](suffix: IArray[B]): IArray[B] = ???
  def +++[B](suffix: IterableOnce[B]): IArray[B] = ???
```

**Comment by nicolasstucki** [comment]
It is probably the double type arguments list

**Comment by odersky** [comment]
Yes, if there's just one type parameter it works.
