### PR TITLE
Fix #6199: Use a skolemized prefix in asSeenFrom when needed

### LINKED ISSUE #6199: Type member inference issue
The code below compiles with scalac 2.12, but not with dotty

```scala
trait Foo {
  type State
  def bar(f: Bar[State] => Bar[State]): Foo = this
}
object Foo {
  def unit: Foo = new Foo {
    type State = Any
  }
  def doBar: Foo = unit.bar(bar => bar)
}
case class Bar[+A]()
```
Code like this will produce following compilation error:
```scala
[error] 17 |    identity.bar(bar => bar)
[error]    |                        ^^^
[error]    |           Found:    scalaz.zio.test.Bar[scalaz.zio.test.Foo#State](bar)
[error]    |           Required: scalaz.zio.test.Bar[Nothing]
[error] one error found
```

If we change the declaration of Bar to `case class Bar[A]()` (got rid of covariance) we will get another error:
```scala
[error] 16 |  def doBar: Foo = unit.bar(bar => bar)
[error]    |                                   ^^^
[error]    |                                   Found:    scalaz.zio.test.Bar[_](bar)
[error]    |                                   Required: Nothing
[error] one error found
```
If we change `unit` to be a `val` instead of `def` it compiles, but this is just a distilled, minimum code that produces the same error as we encountered during scalaz-zio compilation with dotty `0.13.0-RC1`, see related ticket https://github.com/scalaz/scalaz-zio/issues/702

### PR DESCRIPTION
**Pull request by smarter**
Prior to
https://github.com/lampepfl/dotty/commit/91ee02fcca4881b34e35d3e2721e1b00e98fd512,
unstable prefixes appearing in selection types were handled in a
two-pass approach which can be summarized as:

1. Type the selection with the unstable prefix, if this prefix appears
   in a position where it cannot be widened away, mark it with a special
   annotation.
2. If the result of the selection contains this annotation, retype it
   after having wrapped its prefix in a skolem.

This got replaced by the use of an `ApproximatingTypeMap` which can
always construct a valid (but potentially approximated) type for the
selection.

Most of the time this is all we need but there are some cases where
skolemizing the prefix is still useful as witnessed by the tests added
in this commit. They are now handled by unconditionally skolemizing
unstable prefixes.

To avoid any potential performance impact from this, we teach
`asSeenFrom` to always widen these prefixes first and only make use of
the skolem to avoid returning an approximation. Since this almost never
occurs (it happens only once when compiling Dotty) this means we incur
almost no extra cost (the skolem itself still needs to be allocated
unconditionally in advance, this cannot be delegated to `asSeenFrom`
because it's supposed to be an idempotent operation and each skolem is
unique).

### CODE REVIEW

**Comment by smarter** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala [hunk 1]
```diff
@@ -1033,10 +1033,11 @@ class TreeUnpickler(reader: TastyReader,
          (untpd.Ident(qual.name).withSpan(qual.span), qual.tpe.asInstanceOf[TypeRef])
       }
 
-      def accessibleDenot(pre: Type, name: Name, sig: Signature) = {
-        val d = pre.member(name).atSignature(sig)
+      def accessibleDenot(qualType: Type, name: Name, sig: Signature) = {
+        val pre = ctx.typeAssigner.maybeSkolemizePrefix(qualType, name)
```
Comment (smarter) [inline compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala]: I'm not super happy with having to recompute whether the prefix needs to be skolemized in the unpickler, but I don't really see a way around it. Maybe asSeenFrom should behave differently when unpickling a tree, but how do you even know if the type on which asSeenFrom is called comes from a tree being unpickled ? And even if we manage to allow unstable prefixes when unpickling, is that really sound when combined with inlining ?

**Comment by liufengyun** [comment]
test performance please

File: compiler/src/dotty/tools/dotc/core/TypeOps.scala [hunk 2]
```diff
@@ -44,7 +68,14 @@ trait TypeOps { this: Context => // TODO: Make standalone object.
           case pre: SuperType => toPrefix(pre.thistpe, cls, thiscls)
           case _ =>
             if (thiscls.derivesFrom(cls) && pre.baseType(thiscls).exists)
-              if (variance <= 0 && !isLegalPrefix(pre)) range(defn.NothingType, pre)
+              if (variance <= 0 && !isLegalPrefix(pre)) {
```
Comment (odersky) [inline compiler/src/dotty/tools/dotc/core/TypeOps.scala]: I don't understand the change in logic here. Why set `approximated = true` only if variance < 0?

Comment (smarter) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala]: If variance = 0 then we return a range, and this range happens to be the prefix of a path, then we might be able to get away with not approximating the type by dealiasing (this is handled by the logic in ApproximatingTypeMap). On the other hand, if we do approximate then ApproximatingTypeMap will inevitably call `expandBounds` which will set the approximated flag. Maybe I could add this explanation as a comment in the code ?

Comment (odersky) [reply compiler/src/dotty/tools/dotc/core/TypeOps.scala]: Yes, would be good to add this as an explanation.
