### ISSUE TITLE
Can't build scala3-compiler with JDK 14

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10133]
## Minimized code

using JDK 14 on commit 1ab76c19993feb85521b5b0d17ed7f53ed69a7f3:
```
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
```

```Scala
sbt:scala3> clean
sbt:scala3> repl
```

## Output (click arrow to expand)
<details>

```scala
exception caught when loading class AnnotationDefault: java.lang.NullPointerException
[error] error while loading PreviewFeature,
[error] class file /modules/java.base/jdk/internal/PreviewFeature.class is broken, reading aborted with class java.lang.NullPointerException
[error] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[error] externalName = jdk.internal.PreviewFeature$Feature,
[error] outerName = jdk.internal.PreviewFeature,
[error] innerName = Feature
[error] owner.fullName = jdk.internal.PreviewFeature
[error] while parsing /modules/java.base/java/lang/Class.class while parsing annotations in /modules/java.base/java/lang/Class.class
[error] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[error] externalName = jdk.internal.PreviewFeature$Feature,
[error] outerName = jdk.internal.PreviewFeature,
[error] innerName = Feature
[error] owner.fullName = jdk.internal.PreviewFeature
[error] while parsing /modules/java.base/java/lang/Class.class while parsing annotations in /modules/java.base/java/lang/Class.class
[error] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[error] externalName = jdk.internal.PreviewFeature$Feature,
[error] outerName = jdk.internal.PreviewFeature,
[error] innerName = Feature
[error] owner.fullName = jdk.internal.PreviewFeature
[error] while parsing /modules/java.base/java/lang/String.class while parsing annotations in /modules/java.base/java/lang/String.class
[error] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[error] externalName = jdk.internal.PreviewFeature$Feature,
[error] outerName = jdk.internal.PreviewFeature,
[error] innerName = Feature
[error] owner.fullName = jdk.internal.PreviewFeature
[error] while parsing /modules/java.base/java/lang/String.class while parsing annotations in /modules/java.base/java/lang/String.class
[error] Caught: java.lang.AssertionError: assertion failed: failure to resolve inner class:
[error] externalName = jdk.internal.PreviewFeature$Feature,
[error] outerName = jdk.internal.PreviewFeature,
[error] innerName = Feature
[error] owner.fullName = jdk.internal.PreviewFeature
[error] while parsing /modules/java.base/java/lang/String.class while parsing annotations in /modules/java.base/java/lang/String.class
[error] 6 errors found
[error] (scala3-library-bootstrapped / Compile / compileIncremental) Compilation failed
[error] Total time: 77 s (01:17), completed 1 Nov 2020, 00:27:03
```
</details>

**Comment by bishabosha** [comment]
related to #10037 and #10131 ?

**Comment by smarter** [comment]
It's interesting cause I tried it recently and compilation worked (there was a few test failures for things that have since been fixed): https://github.com/smarter/dotty/actions/runs/245223848, so there's a good chance it regressed in https://github.com/lampepfl/dotty/pull/10037

**Comment by griggt** [comment]
`git bisect` shows the culprit as a8f1cfb in #10037 when using:

```
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
```
