### PR TITLE
Rebase scalatest community build on scalatest/3.1.x

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
We have some new issue with a `java.lang.NoClassDefFoundError`

```scala
[info] - should be used when GenSeq is being compared with shouldEqual matcher *** FAILED *** (2 milliseconds)
[info]   Expected exception org.scalatest.exceptions.TestFailedException to be thrown, but java.lang.NoClassDefFoundError was thrown (DifferSpec.scala:429)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
[info]   at org.scalatest.funspec.AnyFunSpec.newAssertionFailedException(AnyFunSpec.scala:1631)
[info]   at org.scalatest.Assertions.intercept(Assertions.scala:762)
[info]   at org.scalatest.funspec.AnyFunSpec.intercept(AnyFunSpec.scala:1631)
[info]   at org.scalactic.DifferSpec.$init$$$anonfun$132$$anonfun$13(DifferSpec.scala:430)
[info]   at org.scalatest.funspec.AnyFunSpecLike.org$scalatest$funspec$AnyFunSpecLike$ItWord$$_$apply$$anonfun$1(AnyFunSpecLike.scala:167)
[info]   at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:21)
[info]   at org.scalatest.funspec.AnyFunSpecLike$$anon$1.apply(AnyFunSpecLike.scala:456)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.funspec.AnyFunSpec.withFixture(AnyFunSpec.scala:1631)
[info]   at org.scalatest.funspec.AnyFunSpecLike.invokeWithFixture$1(AnyFunSpecLike.scala:462)
[info]   at org.scalatest.funspec.AnyFunSpecLike.runTest$$anonfun$1(AnyFunSpecLike.scala:466)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:307)
[info]   at org.scalatest.funspec.AnyFunSpecLike.runTest(AnyFunSpecLike.scala:466)
```

@liufengyun, could you investigate this one?

**Comment by liufengyun** [comment]
OK, I'll have a look

**Comment by nicolasstucki** [comment]
Cool. I see that you could revert the workarounds I added previously. We can probably squash https://github.com/dotty-staging/scalatest/commit/6a4c896adb68e35b8cdad90cc1984e625c40be4f and https://github.com/dotty-staging/scalatest/commit/d8c3df8c52663a95af8019d2284033ab74b9e1ad with https://github.com/dotty-staging/scalatest/commit/db67eb289abf346542613e2df1eaf68aa5b87cce. This would minimize the diff with `scalatest/3.1.x`.

**Comment by nicolasstucki** [comment]
Note that this uses the scalatest branch https://github.com/dotty-staging/scalatest/commits/dotty-community-build.

**Comment by anatoliykmetyuk** [comment]
Looks like we're about two months behind scalatest/scalatest/3.1.x. Is that intended?
