### ISSUE TITLE
`@BeanProperty` setters/getters not found

### ISSUE THREAD

**Issue by armanbilge** [lampepfl/dotty#15563]
## Compiler version

`3.2.1-RC1-bin-20220630-f157978-NIGHTLY`

## Minimized code

```Scala
//> using scala "3.2.1-RC1-bin-20220630-f157978-NIGHTLY"

import scala.beans.BeanProperty

class Foo {
  @BeanProperty var bar: String = "whatever"
}

class Baz {
  def go(foo: Foo): Unit = {
    foo.getBar()
    foo.setBar("whoever")
  }
}
```

## Output

```scala
[error] ./bug.scala:11:5: value getBar is not a member of Foo
[error]     foo.getBar()
[error]     ^^^^^^^^^^
[error] ./bug.scala:12:5: value setBar is not a member of Foo
[error]     foo.setBar("whoever")
[error]     ^^^^^^^^^^
```

## Expectation

It compiles in Scala 2.13.

**Comment by armanbilge** [comment]
Woops, looks like wontfix dupe of https://github.com/lampepfl/dotty/issues/11972#issuecomment-812253271.
