### ISSUE TITLE
REPL NPE on invalid code without indentation

### ISSUE THREAD

**Issue by SolalPirelli** [lampepfl/dotty#25715]
## Compiler version

3.8.3-RC3

## Minimized code

```scala
def formatTime(numBreadsUsed: BigDecimal, hourRatioInBigDecimal2: Double, machineUtilizationInSecondsAsString9InBCIFormatMaybeTruncated) =
          return;
var formattedTime: String = "%.2f".format(result)
result < minAllowedMin => {
log.logMessage("machine with id-" + item.getId() +" uses more than twice that number which equals : "+ doubleMachinePerSecondsValueFromBCIDouble);
log.timeFormattedByHours(secondsUsedForAllTypesLogInfoToStdOutInSecondsAsString.toDouble.toFloat,result.getTime().fmtAndConvertTotalResultIntoHours())
log.msgToConsole(item.getId(),"", "", seconds)
log.doAction(seconds == Util.SECONDS_THRESHOLD_OVER_HALF_AN_HOUR);
return;
log.printSummary("\n \t"+minutesSinceStartTime+" minute since run - result:\ncalculated by ratio to all current utilized minutes converted from ",seconds.intValue());
return;
@Retention class AnnotationDemo
fun interface
annotation on
class CancellationFailureThrowable {
  if (cancelRequested.compareAndSet(true,
  throw if (!(Thread.currentThread()))
cancellationStatusRef ? new Predicate<>();
else if (((test && timeout > getTimeStamp().get())
||
```

In appears that the `match` statement in Scanners.scala:593 requires an indentation region exists:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "dotty.tools.dotc.parsing.Scanners$Region.proposeKnownWidth(dotty.tools.dotc.parsing.Scanners$IndentWidth, int)" because "r" is null
	at dotty.tools.dotc.parsing.Scanners$Scanner.handleNewLine(Scanners.scala:602)
	at dotty.tools.dotc.parsing.Scanners$Scanner.nextToken(Scanners.scala:401)
	at dotty.tools.dotc.parsing.Scanners$Scanner.skip(Scanners.scala:313)
	...
	at dotty.tools.repl.Main.main(Main.scala)
```

Maybe the variable could be initialized with a "root" region to prevent this bug.

_Thanks to OSTIF/Quarkslab for finding this._

**Comment by som-snytt** [comment]
What did I do wrong? `currentRegion` should never turn null.

```
✗ scala-cli compile --server=false -S 3.8.3 tests/neg/i25715.scala
-- [E040] Syntax Error: /home/amarki/projects/scala3/tests/neg/i25715.scala:1:135
1 |def formatTime(numBreadsUsed: BigDecimal, hourRatioInBigDecimal2: Double, machineUtilizationInSecondsAsString9InBCIFormatMaybeTruncated) =
  |                                                                                                                                       ^
  |                                               ':' expected, but ')' found
-- [E103] Syntax Error: /home/amarki/projects/scala3/tests/neg/i25715.scala:4:0
4 |result < minAllowedMin => {
  |^^^^^^
  |Illegal start of toplevel definition
  |
  | longer explanation available when compiling with `-explain`
-- [E089] Syntax Error: /home/amarki/projects/scala3/tests/neg/i25715.scala:2:10
2 |          return;
  |          ^^^^^^
  |          method formatTime has a return statement; it needs a result type
  |
  | longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: /home/amarki/projects/scala3/tests/neg/i25715.scala:3:42
3 |var formattedTime: String = "%.2f".format(result)
  |                                          ^^^^^^
  |                                          Not found: result
  |
  | longer explanation available when compiling with `-explain`
4 errors found
Compilation failed
```

**Comment by SolalPirelli** [comment]
It crashes the REPL, but not the compiler, for some reason.

**Comment by Gedochao** [comment]
This seems to actually be a regression.
It crashes with Scala 3.7.0+, but not on 3.6.4.
Trying to bisect further.

**Comment by Gedochao** [comment]
Last good nightly: 3.7.0-RC1-bin-20250218-417d542-NIGHTLY
First bad nightly: 3.7.0-RC1-bin-20250219-345b2da-NIGHTLY
The culprit commit is in the 417d542..345b2da range.

**Comment by Gedochao** [comment]
6bf8eaee7b  / https://github.com/scala/scala3/pull/22611 seems to be the culprit.
Beats me why does it only crash in the REPL.
cc @som-snytt

**Comment by som-snytt** [comment]
Thanks @Gedochao I was thinking 3.7.0-RC1 was before my time.

Simple question, is the repro to paste to REPL, or what is the test? (It didn't work for me during my last night. On Windows WSL. I looked briefly at the REPL testing options.)

I will assume ownership or assignmentship if I can test it. I don't use REPL in anger anymore FSR.

Also worth noting, that this the commit I suspected on the other fuzzing ticket for scanner!

**Comment by Gedochao** [comment]
> Simple question, is the repro to paste to REPL, or what is the test?

@som-snytt exactly this. 
You paste it, press enter and it crashes.
Did it on MacOS.

I went through a number of hoops while trying to reproduce it programmatically and then failed.
Hopefully we can think of a test once we know what's the problem.
So yeah, the bisect was manual. 🧑‍🌾

**Comment by som-snytt** [comment]
@Gedochao Thanks! I'll try on Windows proper (when I get it set up). While I think of it, I intended to add on the other ticket (that I can't find) that I didn't mean to suggest bisect was trivial, only that you are good at it!

**Comment by som-snytt** [comment]
I didn't really need a reminder why I never touch Windows -- I'd planned to install Linux natively last year but was lazy -- but I'm reminded that when I first used Scala, it was under cygwin.

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\andre> scala-cli repl --server=false
Welcome to Scala 3.8.3 (17, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala>

scala> def formatTime(numBreadsUsed: BigDecimal, hourRatioInBigDecimal2: Double, machineUtilizationInSecondsAsString9InBCIFormatMaybeTruncated) =
-- [E040] Syntax Error: --------------------------------------------------------
1 |def formatTime(numBreadsUsed: BigDecimal, hourRatioInBigDecimal2: Double, machineUtilizationInSecondsAsString9InBCIFormatMaybeTruncated) =
  |                                                                                                                                       ^
  |                                               ':' expected, but ')' found
-- [E018] Syntax Error: --------------------------------------------------------
1 |def formatTime(numBreadsUsed: BigDecimal, hourRatioInBigDecimal2: Double, machineUtilizationInSecondsAsString9InBCIFormatMaybeTruncated) =
  |                                                                                                                                          ^
  |                                         expression expected but eof found
  |
  | longer explanation available when compiling with `-explain`

scala>
```
This is the same as under WSL. I see cs doesn't put Java on the path but sets JAVA_HOME, which scala-cli does not use. Not sure if the official "install script" does something different, but I had cs already, so I installed Java 25, then `cs setup --jvm 25`.

Note that I can't see the prompt that is shown in the plain text above.

<img width="304" height="166" alt="Image" src="https://github.com/user-attachments/assets/40a24651-74c4-4006-b3de-70734f4a5a30" />

The `cmd` terminal is black background and shows a magenta prompt.

Maybe if I were a regular Windows user, I would have done something slightly different and it would work. But if I were not a regular user of Scala, I would not be one after this experience.

**Comment by som-snytt** [comment]
Reproducers may wish to try HEAD with the linked fix https://github.com/scala/scala3/pull/25738

The old PR was to allow indent in parenthesized `if` conditional, so it allows parsing to continue until the current region is nullified in error recovery, an example of which is fixed in the linked PR.

**Comment by som-snytt** [comment]
Looking at a different issue, I realized that the difference with REPL is that there are ~two~ three opportunities to fail, when parsing for compilation and also for highlighting, and also for "accept line" test which checks `isIncomplete`; and scalac highlights for error reporting, but REPL highlights for redisplay when readLine.

Separately, I recall JLine had code to detect whether text had been pasted (versus entered quickly at the keyboard); I don't know if it still does that; and I don't remember the what's the word "interaction diagram" JLine line parsing and highlighting.

**Comment by SolalPirelli** [comment]
Does not repro on main, perhaps fixed by som-snytt's PR on what looks like a similar issue.
