### ISSUE TITLE
3.1.3-RC2 is not able to compile `scala3-compiler` from current `main`

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#14938]
## Compiler version

3.1.3-RC2

## Output

```
[error] -- [E007] Type Mismatch Error: /Users/pmarks/dotty/compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala:126:18
[error] 126 |              |  $ex
[error]     |                  ^^
[error]     |                  Found:    (ex : Throwable)
[error]     |                  Required: dotty.tools.dotc.printing.Formatting.Shown
[error]     |
[error]     | longer explanation available when compiling with `-explain`
[error] one error found
[error] (scala3-compiler / Compile / compileIncremental) Compilation failed
```

## Expectation

Stuff compiles!

**Comment by nicolasstucki** [comment]
Probably introduced in #14455

**Comment by nicolasstucki** [comment]
We seem to be missing a given `Show[Throwable]` but we have one for `Show[Exception]`.

https://github.com/lampepfl/dotty/pull/14455/files#diff-1aeccc1856f9265f1358bb106fe44428b9aa9b4d353bd1a85b5799a00e810b9cR69

**Comment by dwijnand** [comment]
How did this show up?  The other community build?
