### ISSUE TITLE
 Bad symbolic reference. A signature compilation error

### ISSUE THREAD

**Issue by chungonn** [lampepfl/dotty#8849]
The code compiles in Scala 2.13.1 but emits error on dotty 0.24.0-RC1

## Minimized code
***build.sbt***
```Scala
val dottyVersion = "0.24.0-RC1"

lazy val root = project
  .in(file("."))
  .settings(
    name := "dotty-simple",
    version := "0.1.0",

    scalaVersion := dottyVersion,

    libraryDependencies ++= Seq(
      "org.threeten" % "threeten-extra" % "1.5.0",
      "com.novocode" % "junit-interface" % "0.11" % "test",
      "ch.epfl.lamp" %% "dotty-staging" % scalaVersion.value
    )
  )

```
***code***
```Scala
def toMyInterval(value: String): org.threeten.extra.Interval = org.threeten.extra.Interval.parse(value)

object Interval310 {
  def main(args: Array[String]): Unit = {
    println("hello world")
  }
}
```

## Output

```scala
[info] Compiling 1 Scala source to /home/chungonn/development/scala3/explore/dotty-project-template/target/scala-0.24/classes ...
[error] Bad symbolic reference. A signature
[error] refers to FromString/T in package org.joda.convert which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling the signature.
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed 1 May, 2020 2:05:19 PM
```

**Comment by griggt** [comment]
Alternative minimization without the `threeten-extra` dependency:

foo/Foo.java

```java
package foo;

import org.joda.convert.FromString;

public final class Foo {
    @FromString
    public static Foo parse(CharSequence t) { throw new UnsupportedOperationException(); }
}
```

test.scala

```scala
import foo.Foo

object Test {
  val bar = Foo.parse("")
}
```

```
$ javac -classpath $JARS/joda-convert-2.2.1.jar foo/Foo.java

# note: joda-convert-2.2.1.jar not on dotc classpath
$ dotc test.scala
Bad symbolic reference. A signature
refers to FromString/T in package org.joda.convert which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling the signature.
1 error found
```

**Comment by griggt** [comment]
This is a duplicate of #8554 which is fixed by #9096.

@smarter Do you feel that the test you wrote for #9096 is sufficient to close this issue?

**Comment by smarter** [comment]
Yeah seems like this is the same.
